### ISSUE TITLE
Using Navigation Drawer Layout for EventsActivity

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#100]
To be done after: #93 
Sub Issue: #92 

Currently **framelayout** is used for **EventsActivity**. Instead **Navigation Drawer** should be used for required navigations. 
To be done with **EventsActivity MVP implementaion**

Navigations (For now)
- Logout

**Comment by iamareebjamal** [comment]
What should be the contents of NavigationDrawer

**Comment by niranjan94** [comment]
@iamareebjamal yea. Currently that should suffice. Perhaps you could show the current logged in user's name too.
