### ISSUE TITLE
Build fails due to issue with Android Plugin for Gradle 3.1.2

### ISSUE THREAD

**Issue by brijeshshah13** [fossasia/open-event-orga-app#1003]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Building the latest development branch fails due to Known Issues with Android Plugin for Gradle 3.1.2.

**Expected Behaviour**

To prevent build from failing, we should downgrade to Android Plugin for Gradle 3.1.1 until a new version fixes it.

**Steps to reproduce it**

Pull the latest changes of the development branch and try to build the project.

**LogCat for the issue**

Error message: `Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.
`

**Screenshots of the issue**

N/A.
    
**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
https://stackoverflow.com/questions/49990933/configuration-on-demand-is-not-supported-by-the-current-version-of-the-android-g

**Comment by brijeshshah13** [comment]
@iamareebjamal Disabling `Configure on demand` will have to performed by everyone, instead we could just wait out till the newer version comes out. After all, we are not downgrading all the way back to 3.1.0.

**Comment by iamareebjamal** [comment]
Is this a bug or standard behaviour. Gradle build is working on travis. Now it depends on if this change is permanent or not

**Comment by brijeshshah13** [comment]
It is a bug. Here, it has been mentioned in the Known issues as well: https://developer.android.com/studio/known-issues
