### ISSUE TITLE
Adding option to add description in tickets

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1005]
### Feature Request

**Feature Description**
Currently there is no option to enter description of the ticket during its creation. I would like to add a field where the user can enter a short description about it.

**Would you like to work on the issue?**
Yes

@iamareebjamal I would like to work on this

**Comment by sridharjajoo** [comment]
Sure. This field is required so that the end user can get to know more information about the ticket for eg.
 If the tickets get SOLD OUT, is there any other way to buy them or is there option to buy ticket from the event site itself.

**Comment by iamareebjamal** [comment]
This is server requirement. Not orga app's responsibility

**Comment by sridharjajoo** [comment]
Can you tell about what other data is missing from the ticket?I thought the description is missing and hence added it

**Comment by iamareebjamal** [comment]
No data is missing from ticket. You can confirm from API docs
