### ISSUE TITLE
Set a placeholder image for Sponsor

### ISSUE THREAD

**Issue by brijeshshah13** [fossasia/open-event-orga-app#1008]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Currently, no placeholder image is set to be displayed if the Logo URL is kept empty while creating a Sponsor, leaving the UI mysterious and incomplete. We can use the existing `cirlce_placeholder.xml` drawable as the placeholder.

Before:

![screenshot_20180602-202432](https://user-images.githubusercontent.com/18366144/40877821-931b05b6-66a4-11e8-9e26-ac2ebe22f25b.png)

After:

![screenshot_20180602-203511](https://user-images.githubusercontent.com/18366144/40877822-96f7b06c-66a4-11e8-9466-1ae966c2d4b7.png)

Previous

**Would you like to work on the issue?**

Yes.

**Comment by brijeshshah13** [comment]
@iamareebjamal Please share your view for the same.

**Comment by iamareebjamal** [comment]
Go ahead, but use a different placeholder. The one we are using for events and such

**Comment by brijeshshah13** [comment]
@iamareebjamal Alright. Will send a PR right away with the placeholder used for events.
