### ISSUE TITLE
Making Single Tabbed Event Activity

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#101]
To be done after: #100 
Sub Issue: #92 

Getting all event related functionality on a single screen under event title will be more convenient than navigating through each of them.

Tabs

- Dashboard - event related stats containing ticket sales, attendees checked-ins

- Attendees - attendees list with QR code scan option

- Tracks and Sessions**

- Communicate**

**Can be left empty for now. We can take these as separate issues later @iamareebjamal @Ronak-59 @niranjan94 What do you think ?

**Comment by iamareebjamal** [comment]
Correct. As soon as the Login MVP is finished, we will move to convert EventDetails and other components to MVP, and then it'll be feature addition

**Comment by mejariamol** [comment]
@iamareebjamal 
**Bottom Navigation Activity** should be preferred over **Tabbed activity**. as bottom navigation is located in a more ergonomic location on mobile device. What do you think?

**Comment by iamareebjamal** [comment]
How many pages will be there on this screen?

**Comment by mejariamol** [comment]
Total 4 -details, attendees, tracksandsessions, communicate

**Comment by iamareebjamal** [comment]
OK, Bottom Navigation sounds cool, but do test it first. There was a severe performance issue even in the Google I/O app because of the bottom navigation implementation
