### ISSUE TITLE
Fix Navigation issues throughout the app

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1011]
### Bug Report    

Parent issue for all the current navigation glitches in the app.

**Comment by srv-twry** [comment]
@mishuvs Can I work on it in case you aren't  ?

**Comment by iamareebjamal** [comment]
@srv-twry @mishuvs Also try to solve other navigation related bugs in the same PR. There are a lot of similar issues. Make this s parent issue and solve these

**Comment by srv-twry** [comment]
@mishuvs Can you change the title to "Fix Navigation issues in the app" or something like that ?

**Comment by mishuvs** [comment]
@srv-twry Priyanshu  is probably working on https://github.com/fossasia/open-event-orga-app/pull/977 which I think will automatically solve the navigation issues.

And for the screen rotation issue, as you pointed out, conversion to MVVM will solve it automatically. So I doubt if we should keep these issues open. https://github.com/fossasia/open-event-orga-app/issues/562 should be the parent issue for that IMO.

(Sorry for the late reply)

**Comment by Masquerade0097** [comment]
@mishuvs @iamareebjamal Yes, I'm working on fixing Navigation throughout the app. I will update the PR #977 and try to resolve it asap.

**Comment by iamareebjamal** [comment]
@Masquerade0097 The new navigation component is not compatible with our flat navigation via Navigation Drawer. So be aware of that. This issue needs to be solved separately

**Comment by Masquerade0097** [comment]
@iamareebjamal It seems it is not compatible with flat navigation. But I was trying to do as suggested under topic `Tie destinations to menu-driven UI components ` [here](https://developer.android.com/topic/libraries/architecture/navigation/navigation-implementing) but the arguments are not being sent to fragments when using drawer. So, I guess I should implement Navigation Components only for AuthActivity and OrganizerDetailActivity and skip MainActivity for now ?

**Comment by Masquerade0097** [comment]
@iamareebjamal Should I proceed with what I mentioned in above comment ?

**Comment by Masquerade0097** [comment]
@iamareebjamal I've already implemented them for Auth Activity in the WIP PR :disappointed: . Anyways, I'll close it.

**Comment by iamareebjamal** [comment]
Let it just be for the activity you've implemented. Don't add it for the rest

**Comment by Masquerade0097** [comment]
@iamareebjamal The Navigation Component also have issues with fragment transition animations along with others as discussed above .So, I've closed the PR and issue #966 for now.

**Comment by Masquerade0097** [comment]
@mishuvs Please list the navigation bugs in the issue description so that child issues can be created to work on them.

**Comment by mishuvs** [comment]
@Masquerade0097 Couldn't find. I think this can be closed.
