### ISSUE TITLE
Implement Orders Endpoint

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1012]
### Feature Request

The following features should be implemented regarding Orders endpoint, the features are consistent with eventbrite.

- [x]  List Orders Under Event

- [x]  Order Details

- [ ]  Create Order

**Child Issue**
#522 
   
**Would you like to work on the issue?**

Yes

**Comment by srv-twry** [comment]
@Masquerade0097 Unfortunately the Order's API is buggy and isn't working properly as far as i know. Please make sure you test it before working on this one.
Order's API has a few prerequisites before it can work properly:
1. Stripe - (PR opened in server)
2. Paypal - (working)
3. Tax - (PR open in the server)

Once they are done, me or anyone else would have to fix(if it's buggy) the order's API. Then only it can implemented here.

CC: @iamareebjamal

**Comment by iamareebjamal** [comment]
We juat need to show orders and their details

**Comment by Masquerade0097** [comment]
@srv-twry @iamareebjamal I have tested Listing and Details of Orders endpoint and it is working fine.

**Comment by Masquerade0097** [comment]
**Status** :  The issue is on hold till enhancements are made in server to create orders for onsite attendee.
