### ISSUE TITLE
Rename Navigation Drawer items

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1013]
### Chore 

**Chore Description**

Few menu items in the Drawer layout should be renamed so that the Drawer layout of Orga App looks similar to EventBrite app. This will help users to make the transition smooth for users who choose to migrate to Orga app from EventBrite app.

1. Attendees -> Check In
2. Change the Date format displayed in Drawer to `DAY, MONTH-DATE, TIME` 
3. Change Attendee Drawable.
   
**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
@Masquerade0097 Can I take this issue up?

**Comment by Masquerade0097** [comment]
@sridharjajoo Sorry, I intend to work on it.
