### ISSUE TITLE
Option to toggle Gross and Net Sales

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1015]
### Feature Request

**Feature Description**

Currently the user can only see Gross Sales in Dashboard. There should be an option in Settings Fragment which allow user to toggle between Gross sales and Net Sales to be shown in Dashboard.  The flow is in accordance with EventBrite app. Below is a gif of EventBrite for the same.

![20180605123203-7c011ad592 gif-2-mp4 com](https://user-images.githubusercontent.com/23634977/40967799-a723616e-68d1-11e8-9bd6-8890c2d1c3fb.gif)

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal For calculating net sales, we need total expenses of seller which I guess we don't have. So how should I proceed ?

**Comment by iamareebjamal** [comment]
Hence we can't move forward with this. IMO all these calculations and stats should be available from server and not calculated on device
