### ISSUE TITLE
Change common developer email address to a real email address

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1017]
**Is it a ?**

- [x] Chore
    
### Chore

**Description**

The common developer email should be a real verified email address so that forgot password feature could be tested and the admin rights can be obtained.

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@mishuvs While you are at it. Provide co-organizer access to current Orga App developers to avoid server endpoints access issues.

**Comment by mishuvs** [comment]
@Masquerade0097 I am not aware about how to provide co-organizer access. Please provide a reference doc or tell me how.
And would it be okay if I use disposable email like mailinator? Would be openly accessible.

**Comment by Masquerade0097** [comment]
@mishuvs Use the API to assign Roles and send Role Invites to other developers from this account.
