### ISSUE TITLE
Functionality to Update FAQ

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1031]
### Feature Request

**Feature Description**

User will be able to update the details of FAQ.
   

**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
@iamareebjamal @Masquerade0097 Can I take up this issue?

**Comment by Masquerade0097** [comment]
@iamareebjamal We arn't showing FAQ in release version. So, should it be closed ?
