### ISSUE TITLE
Interface name should start with "I"

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#104]
As we will be using many interfaces, we should follow this practice for interface name that it should start with **I**. for example `ILoginView`, `ILoginPresenter`.

**Comment by iamareebjamal** [comment]
Agree, please send pull request

**Comment by mejariamol** [comment]
@iamareebjamal sending.

**Comment by iamareebjamal** [comment]
Also please change the implementation to `LoginView` for `ILoginView` interface
