### ISSUE TITLE
Add tests for the Speaker details module

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#1043]
### Chore

**Description**

Add tests for the speaker details module:

- [ ] Update the speaker repository tests
- [x] Tests for the SpeakerDetailsViewModel

**Would you like to work on the issue?**

Yes

**Parent issue**

#925

**Comment by srv-twry** [comment]
@Masquerade0097 @sridharjajoo @mishuvs You guys can claim this if you want. I am having to work on the server as a priority and hence won't be able to work on it in atleast a week. This is the only issue left in implementing the speakers module. Thanks

**Comment by sridharjajoo** [comment]
Sure I'll work on them

**Comment by sridharjajoo** [comment]
@Masquerade0097 Can you reopen this please. Another test needs to be added. (Update SpeakerRepository tests)
