### ISSUE TITLE
Use single network call with ?include in Speaker details module

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#1060]
### Bug Report    

**Actual Behaviour**

Right now we make two network calls. First to fetch the speaker details and the second to fetch the sessions under the speaker.

**Expected Behaviour**

We can use ?include to get the sessions under a speaker in the same network call.

**Would you like to work on the issue?**

Yes

**Parent issue**

#925

**Comment by srv-twry** [comment]
@iamareebjamal I am facing an issue here:
The Speaker list is fetched using this API call - `events/{id}/speakers?include=event&fields[event]=id&page[size]=0` i.e it doesn't contain the speaker's sessions. Now when someone clicks on a speaker, the cached speaker is shown to the user which doesn't contain the sessions. 
I have to refresh the speaker details to get his/her sessions.
Possible solutions:
1. In the `onStart` method of the speaker details fragment use reload = True instead of false. It would work but that would mean we will be making unnecessary calls since it will make calls after screen rotation as well.

2. I could try to fetch the sessions also with the speakers list but that would mean fetching unused and meaning less information which won't even be used in that fragment.

How to deal with this ?

**Comment by iamareebjamal** [comment]
Then I guess current implementation is optimal?

**Comment by srv-twry** [comment]
Yes, it does seem to be the case. Closing this. Will reopen in case I can figure out a way to reduce it to a single call.
