### ISSUE TITLE
Implementing Contextual Action Bar for Tracks Fragment

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1062]
### Feature Request

**Feature Description**
Implementing CAB for selecting multiple tracks in Tracks Fragment.

**Would you like to work on the issue?**
Yes

 **Parent Issue**
#1042

**Comment by Masquerade0097** [comment]
@sridharjajoo I was planning to send a single PR for #1042 as it's not big enough. Can I send include this in the PR too ?

**Comment by sridharjajoo** [comment]
I would like to send  a P.R for this.
