### ISSUE TITLE
Allow adding device name to track check-ins and sales

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1074]
**Is it a ?**

- [x] Feature Request

### Feature Request

**Feature Description**

The EventBrite app has an option to add device name in Device Settings. The device name is used to track check-ins and sales. The Organizer App also needs to support the same.

<img src="https://user-images.githubusercontent.com/35009811/41453654-2d4e2584-7094-11e8-90d6-2798c0584079.png" width="300"/>
   
**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
First this needs to be supported by server

**Comment by mishuvs** [comment]
@iamareebjamal Right now we may only create the device name preference. This shared preference can then be used when attendee check-in and sales code could to be changed, i.e when it's implemented on the server. 
I have created an issue on the server, and have requested suggestions to move forth.

**Comment by iamareebjamal** [comment]
OK
