### ISSUE TITLE
CreateSessionFragment should close on Session creation

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1077]
### Bug Report    

**Actual Behaviour**

CreateSessionFragment do not close on session creation. The user has to explicitly press back button.

**Expected Behaviour**

CreateSessionFragment should close on successful session creation.

**Steps to reproduce it**

Create Session in App.

**Android version and Phone Model**

Jelly Bean and Moto G4 Plus
    
**Would you like to work on the issue?**

Yes

**Comment by mishuvs** [comment]
@Masquerade0097 Adding a GIF would be helpful.
