### ISSUE TITLE
Project structure refactoring

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#108]
Current project structure is not module wise and hence not easily maintainable.
**For example** if someone wants to make some changes in the events showing page then he will need to search for related files in all of the directories.
If our project structure is module wise such that all the related files will be contained in a module. For example `app/events` is a module somewhat like below -
```
events
  | EventsActivity.java
  | EventsContract.java
  | EventsPresenter.java
```
`EventsContract` will contain the interfaces required `View.java`, `Presenter.java`.

`data` should be separate module. which will consist one interface and one class implementing it. (For now)

This would make code readability better. reference - https://github.com/googlesamples/android-architecture/tree/todo-mvp

@niranjan94 @iamareebjamal @Ronak-59 What are your views ?

**Comment by iamareebjamal** [comment]
We won't be encapsulating interfaces into a class, but idea of package by feature is good.

**Comment by iamareebjamal** [comment]
The problem by using per contract per feature is that we can't reuse contract info outside package (it becomes a bad practice) and encapsulating interfaces in a class is opinionated and can increase verbosity of code

Otherwise package by feature is good

**Comment by iamareebjamal** [comment]
Each package should also contain its model and common models must be provided in `common` package under correct sub-package

Please share the complete structure and design of current classes before sending PR as it'll be easier to understand it here

**Comment by mejariamol** [comment]
@iamareebjamal yes sure.

**Comment by mejariamol** [comment]
Let's say for `login` module, the module structure will be 
```
├── app
    ├── login
    │   ├── LoginActivity.java
    │   ├── LoginContract.java
    │   └── LoginPresenter.java
    └── ...
```
`LoginContract.java` will contain both the interfaces - `View` & `Presenter`  and will look something like -
```
public interface LoginContract {

    interface View {

        void showProgressBar(boolean show);

        void onLoginSuccess();

        void onLoginError(String error);

    }

    interface Presenter {

        void attach();

        void detach();

        void login(String email, String password);

    }
}
```
@iamareebjamal For data I am still thinking. Will share the complete design by tonight.

**Comment by iamareebjamal** [comment]
Let's not encapsulate the contract inside a class, rather make a contract package in each feature

**Comment by iamareebjamal** [comment]
Using a class couples them inherently and IDEs force `Class.Inner` syntax whereas in package we can import View or Presenter freely

**Comment by mejariamol** [comment]
>Using a class couples them inherently and IDEs force Class.Inner syntax whereas in package we can import View or Presenter freely

Which IDE's force `Class.Inner` syntax at the inner interfaces of the interface? 
Creating `contract` package in each module will be redundant.

I have referred this convention from  https://github.com/googlesamples/android-architecture/tree/todo-mvp. there shouldn't be any trouble in this approach.

**Comment by iamareebjamal** [comment]
This is an opinionated format and structure of that app is very simple for that use case

Imagine when interfaces will contain many methods, the contract class will increase in size and there will be unnecessary coupling

And google is not generally known to follow even their conventions right. 
Look at the broken AsyncTask API they try to push down our throat and even new architecture components which force you to write an MVVM implementation.

We should have as less coupling as possible.

**Comment by mejariamol** [comment]
I have some doubt about our current cache model. 

1. does cache get stored for just an app session or is it always available like local database ?

**Comment by iamareebjamal** [comment]
It's in memory cache, it does not persist after app session

**Comment by mejariamol** [comment]
Then we should maintain sqlite database for cache. What do you think?

**Comment by iamareebjamal** [comment]
First we should look at implementing the MVP pattern, then we need to discuss how fresh the data must be for the organizer and how it must be refreshed if we use SQlite

It's another issue of its own
