### ISSUE TITLE
Refactor SponsorsListPresenterTest.java

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1083]
### Chore

**Description**

Refactor SponsorsPresenterTest from `org.fossasia.openevent.app.core.sponsor.list` to `org.fossasia.openevent.app.core.presenter`.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
No actually, tests should remain in same package as class being tested

**Comment by Masquerade0097** [comment]
Yes, you're right. I saw it later that the presenter contains protected methods which can be tested in the same package so it must remain in same package. Closing this.
