### ISSUE TITLE
Bad UX of BaseBottomSheet Fragment

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1087]
### Feature Request

**Feature Description**

Whenever a user enters a field in the creation form, most of the BaseBottomSheetFragment gets covered by keyboard. So, the user can only see the current input field and the keyboard at a time. All other fields gets hidden.
After that the user has to press button to put the keyboard down then scroll to other field and then again use the keyboard. 
 
**GIF for the issue**
![20180616062447-7c011ad592 gif-2-mp4 com](https://user-images.githubusercontent.com/23634977/41495377-4c05bf32-7143-11e8-8a8b-f4d4df26e0b2.gif)

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@sridharjajoo @mishuvs @iamareebjamal Please provide your suggestions regarding this. Maybe, we can set the enter key to shift focus from one field to the next one on clicking.

**Comment by sridharjajoo** [comment]
Yes that will be a good option.

**Comment by iamareebjamal** [comment]
I would say ditch BottomSheet for a Fragment

**Comment by Masquerade0097** [comment]
Let's shift to Fragment then.

**Comment by mishuvs** [comment]
I tried adding appropriate padding at the bottom. It works fine.
Doesn't look absurd since only some part of the BottomSheet is open at first and when the user enters the first field, and the space if occupied by keyboard when user comes to the last field.

Switching to fragment is also good.
