### ISSUE TITLE
Add checklist to PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1091]
**Is it a ?**

- [x] Chore
    
### Chore

**Description**

Adding checklist for 

1. having read Contribution & Best practices Guide,
2. having checked for PMD and check-style issues, and
3. the branch being up-to-date with the Upstream development branch

could help existing and new developers send better pull requests.

**Would you like to work on the issue?**

@iamareebjamal should this be added? (if yes, is something missing in the checklist)

**Comment by iamareebjamal** [comment]
Yes
