### ISSUE TITLE
Upload images in App

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1093]
### Feature Request

**Feature Description**

User should be able to upload images from local storage to the app. This will be used for  -

1. Uploading profile picture.
2. Uploading image in event creation.
   

**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
@Masquerade0097 Are you working on it?

**Comment by Masquerade0097** [comment]
@sridharjajoo I'm working on it. I will send a PR soon. In case you are short of issues, please take any of the issue labeled as open-for-all.

**Comment by Smit2010** [comment]
I would like to contribute to this issue. Is this been already done?

**Comment by iamareebjamal** [comment]
Not completed

**Comment by angmas1** [comment]
Is anyone working on this? If not can I contribute?

**Comment by Smit2010** [comment]
Yes, I have been working but for last week I wasn't able to code due to my exams. Now I am continuing my remaining code.
