### ISSUE TITLE
Improving the Login Functionality

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1095]
### Feature Request

**Feature Description**
When the user logs out of the orga app, he is redirected to the login screen and the login credentials are empty. IMO the login credentials should be autofilled by the user name and the password of the last logged out user.
Eventbrite uses a similar functionality as seen below.
![ezgif com-resize 15](https://user-images.githubusercontent.com/20684618/41501449-3c34d1a4-71c2-11e8-8a0f-b5f81930e91b.gif)

**Would you like to work on the issue?**
Yes.

**Comment by iamareebjamal** [comment]
How will you store the password?

**Comment by sridharjajoo** [comment]
I am thinking of storing it in the Android Keystore and then retrieving it in the Login Fragment.

**Comment by srv-twry** [comment]
Yeah, it does seem to be safe: https://medium.com/@josiassena/using-the-android-keystore-system-to-store-sensitive-information-3a56175a454b 
I haven't gone through the whole blog though.

**Comment by sridharjajoo** [comment]
@iamareebjamal I tried implementing the above functionality with Android Keystore but the process of implementing it is becoming a bit cumbersome as the process of key generation is different in API > 23 and API<23 (I was following this article [link](https://medium.com/@ericfu/securely-storing-secrets-in-an-android-application-501f030ae5a3)). Should I try implementing Credential Objects to handle it (Google Smart lock)?

**Comment by sridharjajoo** [comment]
@iamareebjamal I made some modifications to the first method itself and used to encrypt the data. If the second method is used the authentication is handled by the google play services authentication api and we donot need to handle encryption of sensitive data.

**Comment by iamareebjamal** [comment]
We don't want to depend on 3rd party library if we can help it
