### ISSUE TITLE
Fix build warnings in the app

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#1105]
### Bug Report    

**Actual Behaviour**

A few warnings are shown when building the app.
For e.g. In the Speaker model, we have `@ToString(exclude = {"event", "sessions", "user"})` but the `sessions` field doesn't exist in the model.

**Expected Behaviour**

The source of warnings should be fixed as much as possible.

**Would you like to work on the issue?**

No, can be taken by others.

**Comment by sridharjajoo** [comment]
@srv-twry I would like to take it. Also I would like to eliminate other warnings as well that are being caused through this issue.

**Comment by srv-twry** [comment]
yes, please go ahead :smile:
