### ISSUE TITLE
use feedback function

### ISSUE THREAD

**Issue by yohanym95** [fossasia/open-event-orga-app#1108]
developers,
use feedback function because then you can get idea from feedback and then you can develop this app.

**Comment by Masquerade0097** [comment]
Incorporation of Feedback Function can prove useful. 
@yohanym95 Are you willing to work on this issue ?

**Comment by sridharjajoo** [comment]
@iamareebjamal Should we add a link to a google form here as it is done in event brite?

**Comment by sridharjajoo** [comment]
@mishuvs @Masquerade0097 @iamareebjamal Where should we add the feedback option? In the navigation drawer or in the settings option. Because navigation drawer already has an option of Feedback and it might confuse the user
