### ISSUE TITLE
Save viewpager position in the Events list

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#1121]
### Bug Report    

**Actual Behaviour**

When we rotate the screen on the Events list screen, the ViewPager automatically moves to the `Live` section.

**Expected Behaviour**

It should stay in the same tab.

**Steps to reproduce it**

Open Events list and move to the `Past` tab. Now rotate the screen. It will move back to the `Live` tab.

**Would you like to work on the issue?**

No.

**Comment by srv-twry** [comment]
@mishuvs @sridharjajoo @Masquerade0097 One of you may work on this.

**Comment by mishuvs** [comment]
@srv-twry It's not view pager, it's only the Bottom Navigation right now. View Pager would be implemented soon, and I'll remember to check for this issue.
