### ISSUE TITLE
Implement Swipe to CheckIn/Out in Attendee List

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1130]
### Feature Request

**Feature Description**

1. Implement Swipe to check in/out in Attendee List layout. 
2. Change the Attendee List layout item UI to make it similar to EventBrite.

**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
I will like to work on it

**Comment by sridharjajoo** [comment]
This is a just a small UI enhancement with lesser priority. Hence can be closed.
