### ISSUE TITLE
Adding material animations while fragment transition

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1145]
### Feature Request

**Feature Description**
To make the app more attractive, I propose to add circular reveal effect during fragment transition. So whenever the FAB is selected to transition to a new fragment  (when FAB is selected to create a new event, faq, session,ticket etc.), the new fragment should appear on circular reveal.

**Would you like to work on the issue?**
Yes.

**Comment by mariobehling** [comment]
Please keep it simple. Get the basics working. We can follow up on such ideas later once it is stable. Therefore closing it.
