### ISSUE TITLE
Send Order Receipt to the User via email

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1176]
### Feature Request

**Feature Description**
After an order is created there should be a feature to send the receipt of the order to the attendee.

![image](https://user-images.githubusercontent.com/20684618/42416265-a7487da8-8287-11e8-8667-47b178d41ed8.png)

**Would you like to work on the issue?**
Yes.

@Masquerade0097 Please add a dependency label as an issue for it has been created in the server repository.

**Comment by Masquerade0097** [comment]
It's implemented in server. Therefore, removing dependencies label.
