### ISSUE TITLE
Upload User Profile Picture from Local Storage

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1182]
### Feature Request

**Feature Description**

The user should be able to upload images from device local storage to the server and use the returned URL to show the profile picture in the app.
   
**Parent Issue**

#1093 

**Would you like to work on the issue?**

Yes

**Comment by ShridharGoel** [comment]
Done in #1517

**Comment by iamareebjamal** [comment]
Great Job

**Comment by ShridharGoel** [comment]
Thanks
