### ISSUE TITLE
Migrate FAQ list to MVVM.

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#1186]
### Feature Request

**Feature Description**

FAQ list should be migrated to follow the MVVM architecture.

**Would you like to work on the issue?**

Yes

**Parent**
#562

**Comment by srv-twry** [comment]
@sridharjajoo @mishuvs @Masquerade0097 You can take this one :( I am very busy in the frontend.

**Comment by Masquerade0097** [comment]
Not in the release version. Closing this for now.
