### ISSUE TITLE
Change SponsorsPresenter to ViewModel

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1187]
### Chore

**Description**
SponsorsPresenter needs to refactored to ViewModel.

**Would you like to work on the issue?**
Yes

**Parent issue**
#562

**Comment by Masquerade0097** [comment]
@sridharjajoo It's not a priority right now. Can it be closed ?

**Comment by sridharjajoo** [comment]
Sure as it isn't in the release version it can be closed
