### ISSUE TITLE
Disable proguard in the release version

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1196]
### Bug Report    

**Actual Behaviour**
Currently when we are in using the release apk , we aren't able to login into the app nor is the signup functionality working.
This is because of the enabled proguard. When I tried disabling it, the above mentioned features are working.

**Would you like to work on the issue?**
Yes.

**Comment by sridharjajoo** [comment]
We can temporarily disable proguard as we need to release the app. Then we can search for the reason behind it and update the proguard-rules.pro file.

**Comment by iamareebjamal** [comment]
Not good, check why it's happening. Proguard is specifically for release version
