### ISSUE TITLE
Add Support link

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1227]
**Is it a ?**

- [x] Feature Request
    
### Feature Request

**Feature Description**

An option similar to 'How to use the app' in EventBrite is needed.

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@mishuvs Similar to `How to use the app` ? AFAIK there is no webpage for this in Frontend.

**Comment by mishuvs** [comment]
Eventyay has the support document available here: http://support.eventyay.com/
I agree that there's no Organizer App specific webpage here, but when we'll add the documentation and Work Product Submission for GSoC, I think we'll have to add support link for the app as well.
Besides, most apps do provide support links. So IMO there is some point in adding it.

**Comment by Masquerade0097** [comment]
@iamareebjamal Please provide your views?

**Comment by iamareebjamal** [comment]
Right now there isn't anything for app docs, so what should be done @mishuvs

**Comment by mishuvs** [comment]
Then we can close this I think until we have a doc to link, or we can provide Eventyay main support link. Whichever you see fit.
