### ISSUE TITLE
Hide Event Statistics in Release Version

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1234]
### Chore

**Description**
The **Event Statistics** section on the Dashboard needs to be hidden in the Release version because it shows statistics of  fields such as Sponsors, Speakers, Sessions etc. which are anyways hidden in the Navigation drawer in the Release version of the app.

**Would you like to work on the issue?**
Yes

**Comment by Masquerade0097** [comment]
@sridharjajoo I think we should show the statistics to the Organizer in the app. 

>  fields such as Sponsors, Speakers, Sessions etc. which are anyways hidden in the Navigation drawer

Yes, they are hidden but the Organizer can create/edit these fields via Frontend. It would be good if we show the overview of the event statistics for these fields even if we are not creating them in Orga app.

**CC** @iamareebjamal

**Comment by iamareebjamal** [comment]
I agree that it should be shown
