### ISSUE TITLE
Enable proguard and minifying of resources

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#125]
We use RxJava and Vision API like huge libraries and app size is 3 MB currently for almost a hello world like app. We should configure proguard so that release APK size remains less, and to test the release APK, we should add a release variant to the travis branch as well

I tested it out. Proguard minified the app size to 1.5 MB from 3.3 MB

@niranjan94 @mejariamol Should we do this?

**Comment by niranjan94** [comment]
@iamareebjamal yes. We should do this. I don't see why not.

**Comment by iamareebjamal** [comment]
Fixed by #126
