### ISSUE TITLE
ViewPager in Stepper should not allow swiping

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1275]
**Is it a ?**

- [x] Bug Report

### Bug Report    

**Actual Behaviour**

Stepper allows user to swipe through pages. And when moved to next step, the previous steps are shown as completed in the indicator even if no field is filled.

**Expected Behaviour**

Only the buttons should be allowed to take the user to the next step.

**Would you like to work on the issue?**

Open for all | @sridharjajoo ?

**Comment by sridharjajoo** [comment]
@mishuvs Why would you want to disable this swipe functionality?

**Comment by mishuvs** [comment]
It has a clear bug:
> when moved to next step, the previous steps are shown as completed in the indicator even if no field is filled.

And this is a common behaviour across many applications. EventBrite doesn't allow going to the next step unless you fill out first details. Also checkout the frontend, they also don't allow going to next 2 steps in Event Wizard unless you complete step 1.

**Comment by iamareebjamal** [comment]
@sridharjajoo If bugs are different, then issues are different, requiring different PRs
