### ISSUE TITLE
Attendees not loading automatically

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1279]
### Bug Report    

**Actual Behaviour**

1. Attendees are not loading automatically for any event: 
2. Timeout occurs every time for FOSSASIA Summit 2018 as it contains huge number of attendees - attendees can't be loaded even after refresh.

**Expected Behaviour**

Should load automatically when Check In is selected

**Steps to reproduce it**

Select `Check In` from drawer

**Comment by sridharjajoo** [comment]
@mishuvs You should use the template from readme for creating new issues

**Comment by Masquerade0097** [comment]
@mishuvs Attendees are loaded automatically for the event "Google Summer of Code".

**Comment by mishuvs** [comment]
In my device, it sometimes loads automatically and sometimes not. I just tried and it showed a blank screen. Maybe, try checking out different events one after the other.

**Comment by starlord1311** [comment]
@Masquerade0097 can i take up this issue?

**Comment by Masquerade0097** [comment]
@starlord1311 Yes, you can work on it.

**Comment by starlord1311** [comment]
Can you tell me what I am supposed to do?

**Comment by mishuvs** [comment]
@Masquerade0097 Please add the `priority` label. It needs to work for large number of attendees.

**Comment by yohanym95** [comment]
is this issue fixed??

**Comment by ShridharGoel** [comment]
I'm working on this.
