### ISSUE TITLE
Use Fragments instead of Activities

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#128]
- Fragments are lightweight
- Communication between fragments doesn't need parceling/un parceling
- We can retain fragment state across configuration changes
- Easily manage states and transitions using backstack
- Can be used to create Tablet Layout

@mejariamol I have consecutive exams for a few days. Can you take this up?

**Comment by mejariamol** [comment]
@iamareebjamal yes. we **have** to use fragments for bottom view navigation in event module, on which I am working now.
Other than this I don't think we require fragment anywhere else.

**Comment by iamareebjamal** [comment]
Actually, we do because of the reasons I listed above

We need to make this app scalable, so supporting tablet view and other features need fragments

**Comment by mejariamol** [comment]
cool. I will take this up once done with #101

**Comment by iamareebjamal** [comment]
@mejariamol Only need to convert EventsActivity and EventDetailActivity to Fragments

MainActivity will contain a static EventsActivity in XML and on the click of a particular event, show the EventDetailFragment

**Comment by mejariamol** [comment]
We already have event container activity which is hosting event related
fragments.
Now remaining two activities - login activity and events activity are need
to be made to use fragment.

**Comment by iamareebjamal** [comment]
Sorry I was talking about converting EventContainerActivity to fragment
