### ISSUE TITLE
Implement rich text editor for long descriptions in the app

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1307]
### Feature Request

**Feature Description**

Description fields need to support fields like bullet points and special symbols, for which a rich text editor library need to be implemented.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Does the server and frontend have support for this?

**Comment by mishuvs** [comment]
Frontend does support text-style and bullet list and numbered list. We were specifically asked to include support for rich text last time. Maybe, we can add the server support later?

**Comment by iamareebjamal** [comment]
So you'll do it through HTML?

**Comment by mishuvs** [comment]
I was planning to use open source libraries.

**Comment by iamareebjamal** [comment]
For HTML?

**Comment by mishuvs** [comment]
No, I mean libraries for implementing rich text editors, like https://github.com/wasabeef/richeditor-android,  https://github.com/agungsijawir/droid-writer, https://github.com/daothanhduy305/KRichEditor

**Comment by iamareebjamal** [comment]
What do they produce in the end? HTML? Markdown? Quill?

**Comment by mishuvs** [comment]
Most seem to be producing HTML.
