### ISSUE TITLE
Require only necessary information to create an event

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#1324]
### Bug Report    

**Actual Behaviour**

Currently the stepper requires much more information than necessary to create an event.

**Expected Behaviour**

It should only ask for name, description, date and time, and location to create the event.

**Would you like to work on the issue?**

Yes

**Comment by onkarpandit** [comment]
I would like to work on the issue.

**Comment by sridharjajoo** [comment]
Please go ahead

**Comment by ShridharGoel** [comment]
Closed after discussion that it's not needed.
