### ISSUE TITLE
No create event option for newly registered user

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#1326]
### Bug Report    

No create event option is available for newly registered person with no events

@sridharjajoo @Masquerade0097 @mishuvs

**Comment by sridharjajoo** [comment]
I think that is the old apk on playstore which hasn't got updated till now

**Comment by Masquerade0097** [comment]
@iamareebjamal I built the latest release apk with latest changes and the option to create event is present. The playstore one isn't updated I guess.
