### ISSUE TITLE
Modify the update-apk script

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1328]
### Chore

**Description**

According to the points discussed in the meeting the following things need to be changed in the update-apk script

- For the apk's (dev ones) that get generated after merging a PR their names need to be changed to a more informative names For eg.eventyay-organizer-dev-app-debug apk.

- The master apk's should only be generated when the development is merged with master. 
(I think that this is already happening but the whenever a PR gets merged the commit message shows that master apk has also been created )

**Would you like to work on the issue?**
Yes

**Comment by iamareebjamal** [comment]
Second point is not possible. See the discussion on open event android issue and copy it here

**Comment by iamareebjamal** [comment]
> This will render the orphan branch method useless and bloat the repo size to hundreds to megabytes in just 3-4 days and the repo size will only increase. Driving a lot of contributors away. Why don't we use Github's release mechanism rather than branch updation?


> Selective committing will only increase the repo size and contribute to nothing else

> The pslab-android repository was 8 MB in April and increased to 10 MB till this apk model was not used. Now it is 58 MB in just 10 days and will continue to grow
