### ISSUE TITLE
Replace Travis CI build status to Circle CI

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1333]
### Chore

**Description**

Remove Travis CI and add Circle CI build status for development and master branch in README.

**Comment by iamareebjamal** [comment]
Why?

**Comment by Masquerade0097** [comment]
IN the meeting, Mario said that we are not using Travis CI anymore, instead we should show the Circle CI badge in README.

**Comment by iamareebjamal** [comment]
We are using Travis CI for everything including generating APKs. So, circle CI status would denote wrong status

**Comment by iamareebjamal** [comment]
Also, Circle CI is flaky for heavy processes including app building and integration tests and leads to OOM. So if the instructions are to move to Circle CI, then also proceed with caution

**Comment by iamareebjamal** [comment]
It also limits free OSS instances of projects

**Comment by Masquerade0097** [comment]
Okay then, I'll discuss this issue in next meeting. Keeping it on hold till then.
