### ISSUE TITLE
Update the Readme with fdroid link of Eventyay Organizer

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1349]
### Chore

**Description**
The orga app has been released on fdroid and hence the link to it and the fdroid logo should be added to the Readme. Following is the link to the fdroid page.
https://f-droid.org/en/packages/com.eventyay.organizer/

**Comment by GOVINDDIXIT** [comment]
@sridharjajoo  play store link is also not correct

**Comment by GOVINDDIXIT** [comment]
I found this working link on play store. Pls review
https://play.google.com/store/apps/details?id=com.eventyay.organizer

**Comment by sridharjajoo** [comment]
@GOVINDDIXIT The fdroid link is wrong (the image link). It is opening eventyay attendee fdroid page.

**Comment by GOVINDDIXIT** [comment]
Fixed
