### ISSUE TITLE
Add feedback feature in navigation drawer

### ISSUE THREAD

**Issue by GOVINDDIXIT** [fossasia/open-event-orga-app#1362]
**Describe the feature you'd like**
Currently no feedback feature is present in the app. A feedback feature should be present in order to get feedback from non developer users like in Eventbrite app. 

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by GOVINDDIXIT** [comment]
Currently my idea is to use Google forms as in Eventbrite app. @sridharjajoo pls guide

**Comment by sridharjajoo** [comment]
The feature is already present in the app. Check the **Suggestions** item

**Comment by GOVINDDIXIT** [comment]
😅Oops I was having the play store version.
