### ISSUE TITLE
Add how to use app in about section

### ISSUE THREAD

**Issue by GOVINDDIXIT** [fossasia/open-event-orga-app#1363]
**Describe the feature you'd like**
How to use app is missing in about section

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by sats98** [comment]
hi sir, i want to work on this issue.

**Comment by GOVINDDIXIT** [comment]
@sats98  Thanks for your interest but this feature need to be implemented on site first. Currently we don't have any dedicated site for android client.

**Comment by sats98** [comment]
ohk sir . Thanks for informing

**Comment by ShridharGoel** [comment]
Out of scope.
