### ISSUE TITLE
App Crashes because Memory leaks occur while creating event

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-orga-app#1373]
**Describe the bug**
Memory Leaks occur while creating an event

**To Reproduce**
Im still finding out a way to reproduce the bug. i will update the issue as soon i get through
 
**Expected behavior**
No memory leaks should occur and app should not crash

**Screenshots**
![b03f9b7d-1c1b-4674-8c29-e845c18bc2bd](https://user-images.githubusercontent.com/37406965/47451902-8ba38700-d7e6-11e8-878d-0d61f2e31241.jpg)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |OnePlus 5 |
|Android Version| Oreo 8.1|

**Would you like to work on the issue?**
Yes

**Comment by ShridharGoel** [comment]
Not reproducible.
