### ISSUE TITLE
Confirm Password automatically gets filled up on device rotation 

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-orga-app#1374]
**Describe the bug**
The confirm password field in the SignUp Activity automatically gets filled up with your password if you rotate the device. 

**To Reproduce**
1. Go to Sign up activity 
2. Click on Password and type your password
3. Rotate the device .
4. The confirm password field automatically gets filled

**Expected behavior**
It should not automatically get filled.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |One plus 5|
|Android Version|e.g. Oreo 8.1 |

**Would you like to work on the issue?**
YES

**Comment by tavishjain** [comment]
@iamareebjamal this might be closed now

**Comment by iamareebjamal** [comment]
Fixed in #1418
