### ISSUE TITLE
App should exit after 2 continuous back clicks rather than a single one

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-orga-app#1378]
**Describe the feature you'd like**
Presently the app exits on a single back click even if i may have mistakenly pressed the back button. 
The app should ask after one back click to press it again if the user wants to exit and it should exit if the user does so.

**Would you like to work on the issue?**
YES

**Comment by iamareebjamal** [comment]
This is standard behavior on Android and expected

**Comment by codepoet2017390** [comment]
@iamareebjamal  but the app is not showing this behaviour
