### ISSUE TITLE
Update Repo description to include correct APK link

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#138]
Currently, the repo description features wrong link of debug apk -  https://github.com/fossasia/open-event-orga-app/raw/apk/test-android-debug.apk

This should be replaced by  https://github.com/fossasia/open-event-orga-app/raw/apk/test-app-debug.apk
and release version  https://github.com/fossasia/open-event-orga-app/raw/apk/test-app-release-unsigned.apk

@niranjan94 Please take a look

**Comment by niranjan94** [comment]
@iamareebjamal done.
