### ISSUE TITLE
bug: UI fixes in Dashboard

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1382]
**Describe the bug**

1. The separator line present in Dashboard has different width in different sections. The separator line is present at three places of dashboard - 
a) Between Tickets Sold and Checked In
b) In OrderStatistics.
c) In Event Statistics.

2. Add elevation in Event Satistics section.

3. Extra spacing after the ending of Event Statistics section.

**To Reproduce**
Open Dashboard.

**Would you like to work on the issue?**
- [ ] Yes
- [x] No

**Comment by sridharjajoo** [comment]
Please go ahead
