### ISSUE TITLE
Incorrect display of selected item in Navigation Drawer

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1383]
**Describe the bug**
Select Check-In tab in Navigation Drawer then view activity log of any attendee and then press back to land up in Attendee List Fragment. Now, again view the activity log for any attendee and see the navigation drawer. The tab selected will be Dashboard instead of Check-In.

**Expected behavior**
The selcted tab should be Check-In whenever user is in Check-In or it's child fragments.

**Screenshots**
![ezgif-6-ce7c6418d905](https://user-images.githubusercontent.com/23634977/47951341-643a8000-df85-11e8-9cba-7c7917d822d5.gif)

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

**Comment by ShridharGoel** [comment]
I would like to work on this.
