### ISSUE TITLE
Scan QR Code button hides on scroll

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1384]
**Describe the bug**
When the attendee list is scrolled the FAB to scan QR Code gets hidden. 

**Reproduce the bug** 
Select Check-In item from Navigation bar -> Scroll the attendee list.

**Expected behavior**
FAB should not hide, it should become visible again when the scrolling stops.

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

**Comment by iamareebjamal** [comment]
FAB should hide but re-display when scrolling stops

**Comment by ShridharGoel** [comment]
I would like to work on this.
