### ISSUE TITLE
User should be directly able to select image for avatar from the gallery

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/open-event-orga-app#1385]
**Describe the feature you'd like**
The user should be directly able to select an image from the gallery for his avatar rather than uploading an URL for it.

**Would you like to work on the issue?**
YES

**Comment by iamareebjamal** [comment]
Duplicate of #1182

**Comment by codepoet2017390** [comment]
@iamareebjamal can i work on #1182  instead

**Comment by iamareebjamal** [comment]
Yes
