### ISSUE TITLE
Write tests for QR Scan Activity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#139]
Currently, tests for QR Scan Activity are missing. 

I'm working on it

**Comment by iamareebjamal** [comment]
@niranjan94 Also, I want to ask why are we restricted to QR codes only since vision API can detect any kind of barcode

**Comment by niranjan94** [comment]
Two reasons:
- We want to add QR Code scanning feature the web interface too. Using the webcam. In that case, we can only scan QR Codes reliably with a webcam
- Even vision API needs a camera with auto-focus to detect linear barcodes (like Code 128 for example) properly. We didn't want it to be limited by the availability of autofocus. But yea, now-a-days all phones come with autofocus.
