### ISSUE TITLE
No navigation drawer in About activity

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-orga-app#1393]
**Describe the bug**

Navigation drawer cannot be accessed via the 'About' screen

**To Reproduce**

1. Open the navigation drawer.
2. Click on 'About'
3. Try accessing the navigation drawer.
4. Navigation drawer will not open.

**Expected behavior**

Navigation drawer should have come up.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

**Comment by tavishjain** [comment]
I suppose this is working fine and as intended

![open event app](https://user-images.githubusercontent.com/31106411/50549665-ecd45480-0c86-11e9-8755-5d3188afe2f3.gif)

**Comment by ShridharGoel** [comment]
Actually I was thinking that the navigation drawer should be there in the AboutActivity also.

**Comment by ShridharGoel** [comment]
@iamareebjamal Should this be implemented?

**Comment by iamareebjamal** [comment]
No, it's a separate activity
