### ISSUE TITLE
Their should be Minimum and maximum duration of Event.

### ISSUE THREAD

**Issue by ankush-01** [fossasia/open-event-orga-app#1400]
Current Behaviour:
 user can create 1 minute of event to event having 10-15 (or more) years to finish.
Expected Behaviour:
 their should be minimum and maximum duration of event. 
![1de281d0-15bb-4e26-9ac9-0b4ed2c4cc45](https://user-images.githubusercontent.com/33266550/49315472-a7afdd80-f4a2-11e8-9610-e028d66d6fe4.jpg)

**Comment by Masquerade0097** [comment]
I think it's better if server provides this restriction rather than using some hard coded values here.

**Comment by iamareebjamal** [comment]
I don't think that it is even required honestly. You should be able to create a 5 minute event as well

**Comment by ankush-01** [comment]
> I think it's better if server provides this restriction rather than using some hard coded values here.

no its simple ...it can be implemented only in 5-10 lines of code..

**Comment by iamareebjamal** [comment]
Yeah, they should be able to do so unless server restricts it
