### ISSUE TITLE
Unexpected Behaviour of application

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1412]
**Describe the bug**
The app is not displaying any information, in-spite of logging in with the provided email credentials

**To Reproduce**
For me, the app ran the same whenever I ran it. Restarted the app many times, installed it various times, still the same.

**Expected behavior**
I guess it is supposed to act as it has been shown in the screenshots in the repo

**Logs**

**Screenshots**

![open event app](https://user-images.githubusercontent.com/31106411/50525110-7e18bf00-0aff-11e9-86d7-b89d3ae218b0.gif)

**Smartphone Info:**

|               | |
|---------------|-|
Device : Redmi Note 4X
Android Version : Nougat v7.0

**Additional context**

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: Would like to work on the issue if the errors or the cause is caught, as I am not able to catch the errors here currently

**Comment by Masquerade0097** [comment]
@tavishjain The app isn't showing any data because the data does not exist. You have to create it using API or through the app. Closing this.

**Comment by tavishjain** [comment]
@Masquerade0097 it isn't even creating an event from the app. When I press create on Step 3, it just shows a progress bar and nothing happens.

**Comment by iamareebjamal** [comment]
It's a known bug and being worked upon

**Comment by tavishjain** [comment]
@iamareebjamal so what part can I start working upon if I want to participate and contribute to this open source project ?

**Comment by iamareebjamal** [comment]
There are a lot of open issues. Pick any one which has no one working on it

**Comment by iamareebjamal** [comment]
@ShridharGoel Can you help?

**Comment by tavishjain** [comment]
@iamareebjamal I even explored the website right now, infact I was doing the same currently, and found that there is some issue in the backend server.
I received the confirmation mail, which doesn't verify my email and shows me a 404 error. 
I tried logging in and creating an event on the website, but even that gives me Unexpected errors.

**Comment by tavishjain** [comment]
It starts like this and then has some token at the last 

 http://open-event-frontend-dev.herokuapp.com/verify?token=

**Comment by iamareebjamal** [comment]
This is very old deployment. We have run out of heroku build hours. Change it to this:

https://fossasia.github.io/open-event-frontend/verify?token=

**Comment by tavishjain** [comment]
@iamareebjamal The app now works as in the repo screenshots. Thank you for your help :-)

I guess the issue is now completely resolved XD

Starting off with the Issues now

**Comment by ShridharGoel** [comment]
Nice to hear that 👍

**Comment by ShridharGoel** [comment]
Nice to know that 👍
