### ISSUE TITLE
add feture to enable or disable click sound 

### ISSUE THREAD

**Issue by GOVINDDIXIT** [fossasia/open-event-orga-app#1432]
**Describe the feature you'd like**
Add feture to enable or disable click sound on clicking items in navigation drawer layout

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by iamareebjamal** [comment]
?

**Comment by GOVINDDIXIT** [comment]
found this feature in that of eventbrite's app 😜

**Comment by Masquerade0097** [comment]
@GOVINDDIXIT We arn't providing sound output in app so an option to enable or disable it isn't relevant, i think.
