### ISSUE TITLE
Create Track even allows blank spaces in Name and Color fields making them empty

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-orga-app#1434]
**Describe the bug**
Even a single space can be entered in the Name and it will be accepted.

**To Reproduce**
1. Go to Tracks
2. Click on the FAB to create a new track.
3. Put just one or more spaces in the name field and try to submit.
4. It will be accepted.

**Expected behavior**
The spaces should be trimmed and error message should be displayed disallowing empty name field.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by iamareebjamal** [comment]
Related issue #1433. Solve in one PR

**Comment by ShridharGoel** [comment]
Fixed in #1435
