### ISSUE TITLE
Add option to delete events

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-orga-app#1452]
**Describe the feature you'd like**
There should be option to delete events. Long-clicking the event would select it and then the user would see an option to delete it.

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by iamareebjamal** [comment]
This was discussed and not approved as there are a lot of complexities in deleting events from backend. What to do with people who have bought tickets? How to handle refunds. That's why it wasn't approved

**Comment by ShridharGoel** [comment]
Yeah that's a valid concern. But I think there isn't any online payment system as of now. Is this being thought because online payment system will be implemented in the future?

**Comment by iamareebjamal** [comment]
Yes
