### ISSUE TITLE
Add detector frame on QR scan layout

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#146]
**UPDATED:**
Currently qr scan activity is just full screen activity. It gives no idea about what actually it is meant for.

Expected: 
- add detector frame on qr scan layout

I am working on it

**Comment by iamareebjamal** [comment]
Why the need of AppBar in QRScan activity. It'd be better if you add a bar code scanning message instead. A camera based activity is better is full transparent

**Comment by mejariamol** [comment]
Because currently it gives no idea about what actually it is for. yes obviously you would say to scan the code.
but from any user perspective it is just camera activity with no any clue of how to use it and for what to use it.
App bar and a squared scan frame would make that clear.

**Comment by iamareebjamal** [comment]
A Barcode detector frame and a message saying scanning QR code should be enough

**Comment by mejariamol** [comment]
taking this up.
