### ISSUE TITLE
Navigation drawer content overlaps with status bar

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-orga-app#1464]
**Describe the bug**
Navigation drawer content overlaps with status bar.

**Screenshots**
![screenshot_2019-01-25-20-54-27-389_com eventyay organizer](https://user-images.githubusercontent.com/35566748/51755985-ed290980-20e5-11e9-854c-e2b5b6f61704.png)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

- Other: @iamareebjamal Is this intentional? Should it be rectified or not?

**Comment by iamareebjamal** [comment]
It should be rectified

**Comment by ShridharGoel** [comment]
@iamareebjamal Can it be done without making the status bar opaque? I had tried many approaches but none of them worked, either this issue remained there or this issue got solved but the status bar became opaque.

**Comment by iamareebjamal** [comment]
Does it overlap when scrolled completely up?

**Comment by ShridharGoel** [comment]
![Nav drawer overlap](https://user-images.githubusercontent.com/35566748/59505830-31198100-8ec4-11e9-8e64-2d323ebcb24d.jpeg)
