### ISSUE TITLE
Make event container page starter page after log in

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#148]
Currently after log in event list page is a starter page but for event organizer, starter page should be event container page for a selected event. And from navigation drawer organizer can go to the event list page and select the required event. 

@niranjan94 @iamareebjamal what is your view ?

**Comment by iamareebjamal** [comment]
How would you choose which event to show as first? I think current UX is correct

**Comment by mejariamol** [comment]
That is for now since we are not maintaining local database yet. Once we do that we will be having current selected event. 
For now if no event is selected we can redirect to the event list page.

**Comment by iamareebjamal** [comment]
I guess that's too much complication for a basic feature. It's also not just a event page redirection problem, it is essentially a state saving problem. So let's tackle it in that manner only.

Let's say an organizer exits the application and returns back to the app and sees the last event he opened. I think he is most likely to get confused as he clearly pressed back, came to home screen and pressed back again to exit, so when the flow of app is to list->select->detail, why showing detail immediately?

**Comment by mejariamol** [comment]
>why showing detail immediately?

Because its **NOT** like at a time organizer will be handling more than one event. At a time there will be mostly one event and it will be tedious for organizer to always check the event from list on starting.
The focus of the app should be at event detail not on the list.

**Comment by iamareebjamal** [comment]
We can do this -> If there is one event. Show it directly. Sounds good?

**Comment by mejariamol** [comment]
You are not getting my point. Please see the eventbrite organizer app on the playstore.

**Comment by mejariamol** [comment]
@iamareebjamal did you check [eventbrite app](https://play.google.com/store/apps/details?id=com.eventbrite.organizer)? It is cleverly designed. I think we can take ideas from the design.

**Comment by iamareebjamal** [comment]
OK I'm getting it, but let the development flow be organic and dynamic. Let us create a persistence layer first and then discuss this?

**Comment by mejariamol** [comment]
@iamareebjamal please label it as `later`

**Comment by mejariamol** [comment]
As now we have set up data persistence layer, I think we can take up this.

Expected:
After log in, Main page should be event detail page with navigation drawer. User can navigate to the sections of event via navigation drawer. Also event list can be approached from navigation drawer to select any event. Like in eventbrite app - 

![screenshot_2017-06-19-22-34-01](https://user-images.githubusercontent.com/13533840/27296853-410fc994-5540-11e7-9dd4-d7750a39a2fb.png)

![screenshot_2017-06-19-22-34-08](https://user-images.githubusercontent.com/13533840/27296870-53e7492a-5540-11e7-94c1-e1127c9f74ac.png)

**Comment by iamareebjamal** [comment]
@mejariamol The Eventbrite dashboard contains total analysis for all events. If we plan to do this. The complete analysis should be present, and as you suggested correctly, this should be done in API. For now, we can group the events as past, live or upcoming. That'd be great.

If you are ready to implement complete analysis in the app itself, please go ahead

**Comment by mejariamol** [comment]
>The Eventbrite dashboard contains total analysis for all events. If we plan to do this. The complete analysis should be present,

I am talking about navigation in the app.
That is after log in --> All the event containing sections can be navigated via drawer including event list.

Currently the design is Event list -> event containing pages

**Comment by iamareebjamal** [comment]
When we'll have only 2 navigations in nav drawer, it won't make sense. And it will completely ruin the structure we have made so far

The Eventbrite structure is this way. Select an event, the whole app changes to that mode, and then you have the option to sell, check in and edit that event and many other options.

If you are talking about changing to this pattern (changing the context of application for a single event), then please go ahead, but the current navigation can't be just modified to the one like Eventbrite, it has to be changed completely then, including the Tablet layout. If you are on for the task, please continue :smile:

**Comment by mejariamol** [comment]
Can I take this up now. As we are moving towards more features now, I think we should have this navigation. what do you say? @iamareebjamal

**Comment by iamareebjamal** [comment]
Sure @mejariamol
