### ISSUE TITLE
Level and Type cannot be null in the Sponsors fragment

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1488]
**Describe the bug**
Whenever someone creates a new sponsor, and leaves the level and type fields empty, no errors are shown to the user, whereas any sponsor must have a level and type. 

**To Reproduce**
1. Go to Sponsors tab in the navigation drawer
2. Create a new sponser without fillling the fields level and type
3. See error 

**Expected behavior**
There must be an error raised is these cases

**Logs**
NA

**Screenshots**
NA

**Smartphone Info:**

|               | |
|---------------|-|
Device - Redmi Note  4X
Android Version - Nougat 7.1.1

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by Siddharth1698** [comment]
I will work on this

**Comment by ShridharGoel** [comment]
@iamareebjamal Is this valid?

**Comment by iamareebjamal** [comment]
Yes but low priority

**Comment by ShridharGoel** [comment]
Should I fix this? It's hardly 2 lines of code.

**Comment by iamareebjamal** [comment]
Go ahead
