### ISSUE TITLE
App crashes on sorting events list when list is empty

### ISSUE THREAD

**Issue by ravi-kishan** [fossasia/open-event-orga-app#1493]
**Describe the bug**

App crashes on sorting events list when list is empty
**To Reproduce**

1. Go to My Events
2. Click on Date or Name menu
3. App crashes if list is empty

**Expected behavior**

App should not crash

**Logs**

**Screenshots**

![whatsappvideo20190201at12](https://user-images.githubusercontent.com/31040431/52109242-cbb6a900-2622-11e9-98dd-12a0ac2c17cf.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [e.g. Moto G4 Plus] |
|Android Version| Nougat 7.0    |

**Additional context**

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
Not able to reproduce the issue.

![ezgif com-video-to-gif 31](https://user-images.githubusercontent.com/35566748/52110616-2f42d580-2627-11e9-9ece-d709b59b8f99.gif)

Are you using the latest commit from the development branch?
