### ISSUE TITLE
Fix Timber configuration

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#1496]
I added this stupid code 2 years ago in #302

https://github.com/fossasia/open-event-orga-app/blob/2e2cac8369b2a2565244763051fac39db92777c5/app/src/main/java/com/eventyay/organizer/OrgaApplication.java#L145-L146

This will recurse and throw StackOverflow in release build whenever any bug happens. Please solve this on an urgent basis

**Comment by ShridharGoel** [comment]
So we should just remove these lines, right? Since there is no use of calling the log method recursively.
