### ISSUE TITLE
App crashes on screen rotation in QR scanning activity

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#150]
In QR scan activity app crashes on screen rotation.

**Comment by iamareebjamal** [comment]
Yeah. Happens sometimes but doesn't always. Very weird behaviour too

Please set the QR Camera Activity non rotatable in AndroidManifest.xml

As is can already detect codes in all orientation, no need to destroy and recreate whole activity

**Comment by mejariamol** [comment]
@iamareebjamal milestone here too.
