### ISSUE TITLE
event can't be added to the app

### ISSUE THREAD

**Issue by sushmita0810** [fossasia/open-event-orga-app#1514]
**Describe the bug**
<not able to login with the given credentials >

**To Reproduce**
<Steps to reproduce the behavior:
1. Go to 'app'
2. Click on the app and enter the email id  orgadeveloper@gmail.com and password "fossasia"'

4. See error  error 401 unauthorized>

**Expected behavior**
< It should log in
 into the app>

**Logs**

**Screenshots**
<[whatsapp image 2019-02-19 at 1 30 49 pm](https://user-images.githubusercontent.com/35845477/52999265-51bc5780-344b-11e9-8fb2-741f4bb0d06a.jpeg) >

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi 5A|
|Android Version|Oreo    |

**Would you like to work on the issue?**

- [ ] Yes

**Comment by Masquerade0097** [comment]
@sushmita0810 Probably the credentials are changed. Are you able to signup to create a new account ?

**Comment by sushmita0810** [comment]
yes!! I am able to signup.
I would like to work more on this project. 
I was not able to add any event to the app, i.e it is not going to step 2.

**Comment by Masquerade0097** [comment]
@sushmita0810 To work on an issue, comment on existing issues or open a new issue (bug or feature).

>  I was not able to add any event to the app, i.e it is not going to step 2.

What're the logs?

**Comment by sushmita0810** [comment]
While adding the event , nothing happens when I click o nCREATE button  and a toast pops up saying Event Name cannot be empty but I had already written the name in first step1.


here is the screenshot:
step1:
![w1](https://user-images.githubusercontent.com/35845477/53196812-e76c0880-363e-11e9-962f-da1c674ed241.jpeg)
step2:
![w2](https://user-images.githubusercontent.com/35845477/53196815-eb982600-363e-11e9-8397-48aee1ec893b.jpeg)
step 3:
![w3](https://user-images.githubusercontent.com/35845477/53196898-1aae9780-363f-11e9-8933-e21117ddd6a3.jpeg)

**Comment by Masquerade0097** [comment]
@sushmita0810 This seems like a valid bug. You can start working on it to fix it. Also, while creating the issue paste the logs that are shown in Android Studio.

**Comment by iamareebjamal** [comment]
@sushmita0810 Please change the bug title and description accordingly

**Comment by sushmita0810** [comment]
ok

**Comment by ShridharGoel** [comment]
@sushmita0810 Are you working on this?

**Comment by tavishjain** [comment]
Has this issue been fixed or still under some discussion ?
