### ISSUE TITLE
Grouping events in the event list

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#152]
To be done after #156 

Currently all events are shown in an event list.

**Expected:** Events should be grouped under live, past and future on basis of event start-end time.

**Comment by iamareebjamal** [comment]
I think we should just show live events on top, with future and past events below

**Comment by mejariamol** [comment]
using tabs for live past future would be better.

**Comment by iamareebjamal** [comment]
The thing with tabs is that it again requires you to nest fragments and then each of them will have adapters, meaning 3 different views attaching 3 presenters and the ViewPager is really buggy and causes memory leaks. I don't think someone will have that many events to manage to require tabs. Furthermore, it really won't fit in the tablet mode. With tabs on 1/3rd screen and detail on remaining

**Comment by niranjan94** [comment]
Live (let this stay above future upto two days after the event end time) on top. Future below it. (maybe separated by a header). And past either below future or could be loaded on demand.
