### ISSUE TITLE
Application showing wrong credentials while logging in, in spite of typing the correct credentials

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1537]
**Describe the bug**
While logging in, the application is showing the error HTTP error 401 : Unauthorised, inspite of having a verified account and enetering the correct login credentials

**To Reproduce**
Go to the login screen and try logging in

**Expected behavior**
The app should move ahead to the dashboard

**Logs**
HTTP 401 UNAUTHORIZED

**Screenshots**
![whatsapp image 2019-03-08 at 1 22 08 am](https://user-images.githubusercontent.com/31106411/53985033-a85eac80-4140-11e9-9aee-37561adb920d.jpeg)

**Smartphone Info:**
Device - Redmi Note 4
Android - Android Nougat

**Additional context**
NA

**Would you like to work on the issue?**

- [ ] Yes
- [ ] No
- Other: I don't know what the issue is. Seems an error in the server

**Comment by ShridharGoel** [comment]
Not able to reproduce this. Are you still facing the problem?
