### ISSUE TITLE
Unexpected behaviour of FAB button in Attendees section

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1538]
**Describe the bug**
When we open the Attendees section from the navigation drawer, the FAB button is not visible until we touch the screen once

**To Reproduce**
Open the Attendees section from Navigation drawer, and leave it still. You will not see any FAB button. Now click anywhere on the screen and you will be able to see the FAB button now

**Expected behavior**
The FAB should be vissible from the starting

**Logs**
NA

**Screenshots**
![gif](https://user-images.githubusercontent.com/31106411/53986524-6afc1e00-4144-11e9-8f22-914dba22450d.gif)

**Smartphone Info:**

Device - Redmi Note 4
Android Version - Android 7

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
Actually, as far as I know, the FAB is meant to be visible only when the attendee list is non-empty. This was a bug that the FAB used to become visible on trying to scroll but it was fixed in #1466.

**Comment by ShridharGoel** [comment]
@iamareebjamal Please close this.
