### ISSUE TITLE
Update the Gradle version

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1547]
**Describe the chore**
The current version of gradle contains some deprecated code, due to which the build in the PR is failing
For reference, my PR #1539 is failing due to the build error 

*registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)*

and it's solution has been mentioned here, which directly aims to update the gradle version :
https://github.com/google/play-services-plugins/issues/23#issuecomment-448919947
https://github.com/google/play-services-plugins/pull/35

**Would you like to work on the issue?**

- [ ] Yes
- [X] No
- Other:

**Comment by tavishjain** [comment]
@iamareebjamal please have a look

**Comment by ShridharGoel** [comment]
Build of #1539 is failing due to failing tests.

**Comment by ShridharGoel** [comment]
`registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)` is a warning, not an error.

**Comment by iamareebjamal** [comment]
Update the gradle version. Go ahead

**Comment by ShridharGoel** [comment]
I think @tavishjain is not working on this because he has selected the 'No' option. So, I'll be sending a PR.

**Comment by tavishjain** [comment]
@ShridharGoel sure. I even tried to upgrade the gradle version, but was getting many build errors. I'll surely have look at you PR. Just refer it to this issue

**Comment by tavishjain** [comment]
@ShridharGoel is this not done yet ?

**Comment by ShridharGoel** [comment]
Not yet, because of this travis build error:

```
Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
```

**Comment by tavishjain** [comment]
Even I was getting the same error

**Comment by iamareebjamal** [comment]
See open event android Travis configuration
