### ISSUE TITLE
Cannot come back in Settings after clicking on Sales Data Display or Legal

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-orga-app#1549]
**Describe the bug**
When user click on Sales Data Display or Legal in Device Settings, they cannot come back to the main devices setting fragment. If they want to, they have to open the drawer, click on another section and click back onf Device Settings Section

**Screenshots**
<img src="https://i.ibb.co/tqwWC9v/54515420-419168485559152-5529973528373231616-n.png" width="200">              <img src="https://i.ibb.co/Z2HL9T6/54372178-422303395209045-1998578214179438592-n.png" width="200">              <img src="https://i.ibb.co/bWPPcdD/53900744-409902039570040-2700865685596143616-n.png" width="200">

**Would you like to work on the issue?**
Yes

**Comment by ShridharGoel** [comment]
But pressing back in Sales Data Display is taking to Device Settings. Have you tried that?

**Comment by anhanh11001** [comment]
@ShridharGoel I actually got out of the app by pressing back button

**Comment by anhanh11001** [comment]
I don't know if you experience the same issue, if not I will try to figure it out myself why it is not working right with me

**Comment by ShridharGoel** [comment]
It's working fine for me

**Comment by anhanh11001** [comment]
@ShridharGoel can I ask what devices you're using, just in case?

**Comment by ShridharGoel** [comment]
Redmi 4 running Android 7.1.2 (API 25)

**Comment by ShridharGoel** [comment]
Can you add a GIF showing the issue?

**Comment by anhanh11001** [comment]
@ShridharGoel I'm about to have a test at my university so I'll send a GIF in 4,5 hours

**Comment by anhanh11001** [comment]
@ShridharGoel here is the GIF
<img src="https://i.ibb.co/NTkBXQV/ezgif-2-68eae0a131f7.gif" width="300"/>

**Comment by ShridharGoel** [comment]
Okay, this seems strange. Do you have any idea why this might be happening?

**Comment by ShridharGoel** [comment]
@anhanh11001 Your device and android version?

**Comment by anhanh11001** [comment]
For now I don't because I haven't taken a close look at the code today, I'll try to figure it out tomorrow. If you have any ideas, please give me advices to fix this. My device is Nokia 7 Plus, API28, Android Pie

**Comment by ShridharGoel** [comment]
@anhanh11001 Were you able to figure this out?
