### ISSUE TITLE
Sponsers list is not refreshed automatically when we delete sponsers

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1552]
**Describe the bug**
Sponsers list is not refreshed automatically when we delete sponsers

**To Reproduce**

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31106411/54114198-e47b6100-440f-11e9-8b3f-01153e04c7a9.gif)

**Smartphone Info:**

Redmi Note 4
Android Nougat

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
@tavishjain Are you working on this?

**Comment by tavishjain** [comment]
yes @ShridharGoel . I got busy in making the proposal so was not able to focus much on the issues

**Comment by ShridharGoel** [comment]
@tavishjain Updates?
