### ISSUE TITLE
Add persistence layer in the application

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#156]
We need to add a data persistence library in the application.

We should have a discussion over which one to add

I recommend DBFlow, it's quite fast, easy to work with and plays nice with RxJava

For Event

**Comment by mejariamol** [comment]
Yeah. **DBFlow** seems good. And it is well documented.

**Comment by mejariamol** [comment]
@iamareebjamal What's the progress on this? I think this should be done part-wise in sub issues. Please create sub issues for the same if possible.

**Comment by iamareebjamal** [comment]
The progress can be seen here https://github.com/iamareebjamal/open-event-orga-app/tree/dbflow

Was a little busy between reviewing samples and fixing some crucial bugs in Open Event Android 

The problem I was facing was in creating one to many relation. I know the solution but the approach is giving issues. I don't want app to be refactored again and again, so focusing on best principle here

About sub-issues, yeah that's the point, but first, at least the event should be persisted. Then, for next parts, I'll create sub-issues
