### ISSUE TITLE
app crashes while adding images to a new event.

### ISSUE THREAD

**Issue by kk63852** [fossasia/open-event-orga-app#1564]
**Describe the bug**

while creating a event the app crashes on step 3 when an image is added .
**To Reproduce**

1. Go to new event or + icon.
2. fill in the details.
3. add a image when asked in step 3 . app crashes.

**Expected behavior**

app should not crash. 
**Logs**

![Screenshot (16)](https://user-images.githubusercontent.com/31561661/54516788-f7e57980-4985-11e9-8328-0ca24dae480d.png)

**Screenshots**

![device-2019-03-18-135720](https://user-images.githubusercontent.com/31561661/54516832-1186c100-4986-11e9-87cc-e5462d006526.png)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Samsung J7 next|
|Android Version|Oreo 8.1|

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by tavishjain** [comment]
@kk63852 works fine for me. 
Also, @kk63852 from the next time try adding a video of the issue you are trying to depict
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31106411/54585554-61c25980-4a40-11e9-833b-adcec398d52a.gif)

**Comment by kk63852** [comment]
@tavishjain thanks for checking on your device. may be its not working on my device only. i'll have a few more checks before i close this issue.
