### ISSUE TITLE
Create event activity doesn't go past STEP 1

### ISSUE THREAD

**Issue by tavishjain** [fossasia/open-event-orga-app#1568]
**Describe the bug**
The Create event activity doesn't go ahead of STEP 1 when the event start and event end time are same

**To Reproduce**
Create a new event having the same start and end time. When you press on the next button, nothing will happen

**Expected behavior**
A toast message or a snackbar must be shown

**Logs**

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/31106411/54604756-9698d580-4a6d-11e9-8621-c15102262b5c.gif)

**Smartphone Info:**

Device - Redmi Note 4
Android version - Android Nougat

**Additional context**

**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by ShridharGoel** [comment]
Will be fixed in #1567

**Comment by ShridharGoel** [comment]
@tavishjain Please check if you are still experiencing the issue.

**Comment by tavishjain** [comment]
@ShridharGoel this issue has been fixed in #1569. The acitvity was not proceeding ahead because the event start and end time were the same, and no error was being displayed to the user. 
So that caused this issue
