### ISSUE TITLE
Redesign event detail layout

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#157]
Current event detail layout can be modified into better one.

I am working on it.

**Proposed UI:**

Include both progressbar into a card view. Approximate view will be 
![screenshot from 2017-06-07 15-16-34](https://user-images.githubusercontent.com/13533840/26872723-2daf935c-4b95-11e7-9c36-85100a94616f.png)

@iamareebjamal please add `ui` label.

**Comment by mejariamol** [comment]
@iamareebjamal Any suggestions?
![screenshot_2017-06-08-02-19-19](https://user-images.githubusercontent.com/13533840/26900915-8268c470-4bf1-11e7-8122-b2b08361518a.png)

**Comment by iamareebjamal** [comment]
Nice design. I guess showing total tickets and attendees will be a good idea. Probably in small font on lower right side

**Comment by iamareebjamal** [comment]
About empty space, we have a lot of info to be shown in later stages. I think this amount of change is enough for this issue.
