### ISSUE TITLE
Get Started Button Should Be Disabled When There's No Input

### ISSUE THREAD

**Issue by iadeelzafar** [fossasia/open-event-orga-app#1571]
**Describe the bug**
Get Started Button Should Be Disabled When There's No Input

**To Reproduce**

1. Go to the login screen.
2. Click the get started button without input.

**Expected behavior**
Get Started Button Should Be Disabled When There's No Input. We can enable it after a specific amount of input characters.
When it is disabled, we can turn its color to gray.

**Screenshots**

<img src="https://user-images.githubusercontent.com/36811908/54707089-228c2980-4b62-11e9-89e0-737a8a0c5213.gif" height="700" width="394">

**Smartphone Info:**
Galaxy Nexus API 24

**Would you like to work on the issue?**

- [ ] Yes
- [x] No

**Comment by iadeelzafar** [comment]
Same For The Password On Login Too.
<img src="https://user-images.githubusercontent.com/36811908/54707766-a72b7780-4b63-11e9-9071-3d790f541ba9.gif" height="700" width="394">

**Comment by iamareebjamal** [comment]
Don't agree

**Comment by iamareebjamal** [comment]
It's showing the error on Clicking. Why do we need to disable it?

**Comment by iadeelzafar** [comment]
I noticed this enhancement a while ago on some apps. Thanks for reviewing this thread. :)
