### ISSUE TITLE
Copyright Not Updating Even After Refresh

### ISSUE THREAD

**Issue by iadeelzafar** [fossasia/open-event-orga-app#1573]
**Describe the bug**
Adding the copyright information of an event doesn't gets updated even after we refresh it.

**To Reproduce**

1. Go to an event's about
2. Add the copyright information, save it.
3. Go back, refresh.
4. It won't update.

**Expected behavior**
It should update after the refresh.

**Screenshots**
<img src="https://user-images.githubusercontent.com/36811908/54708381-18b7f580-4b65-11e9-94e8-54b0ef0b1f25.gif" height="700" width="394">

**Smartphone Info:**
Galaxy Nexus API 24

**Would you like to work on the issue?**
- [ ] Yes
- [x] No
- Other:

**Comment by ShridharGoel** [comment]
Logs show `HTTP 500 Internal Server Error`

**Comment by iamareebjamal** [comment]
Raise issue on the server

**Comment by kush-mish** [comment]
https://github.com/fossasia/open-event-server/issues/5700#issue-423587290

**Comment by ShridharGoel** [comment]
This is fixed and can be closed.
