### ISSUE TITLE
Option to delete attendees

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-orga-app#1575]
**Describe the feature you'd like**
Show option to delete a particular attendee on long click.

This is already implemented in the server side:
https://api.eventyay.com/#attendees-attendee-details-delete

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

**Comment by ShridharGoel** [comment]
@iamareebjamal Your opinion?

**Comment by iamareebjamal** [comment]
The delete attendee has been previously discussed. Read the closed issue about it

**Comment by ShridharGoel** [comment]
Couldn't find any closed issue related to this

**Comment by iamareebjamal** [comment]
Same concern as #1452 #602

**Comment by ShridharGoel** [comment]
Okay
