### ISSUE TITLE
Shift qr scan button to FAB

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#167]
Currently QR scan button is on attendees page at bottom which takes space. It should be in the app bar of `EventContainerActivity` as it is event specific action.

I am working on it.

**Comment by iamareebjamal** [comment]
It'd be better if you create a FAB for it

**Comment by iamareebjamal** [comment]
@mejariamol Take QR scan icon from here https://materialdesignicons.com/

**Comment by iamareebjamal** [comment]
@mejariamol Shouldn't be taking this long. Please ensure it gets done by the end of day. It's quite trivial

**Comment by mejariamol** [comment]
@iamareebjamal Actually I am afk now. Will be working tonight. :)

**Comment by iamareebjamal** [comment]
OK :+1:
