### ISSUE TITLE
App not Installed 

### ISSUE THREAD

**Issue by obitodarky** [fossasia/open-event-orga-app#1707]
**Describe the chore**

I tried to download the apk as listed [here](https://github.com/fossasia/open-event-orga-app/blob/apk/eventyay-organizer-dev-app-playStore-release-unsigned.apk)
The download was successful but I was unable to install the app. It showed me  `App Not Installed` message.
**Device Specifications**

- Phone: Zenfone Max Pro M1
- Android: 9 (API 28)

**Would you like to work on the issue?**

No

**Comment by ShridharGoel** [comment]
The one you are trying to install is an unsigned APK. Please download the app from Play Store: https://play.google.com/store/apps/details?id=com.eventyay.organizer

**Comment by obitodarky** [comment]
This worked for me. Thank you
