### ISSUE TITLE
Show intermediate layout when no event/attendee present

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#171]
An intermediate layout should be shown when there are no event(s) or attendee(s), using data binding

![test](https://user-images.githubusercontent.com/3874064/27297366-2fb1463a-5542-11e7-8b63-f9e5efcbaad0.png)

**Comment by mariobehling** [comment]
A lot of people are visual people who need mockups or screenshots. We can make it easy for us and use screenshots of eventbrite showing similar features. We already talked about this, but I am not seeing anything in that direction.

**Comment by iamareebjamal** [comment]
@mariobehling I was busy in the implementation of new API format models as it was a high priority issue and ironing out some bugs and making the app usage stable as we just added the database support previous week and there are crashes throughout the app and we needed to handle those first. Secondly, even though example screenshots are not added from Eventbrite app, the issues for completing such UX are created already ( which are possible with the current features of the app, which include checking in and checking out of the attendees )

As for this issue, this is just about the placeholder item to be shown while the event or attendees load, or if there are no events or attendees
