### ISSUE TITLE
Show tracks and sessions of a particular Event

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#172]
Add option to view Tracks in the EventContainerFragment along with a Detail View showing session details. 

Only overview need to be shown. The detail of the track should be shown using a nested fragment so that we can easily convert it into Master/Detail layout in future

**Comment by mejariamol** [comment]
No need to show tracks separately. Sessions shall be shown with color of
the tracks. User will be able to reschedule any session.
Tracks are not required to show explicitly. Tracks can be added in filter
options.

**Comment by mejariamol** [comment]
@iamareebjamal I am thinking about the design. Will add my design proposal
by tomorrow. You may add your proposal by then.

**Comment by iamareebjamal** [comment]
@mejariamol If there are many sessions, then it will become hectic. Probably add StickyListHeader and a FastScroller for track headings?

**Comment by mejariamol** [comment]
@iamareebjamal yeah. but showing sessions on timeline is preferred instead of showing them track wise.

**Comment by iamareebjamal** [comment]
The problem is when there will be numerous sessions

**Comment by mejariamol** [comment]
There can be many sessions in a track too. Why is that a problem?

### Proposed design - 
a page showing sessions of a day will contain - 
- a vertical timeline starting from start time of an earliest session to a last session of a day
- buttons below app bar to switch days and microlocations
- sessions will be shown accordingly besides timeline in scroll view with title and track specific color
- on clicking on floating window will appear in which session can be rescheduled.

**Comment by iamareebjamal** [comment]
Well, in large Events, like Fossasia 2016, there can be several sessions, an organizer may want to view it according to the tracks. 

Well, let's go with your idea first and we'll add options to view by tracks later

**Comment by niranjan94** [comment]
@iamareebjamal @mejariamol we need 
- Grouped microlocations (meaning ... list of microlocations -> click -> sessions)
- Grouped by tracks (meaning ... list of tracks -> click -> sessions)
- Ungrouped list of sessions (not a priority since if there are a lot of session. (which mostly would be the case) this would do more good than bad.)


The organizer app should be looked at from an event organizer's perspective.

**Comment by mariobehling** [comment]
This is currently out of scope of the app.
