### ISSUE TITLE
Implement Developer Mode by default and hide "Tickets" and "Edit Events" if Dev Mode is switched off

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#1739]
In the device settings add a mode "Developer Mode". 
1. This mode should be deactivated by default. 
2. Then in the event menus hide the following. Only show this if users switch on "Developer Mode":
   * "Tickets"
   * "Edit Event"
   * "+" icon to create new events.
   * "Orders" 
-> Only show these features in "Developer Mode!
3. When people activate developer mode, please show a pop up "You are activating Developer Mode. This mode will give you access to unreleased app features. These features are unstable and could potentially result in unwanted changes in your event or data loss. Use with care! Do you really want to activate developer mode? [Yes, I am taking my Chances] [No, I want to stay safe]
4. Implement the "Yes" button in red.

**Comment by iamareebjamal** [comment]
Also, show previously hidden items in dev mode
