### ISSUE TITLE
Improve Sidebar menu, My Events screen, and Event Dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#1745]
Please improve the following:

* Move "My Events" to menu point 1 in sidebar menu
* On "My Events" screen show year of event and include start and end date of event
* Rename "Dashboard" to "Event Dashboard"
* On Event Dashboard Show "Order Statistic" and "Event Statistics" by default and take out the button to switch off these statistics
* Above Section "Gross Sales" add a box with buttons of the following items:
   * Check In
   * Orders
   * Tickets
   * Edit Event
   * Event Settings
* Only show Orders, Tickets, Edit Event in Developer Mode

**Comment by ShridharGoel** [comment]
Done.
