### ISSUE TITLE
Add a sample app after each commit

### ISSUE THREAD

**Issue by the-dagger** [fossasia/open-event-orga-app#18]
@niranjan94 @mariobehling I think that this is pretty nifty,  as it will make the testing of the app easier by simply downloading the app from sample folder instead of going through the hassle of building one for testing. 
I would like to work on this.

**Comment by niranjan94** [comment]
Okay... So, the Travis script already builds the apk. You could it make it such that it uploads the apk after each push onto the gh-pages branch.

**Comment by the-dagger** [comment]
Shouldn't it be pushed on master? 
Similar to opev-android. 
I can make a folder named sample-apk and the built apk will be pushed in it.

**Comment by niranjan94** [comment]
@the-dagger no. let's not put built binaries on the master. We'll keep it in a separate repo.

**Comment by the-dagger** [comment]
Ok, i'' make a gh-pages branch and push the apk there.

**Comment by mariobehling** [comment]
@the-dagger sounds great. Any PR?

**Comment by the-dagger** [comment]
@mariobehling I'll send a PR in the next hour.
Was a bit busy with some other stuff.
