### ISSUE TITLE
Event tickets are not loaded once saved in database

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#181]
The subsequent call to network is not made if the event is saved in the database, to fetch the tickets making the analytics show wrong results

**Comment by mejariamol** [comment]
@iamareebjamal What I am seeing is - now total tickets shows always 0. 
when events are saved in database for first time, were total tickets 0?

**Comment by iamareebjamal** [comment]
The first time event is loaded, it is loaded from /users/me/events which does not contain ticket info

I implemented the correct way to access the correct event but in refactoring, it got lost. Sending a PR

**Comment by mejariamol** [comment]
fixed via #186 
can be closed. @iamareebjamal
