### ISSUE TITLE
Show attendee information at the time of check in

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#183]
Show attendee information in a bottom sheet, along with the ticket type and info about date purchased, receipt number etc.

Along with this, show the attendee bottom sheet in the Scan Activity so that organizer does not have to go to attendee page, again and again, to confirm launch the Scan Activity

![test](https://user-images.githubusercontent.com/3874064/27297075-074780d4-5541-11e7-9d85-85f661781f74.png)

**Comment by mejariamol** [comment]
I am working on it.

**Comment by mejariamol** [comment]
to be done after #185

**Comment by iamareebjamal** [comment]
@mejariamol Please take up the issue now

**Comment by mejariamol** [comment]
We will be using bottom sheet view right?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
It'll be a self-contained entity with its own presenter

**Comment by iamareebjamal** [comment]
@mejariamol Are you working on this or can I take this up?

**Comment by mejariamol** [comment]
Please proceed. I am working on attendees filter.
