### ISSUE TITLE
Add attendees to persistence layer

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#187]
Add attendees in database

**Comment by iamareebjamal** [comment]
@niranjan94 Need your help. Can an attendee be linked to several events? Having difficulty defining the relationship among attendee and event. As all attendees will be stored in one table relationally, we'll also need to store the event id to associate them with a particular event. Is this approach correct?

**Comment by niranjan94** [comment]
@iamareebjamal each attendee will be linked to **only one** event. Yep. You can store the event ID along with each attendee to associate them to an event.
