### ISSUE TITLE
Implement attendees search

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#190]
To be done after #193 
Currently no attendees search present.
Expected:
- search view in app bar on attendees page which can filter attendees by name or email

I am working on it.

**Comment by niranjan94** [comment]
Should be a fuzzy match search.

**Comment by iamareebjamal** [comment]
Please do in memory search using DiffUtils for recyclerview and implement corresponding methods in the MVP contracts and tests

**Comment by mejariamol** [comment]
[SortedList](https://developer.android.com/reference/android/support/v7/util/SortedList.html) is advantageous over DiffUtils as it does sorting additionally.

**Comment by niranjan94** [comment]
@mejariamol @iamareebjamal also keep in mind that we still need the first letter grouping even after search.

**Comment by mejariamol** [comment]
@niranjan94 Yeah. Its not implemented yet on attendees list. Will do so first.

**Comment by mejariamol** [comment]
@niranjan94 What is preferred?
- first letter grouping as it was in ionic version. that is with sticky list headers with initials  **OR**
- side alphabet index which can be scrolled like in phone contacts list.
