### ISSUE TITLE
Separate initial data load part from ui interation in presenters

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#196]
Currently in presenters of event containing fragments, initial data loading part is in conjunction with a part interacting with the view. Hence data loading cannot be initialized in `onCreate` fragment call. Hence data load is called every time when switching between fragments.

If we manage to separate initial data loading as separate functions and maintain a flag to check progress and show result in view accordingly, it can be solved.

@iamareebjamal what do you think?

**Comment by iamareebjamal** [comment]
True, but let's focus on #161 first. I have been creating mock models and API. No one has reported anything related to it. It is a core feature. Please let's focus on it. Follow up in https://github.com/fossasia/open-event-android/issues/1680

**Comment by mejariamol** [comment]
saving and providing presenters will be done via this issue right? @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
It will be done by loaders

**Comment by mejariamol** [comment]
taking this up

**Comment by iamareebjamal** [comment]
Try to handle it in BaseFragment so you don't have to do it everywhere
