### ISSUE TITLE
App crash if attendees are saved before complete event

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#205]
As attendee rely on the ticket to be foreign key, Foreign Key Constraint fails when attendees are saved before tickets( included in complete event )

We have to design a synchronisation mechanism to ensure this doesn't happen

**Comment by mejariamol** [comment]
should be done with #196

**Comment by iamareebjamal** [comment]
They are both entirely different issues

**Comment by mejariamol** [comment]
with #196 we will be separating initial data loading calls in presenter from actual ui interaction. Hence synchronizations in calls (calls saving data in database) also can be handled there such that these effects can be avoided.

**Comment by iamareebjamal** [comment]
IMO there is no need to merge these 2 issues as they both are big enough on their own and completely unrelated with each other. Meaning that there will be no code sharing in between these two

**Comment by iamareebjamal** [comment]
@mejariamol The lease complex and most natural way would be to download ticket info when we are downloading the user events. I mean, to remove the possibility of incomplete events being saved in the database. What say?

**Comment by mejariamol** [comment]
> to download ticket info when we are downloading the user events

if we could do this, then why not. :+1:
