### ISSUE TITLE
Add option to change server base URL in login

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#206]
Currently app uses `http://open-event-dev.herokuapp.com/api/v1/` as api end. 

Expected: 
default base URL will be `https://eventyay.com/api/v1/`
and an option will be given to add new URL

I am working on it.

**Comment by iamareebjamal** [comment]
Use dagger to make base URL as the dependency. It'll be a better solution

**Comment by mejariamol** [comment]
@iamareebjamal please add milestone to this issue. Also please check for without milestone closed issues.
