### ISSUE TITLE
Autocomplete email text input

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/open-event-orga-app#209]
Actual Behaviour

The user has to each and every time enter the whole email address to login.

Expected Behaviour

The user would be able to select his email from autocomplete dropdown if he has successfully logged in earlier in the app.

Would you like to work on the issue?

Yes, I would like to solve this issue.

**Comment by iamareebjamal** [comment]
@rohanagarwal94 Please only store email with user consent. Meaning that please provide a selection to ask whether to store the email in the form of checkbox.

**Comment by rohanagarwal94** [comment]
@iamareebjamal what I will be doing is store the email on a successful login in the shared preference and when the user types the email again in the edittext, he/she can select it from the autocomplete dropdown. I dont thing that is something which will trigger a security threat or something which requires user consent as such.

**Comment by iamareebjamal** [comment]
The thing is that if the user logs out, someone else may come and see his login email. Though not very serious, it is one part of the credentials

**Comment by mejariamol** [comment]
@iamareebjamal As this is phone app i don't find it credential leak.

**Comment by iamareebjamal** [comment]
Ok, then go ahead
