### ISSUE TITLE
Clear all the database on new user login

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#210]
Currently we are keeping database excluding `User` and `UserDetail`tables on log out. Which is problem for new login as it still shows old data for new user.

Correct approach should be keeping all the database on logout. On login if data exist check for the user id. If user id of the new user doesn't matches with existing id then clear all the database otherwise keep the same.

@iamareebjamal you may want to take up this.

**Comment by iamareebjamal** [comment]
Correct. Thanks for pointing out. Taking it up

**Comment by iamareebjamal** [comment]
Changing to this. The User and USerDetail are not cleared when the user is logged out. But when someone logs in. It is checked if the login username is different from the already saved one. And if so, then the database is cleared

**Comment by mejariamol** [comment]
>login username is different from the already saved one

Are we storing email ? I think checking user id should be preferred.

**Comment by iamareebjamal** [comment]
We won't get user id from the login response

**Comment by iamareebjamal** [comment]
The email is stored with the user object and is available when the user logs in. Secondly, we won't get user ID till we fetch organizer and till then, it might be too late to delete the database
