### ISSUE TITLE
Handle screen rotation

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#218]
Currently on screen rotation event detail fragment looses its data.

Expected: data must be retained on screen rotation

**The problem is to retain more than one fragment on screen rotation.**
- `setRetainInstance(true)`
is one option to retain fragment instance on screen rotation that is on `onDetach()` call.
But using this only one object can be retained in the activity. We have 3 fragments currently. 
    - **EventContainerFragment** (direct fragment to the host activity - EventDetailActivity)
    - **AttendeesFragment** (child fragment of EventContainerFragment)
    - **EventDetailFragment** (child fragment of EventContainerFragment)

So we have to retain all these child fragments on screen rotation to avoid repetitive loading from the disk.

**Comment by iamareebjamal** [comment]
Data is loaded now. But we need to retain fragment on rotation

**Comment by iamareebjamal** [comment]
This is the same as tackling #196 

Closing
