### ISSUE TITLE
Show attendee check in dialog in QR scan activity

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#230]
To be done after #224 is merged

Currently QR scan activity is started for results from attendees fragment and on successful scan attendee check in dialog is shown in attendees fragment.

Expected: Attendee check in dialog (from #224) shall be shown in QR scan activity itself.

**Comment by mejariamol** [comment]
taking this up.

**Comment by mejariamol** [comment]
@iamareebjamal 
Current implementation of bar code detection is more complex. Also missing the setup with activity's life cycles.
while adding this feat, I am unable to stop and start camera source to halt detection when attendee check in dialogue is shown. You may suggest the approach for doing same. Or may just break the things to simpler. :smile:

**Comment by iamareebjamal** [comment]
Very true. The scan activity is designed to be use and throw. I have been thinking of a way to stop and restart camera source. I'll let you know after a bit of research

**Comment by iamareebjamal** [comment]
You can dispose the subject to stop receiving callbacks and resubscribe when the dialog is dismissed
