### ISSUE TITLE
Toggling check in status doesn't reflect in the attendees list

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#234]
On Attendees page, toggling check in status doesn't reflect in the attendees list.

### How to produce:
1. Open attendees list section.
2. Toggle an attendee's check in clicking on any of them which will change check in button of that attendee correctly.
3. Try toggling more check ins which will not reflect in the list

**Comment by iamareebjamal** [comment]
Works correctly for me. Can you add a screencast please

**Comment by mejariamol** [comment]
@iamareebjamal I re-install the App and its working for me too. :thinking: closing it.

**Comment by iamareebjamal** [comment]
You might be on the attendee filter one
