### ISSUE TITLE
Scan button behaviour

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#238]
- Hide Scan button on scroll
- Only show scan button if there are attendees

**Comment by mejariamol** [comment]
I am working on it.

**Comment by mejariamol** [comment]
@iamareebjamal couldn't get the need of hiding scan button on list scroll. I think it is of no use in UX just hiding it on scroll and showing on scroll has stopped. What do you think?

**Comment by mejariamol** [comment]
Can we go for this?
Hiding it when scrolled down and showing it on scroll up.

**Comment by iamareebjamal** [comment]
Yes, that's what I meant
