### ISSUE TITLE
local data is not cleared on different user login

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#252]
Currently we are matching username (email id) of new user to decide if local data is to be removed.

But as we are using (and shall be using) separate server for _dev_ branch where email can be same hence previous data stored is not removed in that case.

Expected: username and userid both shall be checked to decide previous data removal.

@iamareebjamal what is your opinion?

**Comment by iamareebjamal** [comment]
Yeah, it should be, but then it'll involve database in the operation, and we can't clear the database till the user has successfully logged in and that might be too late as everything is happening asynchronously, it may load the data before db is cleared. So, I'm thinking of a better approach. Please you suggest as well

**Comment by mejariamol** [comment]
>successfully logged in and that might be too late as everything is happening asynchronously, it may load the data before db is cleared

Actually all the data loading starts when we initiate other activity from LoginActivity. On successful login we just get a token. Which can be used in LoginActivity itself to get user and check whether is it same and accordingly clear the database before starting any data loading activity.

I am saying LoginModel :: login itself should download user and check.

**Comment by iamareebjamal** [comment]
OK, you can play with it and see if it works

**Comment by mejariamol** [comment]
Okay.
