### ISSUE TITLE
Show confirm dialogue for logout

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#253]
To be done after #246 is merged

Currently no confirm dialogue for logout

Expected: show confirm dialogue for logout.

**Comment by iamareebjamal** [comment]
We can add that now. Simply logging out is poor UX. Taking this up

**Comment by mejariamol** [comment]
@iamareebjamal But by #246 logout will be shifted from EventListActivity to MainActivity

**Comment by iamareebjamal** [comment]
As long as they are implementing contract, I don't think refactoring will be a problem
