### ISSUE TITLE
Old data is not removed on swipe refresh success

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#255]
On swipe refresh new data is saved.(Updated)

**Expected:** On swipe refresh success complete concerned table must be cleared before saving new data. So that this will ensure that data deleted on the server never stays locally.

**Comment by iamareebjamal** [comment]
Which deleted data was not cleared. The DB uses update on conflict

**Comment by mejariamol** [comment]
For example suppose an event is deleted on server. So swipe refresh can't remove it. As it just updates the data got from server. The deleted data will always stay in local database as it is.
