### ISSUE TITLE
Add Type, Relation, Id annotations to models

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#257]
Part of #161

- Add JSONAPI annotations to model

**Comment by mejariamol** [comment]
@iamareebjamal I am not clear about this. by this we will be shifting completely to nextgen api right? which means this issue will include changing retrofit builder and all other network requests handling stuff?

**Comment by iamareebjamal** [comment]
Not much would be changing, just the ObjectMapper object, and this is just about adding annotations, which will just work fine with older APIs as well. When we'll shift to nextgen, all models will have to change too. This is just about starting the process by adding annotations
