### ISSUE TITLE
Create error handler class to parse errors

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#266]
- Create error handler class to parse errors and provide user-friendly messages instead
- Change toasts to appropriate Snackbars and Dialogs in UI according to the error shown

**Comment by mejariamol** [comment]
@iamareebjamal shall we use this for error handling https://github.com/Workable/java-error-handler

**Comment by iamareebjamal** [comment]
Sure

**Comment by mejariamol** [comment]
taking this up.

**Comment by mejariamol** [comment]
Yeah. Taking this up. @iamareebjamal
