### ISSUE TITLE
Simplify MainActivity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#268]
Current implementation is too complex and data flow is not unidirectional

- Make data flow simpler throughout components
- Remove complexity from views, especially MainActivity

**Comment by mejariamol** [comment]
@iamareebjamal
Please be more detailed.

**Comment by iamareebjamal** [comment]
It's simply that the current way the selected event is propagated through components and the use of an interface to detect when the event is loaded is pretty complex and unneeded as discussed in the PR for navigation view. This adds window for large amount of bugs we can't test for
