### ISSUE TITLE
Attendees page doesn't load

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#269]
To be done after #270 
Attendees page doesn't load. Progress bar keeps on running.

Taking this up.

**Comment by mejariamol** [comment]
@iamareebjamal swiperefresh not working on attendees page. will you please take a look.

**Comment by iamareebjamal** [comment]
On it

**Comment by iamareebjamal** [comment]
It's working fine on my side

**Comment by mejariamol** [comment]
which server you are using?

**Comment by iamareebjamal** [comment]
open-event-dev

**Comment by mejariamol** [comment]
Will be fixed in #273
