### ISSUE TITLE
Data loading takes longer on Events and Attendees page

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#274]
sub issue of #273 

Currently the pages fails to load data sometimes and keep on showing progress bar for long. 
The reason behind misbehaviour of Computation scheduler in data loading observables. Removing it solves issue for now.
**Future action:** implement sorting in fastAdapter itself. Creating issue for the same. #275  But for now just removing computation scheduler.

**Comment by iamareebjamal** [comment]
This was fixed by #277
