### ISSUE TITLE
Implement sorting in fastAdapter

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#275]
Currently for events and attendees page, items are sorted in the fetch request itself while loading from disk or network.

**Expected:** Implement fastAdapter sorting which will enable run time sorting (ASCEND/DESCEND). Also this will include implementing fastAdapter for events.

@iamareebjamal please label it `later`

**Comment by mejariamol** [comment]
This also can be closed now as currently sorting is handled well while loading itself. @iamareebjamal what do you say?

**Comment by iamareebjamal** [comment]
@mejariamol Implementing sorting in FastAdapter will also fix the flaky tests and enable us to provide a custom sorting feature in future. Like sort by checked in, etc

**Comment by srv-twry** [comment]
@iamareebjamal Can i take this ?

**Comment by iamareebjamal** [comment]
Yes, I forget if it is already implemented somewhere so please check

**Comment by AkshayCHD** [comment]
@iamareebjamal does this issue include implementing fast adapter for events list, as currently the events list is populated through a simple recycler view adapter

**Comment by iamareebjamal** [comment]
Right now we don't need any of fast adapter features in event list

**Comment by AkshayCHD** [comment]
@iamareebjamal so this issue is implemented i think, is there some part left?
