### ISSUE TITLE
Fix selected color in NavigationDrawer

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#282]
Navigation Drawer selected color should be darker and not lighter

![device-2017-07-07-185218](https://user-images.githubusercontent.com/3874064/27959546-8333dc26-6345-11e7-8212-d14102ae4686.png)

**Comment by mejariamol** [comment]
you mean text color right?

**Comment by iamareebjamal** [comment]
Yes, text and icon color

**Comment by mejariamol** [comment]
taking this up.

**Comment by iamareebjamal** [comment]
:+1:

**Comment by mejariamol** [comment]
@iamareebjamal 

![unnamed](https://user-images.githubusercontent.com/13533840/27961280-d1b4c634-634b-11e7-9178-d6ed6763249f.png)
