### ISSUE TITLE
Create Settings Page and add timezone changing settings

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#292]
- Create Settings Page
- Add option to switch from event timezone to local timezone

**Comment by mejariamol** [comment]
It will be event specific settings, right?
Better we add the setting page for the event. I mean Dashboard, Attendees, Settings @iamareebjamal

**Comment by iamareebjamal** [comment]
Yeah

**Comment by mejariamol** [comment]
but event location can differ for same organizer

**Comment by iamareebjamal** [comment]
Doesn't matter, we'll show what his local location is
