### ISSUE TITLE
Making single base interface for all presenters

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#315]
Currently, there are two base interfaces for presenter - IPresenter and IDetailPresenter. 

Expected: Make single base interface for presenter creating separate method for attaching key to the detail presenter. So that single base interface can be kept for presenters.

Sending a PR

**Comment by iamareebjamal** [comment]
This is not correct TBH. If it was possible in Android, we would be adding view and key in the constructor itself as required dependency. But as view initialization is late, we can't. So as a safety mechanism, we attach view and key at the same time. This prevents errors like forgetting to attach key after attaching view, or vice versa. There is no benefit of separating this. What you can do is create another interface as root interface for both of these containing only detach, but I don't understand the point behind it.

**Comment by mejariamol** [comment]
I wanted single presenter interface containing attach detach for loaders. With this we get a single base presenter interface for all the presenters.

**Comment by iamareebjamal** [comment]
You can create an abstract class leaving the attaching part up to the presenters. Can you share the design proposal of the implementation? Maybe I can help

**Comment by mejariamol** [comment]
@iamareebjamal Just a doubt. Can I store IAttendeesPresenter object as IPresenter in loader. And still shall be able to use its other methods (of IAttendeesPresenter not of IPresenter) after restoring(type casting to IAttendeesPresenter) it from loaders?

**Comment by mejariamol** [comment]
Not required for now. Was able to implement presenter loaders using IBasePresenter. Hence closing it,
