### ISSUE TITLE
Add tooltips to ticket graph

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#318]
We need to show the amount and date the order took place in the form of tooltip for each data point

**Comment by AkshayCHD** [comment]
Sir i would like to work on this issue can you tell me where to display the tooltip and in which model is this data stored.

**Comment by iamareebjamal** [comment]
The tickets graph is shown in Dashboard, it is to be shown there. The data is in Ticket model

**Comment by AkshayCHD** [comment]
Sir what graph are you talking about i didn't find any graph in dashboard.

**Comment by iamareebjamal** [comment]
There would be no graph if there are no sales for the event. You'll have to add tickets and then attendees for them

**Comment by AkshayCHD** [comment]
@iamareebjamal i am unable to add attendees using postman,
the api endpoint i used is http://open-event-api.herokuapp.com/v1/tickets/332 and  and i am getting 
` ` ` <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p> ` ` `

but when i use http://open-event-api.herokuapp.com/v1/tickets/332 to find tickets it is working properly and givine ` ` ` {
    "links": {
        "self": "/v1/tickets/332"
    },
    "jsonapi": {
        "version": "1.0"
    },
    "data": {
        "links": {
            "self": "/v1/tickets/332"
        },
        "attributes": {
            "is-description-visible": true,
            "type": "free",
            "min-order": 1,
            "sales-ends-at": "2018-01-29T18:21:41.322000+00:00",
            "max-order": 10,
            "is-fee-absorbed": false,
            "description": null,
            "sales-starts-at": "2018-01-27T18:21:41.322000+00:00",
            "is-hidden": false,
            "name": "second ticket",
            "price": 0,
            "quantity": 1,
            "position": 1
        },
        "relationships": {
            "event": {
                "links": {
                    "related": "/v1/tickets/332/event",
                    "self": "/v1/tickets/332/relationships/event"
                }
            },
            "ticket-tags": {
                "links": {
                    "related": "/v1/tickets/332/ticket-tags",
                    "self": "/v1/tickets/332/relationships/ticket-tags"
                }
            },
            "attendees": {
                "links": {
                    "related": "/v1/attendees?ticket_id=332",
                    "self": "/v1/tickets/332/relationships/attendees"
                }
            },
            "access-codes": {
                "links": {
                    "related": "/v1/tickets/332/access-codes",
                    "self": "/v1/tickets/332/relationships/access-codes"
                }
            }
        },
        "type": "ticket",
        "id": "332"
    }
} ` ` `

**Comment by iamareebjamal** [comment]
Attendees are added via /attendees endpoint

**Comment by AkshayCHD** [comment]
@iamareebjamal i created attendees using the endpoint but still i see no chart or graph
