### ISSUE TITLE
Handle presenter reload from loader

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#325]
Presenters are now correctly retained through loaders

- Design a mechanism to restore saved changes rather than loading again from db
- Do this through generic mechanism

**Comment by mejariamol** [comment]
taking this up

**Comment by mejariamol** [comment]
@iamareebjamal please check the approach:
1. presenter will save the loaded data into fields
2. On _start_, the presenter will check if the data is already saved and loads accordingly, and sends to the view.

**Comment by iamareebjamal** [comment]
Yes, that's the normal approach but how to make it general. I mean event detail presenter is slightly more complex. How to make it automatic?

**Comment by mejariamol** [comment]
The presenter must have these two separate parts:
1. Data loading/saving into fields
2. Sending data to the view

Currently, both are mixed using Rx Observable Transformers. Will need to change that right? @iamareebjamal

**Comment by iamareebjamal** [comment]
You would just need to call replay on these observables to get the last emitted values

**Comment by mejariamol** [comment]
>call replay on these observables to get the last emitted values

We don't want to get the emitted items again from the observables. We will be saving the loaded data into fields in the presenter. right? @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes, but this would be a more general solution. If start is called for the first time, -> load from original source, and if it is called again, just call replay to emit the older values. This will also be easier to implement rather than taking care of different logic in each presenter

**Comment by mejariamol** [comment]
Will try it.

**Comment by mejariamol** [comment]
Leaving it for now. It is open.

**Comment by iamareebjamal** [comment]
The complex nature of requested resources in each presenter makes it difficult to make this generic. Solutions have been sent as PR. Will reopen this if we think of a solution in future
