### ISSUE TITLE
Verify correct detach call on presenter

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#326]
Loaders automatically remove the instance of item when the loader container is actually getting destroyed. Currently, several detach calls are made in fragment and activities stopping any ongoing task, which defeats the purpose of retaining presenters.

- View should get detached for each fragment/activity
- The containing composite disposable should only be disposed when the view is actually destroyed

**Comment by mejariamol** [comment]
taking this up.

**Comment by iamareebjamal** [comment]
Closing as invalid now
