### ISSUE TITLE
Implement Yaydoc to generate documentation

### ISSUE THREAD

**Issue by sch00lb0y** [fossasia/open-event-orga-app#330]
[Yaydoc](http://github.com/sch00lb0y/yaydoc) is a documentation generation project maintained by FOSSASIA. Implement yaydoc in `open-event-orga-app` to generate documentation and also register `open-event-orga-app` to Yaydoc CI for continuous documentation deployment.

**Comment by sch00lb0y** [comment]
I would like to work on this.

**Comment by niranjan94** [comment]
@sch00lb0y all open event projects need to come together. 

Parent Project: https://github.com/fossasia/open-event

**Sub projects:**

1. https://github.com/fossasia/open-event-orga-server
2. https://github.com/fossasia/open-event-frontend
3. https://github.com/fossasia/open-event-android
4. https://github.com/fossasia/open-event-webapp
5. https://github.com/fossasia/open-event-orga-app

The final documentation is to goto the `gh-pages` branch of  `fossasia/open-event`.

**Comment by mejariamol** [comment]
@sch00lb0y what is the progress on this?

**Comment by sch00lb0y** [comment]
@mejariamol I have fixed this issue. I have sent PR to the respective repositories. You can close this issue.

**Comment by mejariamol** [comment]
>I have sent PR to the respective repositories

Is that mean, doc page is viewable now? So that README.md can be modified accordingly.
