### ISSUE TITLE
Fragments overlap if switched while refreshing

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#331]
How to produce:
1. Open one of the section. for example Event Dashboard
2. Swipe down to refresh
3. open another section while loading is on
4. result:

![screenshot_2017-07-20-13-53-53](https://user-images.githubusercontent.com/13533840/28413081-f382d126-6d63-11e7-8e30-fd9fef0a898b.png)

I am working on it.

@iamareebjamal any hint?

**Comment by iamareebjamal** [comment]
Should not happen. Check if detach is called when switching sections

**Comment by mejariamol** [comment]
yes. detach is called. And it is called twice for a presenter. (Don't know why?)

**Comment by iamareebjamal** [comment]
Because of https://github.com/fossasia/open-event-orga-app/issues/326

**Comment by mejariamol** [comment]
Yeah, that is another issue. But why `CompositeDisposable` not working here.

**Comment by iamareebjamal** [comment]
It should be working. I don't think composite disposable is the issue here

**Comment by mejariamol** [comment]
And this never happens on rotation. Does this mean subscribers are never destroyed until main activity is destroyed?

**Comment by iamareebjamal** [comment]
No, because the detach is called when the fragments change. Will look into it

**Comment by mejariamol** [comment]
@iamareebjamal the issue is with swipe refresh layout. https://issuetracker.google.com/issues/37008170
