### ISSUE TITLE
Make generic bus for data passing

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#338]
Currently, IBus is used to pass selected event between fragment and MainActivity.

Expected: Make it generic to support other data types. 

Sending a PR.

**Comment by iamareebjamal** [comment]
This is not type safe then. Suppose we want to have two different bus for event type only. What will be the solution for that?

**Comment by mejariamol** [comment]
I did this to pass ChartAnalyser object. Will be able to do that. right? I mean will I be able to inject `IBus<Event>` and `IBus<ChartAnalyser>` separately ?

**Comment by iamareebjamal** [comment]
But if I want two bus for event type. How will I get that?

**Comment by mejariamol** [comment]
>But if I want two bus for event type. How will I get that?

di should not be preferred for that case. 

Can we achieve it with di ?? what do you think?

**Comment by iamareebjamal** [comment]
We can do it with named provider, but tests will fail as we cannot use the same component in tests to inject dependencies. This solution is only viable after #175

**Comment by mejariamol** [comment]
So what shall we do for now? As now there is no case where we want two event buses. With this, ChartAnalyser could be passed to the full-screen page.  @iamareebjamal

**Comment by iamareebjamal** [comment]
Why is ChartAnalyser not injected there?

**Comment by iamareebjamal** [comment]
If you push it, it completely removes the possibility to reuse it in other components -> Tickets Page

**Comment by mejariamol** [comment]
>Why is ChartAnalyser not injected there?

Won't need to reload data again if the already loaded chart analyser is passed.

>it completely removes the possibility to reuse it in other components -> Tickets Page

I didn't get how is this less from what is implemented currently?

**Comment by iamareebjamal** [comment]
We need independent components that do not rely on other components to provide them data. If data is stored in db, we should not expect for other component to provide it. It increases the responsibility of components and makes the components less modular.

In tickets page, we will show the graphs, and then for each of them we'll need to push to the graph detail screen. This is not how it should be

**Comment by mejariamol** [comment]
>We need independent components that do not rely on other components to provide them data. If data is stored in db, we should not expect for other component to provide it. It increases the responsibility of components and makes the components less modular.

ChartAnalyser will not provide data to someone else. It is just like, if data is loaded then why to load again. In detail page chart is already prepared with all the required dataset. So why to reload it. The same can be used in the full screen page.

**Comment by mejariamol** [comment]
Yeah. Got your point. Shall I close it then?

**Comment by iamareebjamal** [comment]
Yes :+1:
