### ISSUE TITLE
Break IUtilModel into smaller functional interfaces

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#342]
UtilModel is getting big and should be broken into smaller components

**Comment by mejariamol** [comment]
One subcomponent can be SharedPreferenceModel. What do you say?

**Comment by iamareebjamal** [comment]
Correct

**Comment by mejariamol** [comment]
Shall we close this now? @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes
