### ISSUE TITLE
Event Detail Page Modification

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#349]
By now, a good analytics is shown on Event detail page but the items are little less organized. 

The modifications can be:
1. Total sale star is overshown compared to the info it shows. Change it.
2. Move sales chart below the total sale
3. Square ticket cards.
4. uniform sized sub headings

@iamareebjamal please suggest if I missed anything.

taking this up.

eventbrite screenshot:

![dashboard](https://user-images.githubusercontent.com/13533840/28499458-45c4837c-6fd4-11e7-8060-073fdb7b7934.png)

**Comment by iamareebjamal** [comment]
@mejariamol Hide the chart if no data. Nice considerations :+1:
