### ISSUE TITLE
Reduce event detail layout complexity using ConstraintLayout

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#357]
I was analyzing the skipped frames using trace view and couldn't get ahold of what was the code which was running slow. Seems like layout inflation of event detail view takes too much time. 

Reduce its complexity by using constraintlayout

**Comment by mejariamol** [comment]
taking this up

**Comment by srv-twry** [comment]
@iamareebjamal @mejariamol Can i take this if you aren't working on it ?

**Comment by iamareebjamal** [comment]
Sure @srv-twry
