### ISSUE TITLE
Unordered tickets

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#365]
tickets in the ticket list page are unordered. 

Screenshot:
![screenshot_2017-07-26-19-42-37](https://user-images.githubusercontent.com/13533840/28625737-c0207154-723a-11e7-86dd-7de4f7775a5d.png)

Expected:
Tickets displayed should be in order. First, all paid then all free.

taking this up

**Comment by iamareebjamal** [comment]
Use the db query for sorting

**Comment by mejariamol** [comment]
@iamareebjamal how many types do we get from the server? I saw in one of the example response on server the type of ticket is `VIP-ticket`?

**Comment by iamareebjamal** [comment]
Server supports any string for type, but the legacy and new front end only provide option for free, paid, and donation, so currently only these are supported
