### ISSUE TITLE
Two alert dialogs appearing if no network connection

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#37]
On starting app without network connection, two alert dialogs are created saying `No Internet Connection`.

**Comment by mejariamol** [comment]
@niranjan94 This happening because `Network.onDisconnect()` behaving in that manner. When no connection initially it is called two times. 
Hence it can be solved by unsubscribing it once error is shown and re-assigning it in `Network.onConnect()`

Shall I make the PR?

**Comment by niranjan94** [comment]
@mejariamol sure. make a PR.
