### ISSUE TITLE
Image Library

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#373]
Picasso has not released a new version since 2015 and has certain issues with first loads and there are no solutions but workarounds. 

Should we move to another library like Glide as it has similar interface to Picasso?

However it is a little bit larger than Picasso. So we have these options:

- Use Picasso 2.6.0 SNAPSHOT and see if it fixes the problem
- Add workarounds to these problems we face (including disk caching)
- Switch to another library

@mejariamol What are your views

**Comment by mejariamol** [comment]
@iamareebjamal actually I am not aware of this now.will have a look into it.

**Comment by iamareebjamal** [comment]
The bus was fixed in 2.6.0-SNAPSHOT which I used in #366, but it is unreleased develop version

**Comment by iamareebjamal** [comment]
3.0.0-SNAPSHOT is working well for now. Will reopen in future if necessary
