### ISSUE TITLE
Manage event selection of app

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#376]
Bus handles click on the selection of event and the event fragment itself triggers the loading of event dashboard. Discuss and plan solution for this

**Comment by mejariamol** [comment]
@iamareebjamal 
Currently, the bus is used for 2 purposes:
1. pushing event from events adapter to the presenter to open dashboard
2. handling the state of the main activity using `storedEventId`.

I think 2nd should be handled in the activity itself without the use of the bus. this will solve #375 too.

**Comment by iamareebjamal** [comment]
I think 1st should be handled by something else. 

Because we do want a stored session event which is reactive. What solution do you propose we can use to make it happen without bus? The problem is with the clicks opening the fragment through bus.

Bus should only update the header view and currency and nothing else. The trigger on event fragment should be handled by something which is not connected to bus

**Comment by mejariamol** [comment]
>The problem is with the clicks opening the fragment through bus.

what problem?

**Comment by iamareebjamal** [comment]
The repeated loading of event dashboard

**Comment by mejariamol** [comment]
No. problem is in the presenter's `onStart` which is handling state of the main activity.

**Comment by mejariamol** [comment]
Initial state of the main activity should be handled in onCreate of main activity

**Comment by mejariamol** [comment]
using the nullity of savedInstanceState

**Comment by iamareebjamal** [comment]
The thing is, bus is also transmitting a value. Which is valid for setting header info, but not for the loading of fragment. The fragment itself is loaded on rotation, so if the bus is not used to open the dashboard, it'll work fine. Yes, your solution is obviously needed, but it is related to #325 

Try by adding take(1) to bus, it will only use 1st transmission from bus and after that rotation will load the fragment automatically
