### ISSUE TITLE
Match Case Search in EventAttendeesPage

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#39]
`searchFilter` implemented on `EventAttendeesPage` needs to search query in an item, ignoring the Case.

**Comment by niranjan94** [comment]
@mejariamol i think it already ignores the case... No?

**Comment by mejariamol** [comment]
@niranjan94 [No. It doesn't.](https://github.com/fossasia/open-event-orga-app/blob/master/src/pages/event-attendees/event-attendees.ts#L128)
