### ISSUE TITLE
Local act and global sync for offline first app implementation

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#404]
As the app is coming to final stages, this crucial feature needs to be implemented ASAP. All the network based actions should be dispatched to a JobScheduler Job if they are failed due to network error or timeout and be configured to be completed on a network connection with exponential backoff strategy.

The persistence of Jobs can be handled by the JobScheduler itself, but we also need to show the user what jobs are pending, which will need an attribute in the table for attendee (check in) and ticket for status.

The task can be broken into 2 parts:
- [ ] Scheduling of Attendee Check In
- [ ] Scheduling of Ticket creation

Canceling of pending jobs can be handled in a later issue

There are two options for JobScheduler which are API version agnostic : 
https://github.com/evernote/android-job
https://github.com/firebase/firebase-jobdispatcher-android

The first one is preferred as it does not require Google Play Services installed on the device. @niranjan94 Please confirm if this constraint is valid

The issue is open for now

**Comment by mejariamol** [comment]
>Scheduling of Ticket creation

I think ticket creation should not use job scheduler. Instead, new ticket draft can be saved if no internet connection available and user can create it later when the internet connection is available.

@iamareebjamal @niranjan94 what do you say?

**Comment by iamareebjamal** [comment]
> Instead, new ticket draft can be saved if no internet connection available and user can create it later when the internet connection is available.

This can robustly done with Job scheduler, and obviously we have to store the draft in db for both check in and ticket as we have to show the user pending actions and to provide the functionality to cancel them in future

**Comment by mejariamol** [comment]
>we have to store the draft in db for both check in and ticket as we have to show the user pending actions and to provide the functionality to cancel them in future

Yeah. In the case of attendee check in it is fine to do the action as the network is back. but for the creation of event ticket, I think the user should have been given an option to re-confirm it when network is back. what do you say?

**Comment by iamareebjamal** [comment]
If the user has clicked on create ticket, and it failed due to network, only then we have to add it to job queue. Adding a confirmation to it will be like adding a draft feature which is currently out of scope, as it woll require maintaining and editing the draft as well. In future, there can be option to save the ticket instead of creating it and then send it. But now, the organizer will have clicked on create ticket and will be expecting it to be created as soon as the network is back. Confirming the ticket to be created will be same as confirming to check in the attendees

**Comment by mejariamol** [comment]
No. I am saying we shall keep creation failed ticket in ticket drafts. And user shall create it when network is available again. It will not be like confirming attendee check in. Ticket creation is not something which can be left to the job scheduler as host must know absolutely if his new ticket is live or not. It is just same as a draft email feature in gmail. 
Of course we can keep it on job scheduler for now. but I think in future this should be handled via draft feature.

**Comment by iamareebjamal** [comment]
When you click send in Gmail, it sends the mail to outbox, not drafts. Handling drafts is completely different feature in entirety

**Comment by mejariamol** [comment]
@iamareebjamal shall I take this up? Will start with attendee check in.

**Comment by iamareebjamal** [comment]
I've started working on it. It is a big issue so we should work together. I'll push the current architecture and plan by the night
