### ISSUE TITLE
Implement pull to refresh on all pages containing data load from server

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#41]
Presently there is no page refreshing feature on the pages which display data from the server.
The pages are
- `EventAttendeesPage`
- `EventDashboardPage`
- `EventsPage`

`SwipeRefreshLayout` from android like feature is preferred.

**Comment by niranjan94** [comment]
@mejariamol add a proper description.

**Comment by abs51295** [comment]
Can I work on this feature @niranjan94 ?

**Comment by niranjan94** [comment]
@abs51295 I guess @mejariamol is working on this ...

@mejariamol can you confirm ?

**Comment by mejariamol** [comment]
@niranjan94 @abs51295  Yes. I am working on this feature.
