### ISSUE TITLE
Event Dashboard Attendance/Tickets Sold Display Error

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#42]
On Event Dashboard page _Total tickets_ value is incremented in place of _Attendance_ value as check in is done.

**Comment by mariobehling** [comment]
@mejariamol Should this one be reported to the server issue tracker? Or can this be solved entirely in the app?

**Comment by mejariamol** [comment]
@mariobehling Nothing wrong with the server. It was an app issue.
