### ISSUE TITLE
Add yaydoc.yml file for yaydoc

### ISSUE THREAD

**Issue by pri22296** [fossasia/open-event-orga-app#420]
Yaydoc will need a yaml file named `.yaydoc.yml` with various configuration.

**Comment by iamareebjamal** [comment]
@pri22296 Just to clarify, why was the PR closed? Is the issue not valid?

**Comment by pri22296** [comment]
@iamareebjamal The docs for this repo would be generated together with other open-event projects as a single site. `.yaydoc.yml` is not required for each and every project. Hence this PR was closed as this repo does not need to override any default settings(such as generating javadocs). Closing this issue though. Thanks for reminding.
