### ISSUE TITLE
Layout optimization using Merge

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#426]
>The \<merge /\> tag was created for the purpose of optimizing Android layouts by reducing the number of levels in view trees. Use the merge tag instead of linearLayout as a root tag around your layout elements if you are going to include that in another layout.

_[source link](http://www.mysamplecode.com/2012/06/android-include-merge-layout-example.html)_

working on it.

**Comment by iamareebjamal** [comment]
This can be taken up later @mejariamol 

There are more pressing issues. We have to make the app ready for release

#266 is not done even after 1 month

**Comment by mejariamol** [comment]
>Data binding does not support include as a direct child of a merge element

[Link](https://developer.android.com/topic/libraries/data-binding/index.html#layout_details)

Closing it.
