### ISSUE TITLE
Ticket type value hides from attendee on swipe refresh

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#435]
Attendees page
In the response for `getAttendees` request from the server, all the other fields of the ticket are null excluding id. Hence ticket type is not shown after swipe refresh. Whereas it is shown when attendees are loaded from the local database.

**Comment by mejariamol** [comment]
As on force refresh, attendees bound to the layout are the attendees from the API response which only contain ticket id hence all the other fields are shown null. hence ticket type too.

need to change force refresh implementation
data always must be loaded from the database. what do you think @iamareebjamal

**Comment by iamareebjamal** [comment]
Yes it should be the single source of truth. This change can be made in AbstractObservableBuilder

**Comment by mejariamol** [comment]
>This change can be made in AbstractObservableBuilder

I am not seeing any way of doing it in AbstractObservableBuilder. Will you please be more specific about the approach. I was thinking to do it in the presenter.

**Comment by iamareebjamal** [comment]
```Java
@NonNull
    public Observable<T> build() {
        if (diskObservable == null || networkObservable == null)
            throw new IllegalStateException("Network or Disk observable not provided");

        return Observable
                .defer(getReloadCallable())
                .switchIfEmpty(getConnectionObservable())
                .flatMap(r -> diskObservable)
                .compose(applySchedulers());
    }
```

**Comment by mejariamol** [comment]
will try on it, in few hours

**Comment by mejariamol** [comment]
>.flatMap(r -> diskObservable)

this will emit items for number of times of total items. that mean is two attendees it will emit 4 attendees each one for two times.

**Comment by iamareebjamal** [comment]
Hmm. Correct. But the changes can be made in AbstractObsetvable only

**Comment by iamareebjamal** [comment]
```Java
return Observable
                .defer(getReloadCallable())
                .switchIfEmpty(getConnectionObservable())
                .toList()
                .flatMap(items -> diskObservable.toList())
                .flattenAsObservable(items -> items)
                .compose(applySchedulers());
```

Shall I send the PR?
