### ISSUE TITLE
Fix miscellaneous bugs

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#439]
There are certain miscellaneous small bugs:

- The SharedPreferences are being uploaded and restored making the app usage inconsistent
- On resume of any list containing fragment, the listeners are not set correctly
- On resume of any list containing fragment, the header padding is doubled

Working on it

**Comment by mejariamol** [comment]
>On resume of any list containing fragment, the listeners are not set correctly

all listeners seem working fine for me. please specify the ones which are not working correctly.

**Comment by iamareebjamal** [comment]
Have done so in the PR itself

Go to Attendee List, open Scan Activity, return, try to search, try to go to tickets page ...
