### ISSUE TITLE
Only show email and password and a checkbox for server on start screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#44]
The start screen currently gives three options to fill in:
Server, Email, Password.

Please only show Email and Password and below a small checkbox in smaller font
* [X] eventyay.com

If the user unticks the checkbox, it should be possible to enter an alternative deployment (just like now).

**Comment by betterclever** [comment]
Working on this

**Comment by betterclever** [comment]
@niranjan94 This can be closed
