### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#441]
As the app is going to be released soon, there should be an app icon.

Proposed icon:

![bada](https://user-images.githubusercontent.com/3874064/29086901-b8efd4c2-7c91-11e7-8560-ba8a7d225c54.png)

@niranjan94 @mariobehling @mejariamol Please comment

**Comment by mejariamol** [comment]
1. as `31st` is the only literal in the logo it seems to have some direct relation to the app name. which is not true.
2. top right side section is unclear? what is it showing?

**Comment by iamareebjamal** [comment]
Event as dates in calendar. 31st is quite a standard text in date based applications. Top right side is showing nothing

**Comment by mejariamol** [comment]
Great design btw! @iamareebjamal  :+1:
