### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#442]
Create splash screen. Only should be shown initially when not logged on.

**Comment by iamareebjamal** [comment]
There should be no logic for showing splash screen at all. Only used in cold start

https://www.bignerdranch.com/blog/splash-screens-the-right-way/

**Comment by mejariamol** [comment]
Yeah. On initial start it takes some time to open dashboard when just blank white screen is displayed.

**Comment by iamareebjamal** [comment]
This is not apparent in release build

**Comment by mejariamol** [comment]
okay. closing it for now. :+1:
