### ISSUE TITLE
Success of Checked-in Attendee unclear

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#46]
Scanning the QR code of an attendee does not give me a clear success message. Has it been successful or not?

Expected: Show a screen "Success. Attendee [Name of Attendee] has been checked in."

Below that display a button "OK"

**Comment by betterclever** [comment]
I am working on this.

**Comment by betterclever** [comment]
Held due to #3356 on Orga Server.

**Comment by niranjan94** [comment]
@betterclever https://github.com/fossasia/open-event-orga-server/issues/3356 is resolved. Please proceed.

**Comment by mejariamol** [comment]
@mariobehling @niranjan94 _Not giving a success message_ is ok. This can be the case of poor network connection, when the attendees check-ins are added to the `queueService` for further sync with the server.
_Validating a check-in_ is necessary, while check in. That is to check- if the scanned QR is valid attendee.

Can we go for this: Show a screen or symbolic signal for valid attendee and an error message for invalid attendee.

**Comment by mariobehling** [comment]
> Can we go for this: Show a screen or symbolic signal for valid attendee and an error message for invalid attendee.

Yes. And below a big button "OK", please. This confirms things. We can think about better things later. The question is if this is possible before Thursday.

**Comment by mejariamol** [comment]
@mariobehling Yes. I will work on this.

**Comment by mejariamol** [comment]
@betterclever Are you working on this already?

**Comment by betterclever** [comment]
@mejariamol I am working on this. I have made initial changes for it. It will be done by tonight.

**Comment by niranjan94** [comment]
@betterclever @mejariamol try to work as a team and make sure both of you are not working on the same thing together.

@betterclever clever is saying that he's working on it. And we have a PR opened by @mejariamol .

**Comment by betterclever** [comment]
@niranjan94 We collaborated on Gitter. He had already solved that issue while working on another issue so he sent a PR 😃.

**Comment by mejariamol** [comment]
@niranjan94 yes, we had conversation on gitter about same.

**Comment by niranjan94** [comment]
@betterclever @mejariamol then please make sure such things are added in the issue as well that way everybody knows what's happening.. Let's try to keep the discussions on the issues itself as much as possible and try not to discuss in private.

**Comment by mejariamol** [comment]
@niranjan94 sure.

**Comment by betterclever** [comment]
@niranjan94 Will take care from next time. 👍
