### ISSUE TITLE
Show event state in events page

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#472]
Currently, there is no indication of the state of an event, whether it is draft or published on the events page.

- [ ] Add an indicator
- [ ] Add an option to change event state in dashboard

**Comment by mejariamol** [comment]
Are you working on this? @iamareebjamal

**Comment by iamareebjamal** [comment]
No, I usually write working on it or assign the issue to myself if I do

**Comment by mejariamol** [comment]
taking this up.

**Comment by mejariamol** [comment]
@iamareebjamal Event GET request not returning draft events currently.
