### ISSUE TITLE
Replace Nav Header Placeholder image to without text

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#486]
Currently the placeholder image in the Nav Header is with text which is overlapping with other texts shown in the header like organizer name. 

Expected: Change the image to no text.

Working on it.

Current View:

![screenshot_2017-08-19-17-04-55](https://user-images.githubusercontent.com/13533840/29486341-1a8a76e8-8501-11e7-91d1-de3bae684e56.png)

**Comment by iamareebjamal** [comment]
I think the image should be more generic like the one in EventBrite

**Comment by mejariamol** [comment]
@iamareebjamal how about this?

![screenshot_2017-08-19-19-53-17](https://user-images.githubusercontent.com/13533840/29487624-14d078a6-851a-11e7-89af-4e52c8b00a7a.png)

**Comment by iamareebjamal** [comment]
It can still interfere with places with light and dark areas. See the eventbrite app header. It is plain image with certain graphic repeating. Like a sprite

**Comment by mejariamol** [comment]
this image can be darkened more for now. Or please suggest any image which can be used?
