### ISSUE TITLE
Check in attendees with barcodes using the camera-based scanner

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#5]
The open event orga server will provide a barcode on tickets. The app needs to be able to easily validate attendee barcodes using the camera-based scanner and sent the information back to the server through an API.

**Comment by the-dagger** [comment]
@niranjan94 I would like to work on this.
Could you please assign it to me?
P.S. It can take a bit time as I am still learning node, but I will try to complete this asap.
