### ISSUE TITLE
Bump version, test release build and merge to master

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#500]
- Increment app version
- Test release build manually
- Create PR to merge dev to master

@mejariamol Can you take this up?

**Comment by mejariamol** [comment]
yeah sure. @iamareebjamal

**Comment by mejariamol** [comment]
what exactly has to be done in the code? just incrementing the version?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
Also, change name to `eventyay organizer`

**Comment by mejariamol** [comment]
app name?
