### ISSUE TITLE
Add DateService Tests

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#505]
Parent Issue #306

**Comment by mejariamol** [comment]
Open for now.
the issue is mocking static methods. and mocking events which are past, live and upcoming with mock now time.

**Comment by iamareebjamal** [comment]
Actually, just create events of different time and check the return string from the static methods

**Comment by iamareebjamal** [comment]
Can I take this up @mejariamol ?

**Comment by mejariamol** [comment]
@iamareebjamal yeah sure.
