### ISSUE TITLE
Add option to create Event

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#518]
Add option to create an event with required fields

This issue follows creation of event with only basic bare minimum fields

**Comment by Masquerade0097** [comment]
@iamareebjamal Please give a description about the UI which you require for this feature.

**Comment by iamareebjamal** [comment]
@Masquerade0097 In the events page, there should be a FAB for creating an event which should take you to a Create Event Fragment which will feature all required and optional fields for the event to be created (tally with API), then the event should be created through a button in Toolbar

**Comment by Masquerade0097** [comment]
@iamareebjamal In the API there are two similar confusing fields - `location name , searchable location name` , what's the difference?  Does user enters latitude and longitude input along with the above location input simply as TextInput or is it somehow connected to Google Maps API in this app ?

**Comment by iamareebjamal** [comment]
Let's focus only on required fields now, extra information can be added later. Also, let's only focus on text-based input wherever required
