### ISSUE TITLE
Show all model data in UI

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#522]
Show all model data using additional details button
- [ ] Order Detail
- [ ] Attendee Detail

Working on attendee detail

@mejariamol Can you please take up Order Detail?

**Comment by mejariamol** [comment]
Yeah sure.

**Comment by mejariamol** [comment]
@what ui you are following for ticket details? @iamareebjamal

**Comment by iamareebjamal** [comment]
A little change @mejariamol. I have updated the issue, there is no change required in ticket detail. Only in attendee detail regarding attendee and order model

The UI will be like this:

There'll be a show hide panel for more attendee details and same for order details in Attendee Check In Layout

**Comment by srv-twry** [comment]
@iamareebjamal Can i take this if it's available ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by srv-twry** [comment]
@iamareebjamal I am trying to work on the attendee details first and i have a problem. How do i test it if it displays the info correctly or not. To do that i will have to use the API to create an attendee since it is empty right now.
I wrote a python script to generate an attendee but i am getting HTTP 405 method not allowed on it.

Here is the script
``` Python 3
import requests

access_token = "my token here"

base_url = "https://open-event-api.herokuapp.com/"
event_identifier = 575
ticket_identifier = 338

path = "v1/attendees/575"
data = { 
	"attributes": {
      "firstname": "John",
      "lastname": "Doe",
      "email": "johndoe@example.com",
      "address": "address",
      "city": "example",
      "state": "example",
      "country": "IN",
      "is-checked-in": "false",
      "pdf-url": "http://example.com"
    },
    "type": "attendee",
    "relationships": {
      "event": {
        "data": {
          "id": 575,
          "type": "event"
        }
      },
      "ticket": {
        "data": {
          "id": 338,
          "type": "ticket"
        }
      }
    }
}
headers = {
	'Content-Type' : "application/vnd.api+json",
	'Authorization' : "JWT " + access_token
} 

r = requests.post(base_url + path, headers = headers, json = data)
print(r.text)

```

output of the script:
``` HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

**Comment by iamareebjamal** [comment]
I'd recommend you to use tools like Postman for this. Also, try posting at /events/<event>/attendees

**Comment by srv-twry** [comment]
I have tried the below three without success. 
https://open-event-api.herokuapp.com/events/attendees/
https://open-event-api.herokuapp.com/events/575/attendees/
https://open-event-api.herokuapp.com/events/attendees/575

Should i create a new issue in the server ?

**Comment by iamareebjamal** [comment]
The endpoint is `http://open-event-api.herokuapp.com/v1/attendees`

**Comment by AkshayCHD** [comment]
@srv-twry how did you create attendee then, actually i am facing the same issue as you did,
` ` ` <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>  ` ` `

**Comment by Masquerade0097** [comment]
@srv-twry Can i work on this, if you arn't? Or maybe we can divide the two tasks.

**Comment by srv-twry** [comment]
@Masquerade0097 Yeah sure, I'm slightly busy with my midsems. 
I can take the order detail and you can take the attendee detail.

**Comment by iamareebjamal** [comment]
@srv-twry @Masquerade0097 Status? Only order details remain to be shown

**Comment by Masquerade0097** [comment]
@iamareebjamal I was working on Attendee details and it's completed. @srv-twry can let you know the status for Order Details.

**Comment by srv-twry** [comment]
Apologies, I have been busy with the exams and then the proposals. I will send the PR in a few days. 
In the meantime, if anyone wants to take it, they definitely can.

**Comment by AkshayCHD** [comment]
@srv-twry can I take this issue please?

**Comment by AkshayCHD** [comment]
@iamareebjamal i am unable to create an order object,
i am trying to post object 
` ` ` {
  "data": {
    "attributes": {
      "payment-mode": "paypal",
      "country": "India",
      "status": "pending",
      "amount": "1"
    },
    "type": "order",
    "relationships": {
      "attendees": {
        "data": [
          {
            "id": "2",
            "type": "attendee"
          }
        ]
      },
      "event": {
        "data": {
          "id": "25",
          "type": "event"
        }
      }
    }
  }
} ` ` `
on the endpoint http://open-event-api-dev.herokuapp.com/v1/orders  the error i am getting is 
{
    "errors": [
        {
            "detail": "Unknown error",
            "source": {
                "pointer": ""
            },
            "status": 500,
            "title": "Unknown error"
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}

**Comment by Masquerade0097** [comment]
@iamareebjamal I tried getting list of Orders from the Server but I am getting 403 Access Forbidden, Admin Access required. I think that should not be the case. The Organizer should be able to view all the Orders for an Event a in EventBrite app. What do you think?

**Comment by iamareebjamal** [comment]
Yes it was available before. Please create an issue in server

**Comment by sridharjajoo** [comment]
@iamareebjamal Is order creation within the scope of the app?

**Comment by iamareebjamal** [comment]
Yes, all API capabilities are in the scope of the app

**Comment by Masquerade0097** [comment]
@iamareebjamal I think it's completed and can be closed.
