### ISSUE TITLE
Add a button "check in" or displayed "Checked in" next to attendees name

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-app#53]
Just like on the server, please add a button "check in" on the right next to the name of attendee on the list in green. If the attendee has checked in already show a red button "Checked in". Enable to revert the status in the app.

**Comment by betterclever** [comment]
@mariobehling Please approve if following approach is fine
- A "Check In" button in corresponding to every person in Green.
- If Checked In , show a red button instead of above mentioned green button.
- If the above mentioned Red button is pressed, a dialog appears asking "Do you wish to revert the status?" with YES and NO option.

Suggest changes if any.

**Comment by mariobehling** [comment]
@betterclever Sounds good. Let's go with that.

**Comment by mejariamol** [comment]
@mariobehling @niranjan94 @betterclever See if this is fine. Any suggestions??

![screenshot 17](https://cloud.githubusercontent.com/assets/13533840/23937814/6bb78b3a-097f-11e7-9a5e-1158a938ce49.png)

**Comment by mariobehling** [comment]
Can you make "checked in" into a red button, please.

Is it possible to revert checked-in if necessary?

What happens if users push "Check In". There should be a pop-up box "checking in -Name, Ticket Name-" and a button "OK"

**Comment by mejariamol** [comment]
@mariobehling Ok. I am making required changes.

**Comment by betterclever** [comment]
@mejariamol Are you working on this? Please proceed then, I won't be able to work till tomorrow morning I'm travelling currently. :+1:

**Comment by mejariamol** [comment]
@mariobehling @niranjan94 Check if this is fine. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/13533840/23942339/ed26af0e-0991-11e7-88f2-698fc2a36d98.gif)

**Comment by mejariamol** [comment]
Shall I make PR with this?
