### ISSUE TITLE
Keyboard Closing not right

### ISSUE THREAD

**Issue by ujjwalagrawal17** [fossasia/open-event-orga-app#538]
**Actual Behaviour**

When credentials are wrong and we press the login button, the Snackbar is not visible to the user.

**Expected Behaviour**

Firstly the keyboard should be closed and then Snackbar should be visible to the user.

**Steps to reproduce it**

In showError function in LoginFragment code for hiding keyboard should be added before Snackbar is shown.

**Screenshots of the issue**

![screenshot_2017-09-07-02-18-02-670_org fossasia eventyay](https://user-images.githubusercontent.com/19607555/30134924-8db97b54-9376-11e7-902b-21bf57257a67.png)

**Would you like to work on the issue?**
Yes

**Comment by ivary43** [comment]
@ujjwalagrawal17 can i work on this ?

**Comment by ujjwalagrawal17** [comment]
@ivary43
