### ISSUE TITLE
Implement forgot password feature

### ISSUE THREAD

**Issue by ujjwalagrawal17** [fossasia/open-event-orga-app#548]
**Expected Behaviour**

we need to implement forgot password function.

**Would you like to work on the issue?**

yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Can i work on this issue?

**Comment by iamareebjamal** [comment]
Yes @Masquerade0097

**Comment by srv-twry** [comment]
@iamareebjamal Can i take it since it seems @Masquerade0097 isn't working on it ?

**Comment by Masquerade0097** [comment]
@srv-twry I'm working on it.

**Comment by shubham-padia** [comment]
This exists already

**Comment by Masquerade0097** [comment]
@iamareebjamal  This feature is now implemented in the app but was not auto closed. Please close this.

**Comment by iamareebjamal** [comment]
Fixed by #580
