### ISSUE TITLE
Translations needed for JSON definition list of all repos and filemasks, so they can be imported to weblate

### ISSUE THREAD

**Issue by ParthS007** [fossasia/open-event-orga-app#552]
[https://github.com/fossasia/labs.fossasia.org/issues/231](https://github.com/fossasia/labs.fossasia.org/issues/231)

Please refer to this issue for more info.

**Comment by Masquerade0097** [comment]
@iamareebjamal Should we close it ?

**Comment by ParthS007** [comment]
Closing it :+1:
