### ISSUE TITLE
Improperly cached Attendee List

### ISSUE THREAD

**Issue by betterclever** [fossasia/open-event-orga-app#56]
The Attendee list is not cached according to event ID leading to display of wrong attendees for an Event when an app is offline.

I am fixing this. Needed for #49.

**Relevant Screencast:**
![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/16309034/23823909/6a21ad86-0692-11e7-859f-4435d76167aa.gif)

Here Attendees for event betterclever-test-event are showing up in betterclever-test-event2. The list updates when internet is on.

**Comment by mejariamol** [comment]
@betterclever what is your status for this issue? Shall I work on this?

**Comment by betterclever** [comment]
I fixed that already. I was just confirming my approach with niranjan94 first on Gitter but he was busy at that time.

**Comment by betterclever** [comment]
Can be closed.
