### ISSUE TITLE
Refactor the Event module from MVP to MVVM

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#564]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Refactor the Event module from MVP to MVVM. 
   
 **Would you like to work on the issue?**

Yes.

Create separate child issues for each fragment of this module treating this as a parent issue.
Parent issue: #562

**Comment by AkshayCHD** [comment]
@srv-twry can i work on this issue

**Comment by srv-twry** [comment]
Yes, please go ahead.
