### ISSUE TITLE
Refactor the Main module from MVP to MVVM

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#565]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Refactor the Main module from MVP to MVVM. 
   
 **Would you like to work on the issue?**

Yes.

Create separate child issues for each fragment/activity of this module treating this as a parent issue.
Parent issue: #562

**Comment by mishuvs** [comment]
Sir @iamareebjamal , @srv-twry I want to work on this issue. Can you please help me get started?

**Comment by srv-twry** [comment]
@mishuvs I believe right now this is out of scope. It would be better to develop features rather than refactoring from MVP to MVVM. Let's wait for what @iamareebjamal has to say though.

**Comment by iamareebjamal** [comment]
Yes, this can be tacked later

**Comment by mishuvs** [comment]
Alright, @srv-twry @iamareebjamal , I will focus on other issues for now.
