### ISSUE TITLE
Search Bar is getting scrolled with the attendees list

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#57]
On the `Attendees page`, search bar is getting scrolled with the attendees list. It must be fixed at its position.

**Comment by mejariamol** [comment]
@niranjan94 Shall we put it in the toolbar? Just like action bar search view in android.

**Comment by mejariamol** [comment]
@mariobehling @niranjan94 Is this fine- fixing search bar in toolbar?

![screenshot_2017-03-13-23-46-17](https://cloud.githubusercontent.com/assets/13533840/23870408/511056b0-084c-11e7-8f48-b1d685341a63.png)

**Comment by niranjan94** [comment]
@mejariamol sure ... make a PR
