### ISSUE TITLE
Replace Presenter with ViewModel for TicketsFragment

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#577]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Replace the Presenter for the TicketsFragment with ViewModel. 
Parent - #567 
   
**Would you like to work on the issue?**

Yes

**Comment by srv-twry** [comment]
@iamareebjamal I explored the code for this issue and i have a question before i can actually start refactoring to ViewModel.
How would you suggest refactoring the Rx stuff(View Transformers) used in the Presenter.
For eg: Below is the code for loading Tickets

```Java
public void loadTickets(boolean forceReload) {
        getTicketSource(forceReload)
            .compose(dispose(compositeDisposable))
            .compose(progressiveErroneousRefresh(getView(), forceReload))
            .toSortedList()
            .compose(emptiable(getView(), tickets))
            .subscribe(Logger::logSuccess, Logger::logError);
    }
``` 
How would you suggest refactoring calls like ```.compose(progressiveErroneousRefresh(getView(), forceReload))``` because i certainly can't have reference to Views inside the ViewModel.
The only way i can think of is to handle these things in the View only.

**Comment by iamareebjamal** [comment]
This will be changed by having SingleEventLiveData and triggering those in the Presenter

**Comment by srv-twry** [comment]
Closing these child issues for now since main priority is to develop more features.
Will open it when required.
