### ISSUE TITLE
Remove Logout menu from Login Page

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#58]
Right now the Logout menu is also showing up on login page by swiping in from left side.

![screenshot_2017-03-13-01-54-59](https://cloud.githubusercontent.com/assets/13533840/23835629/ae723f06-0790-11e7-8ccd-1c0cec7936d3.png)

**Comment by betterclever** [comment]
@mejariamol Are you working on this?

**Comment by mejariamol** [comment]
@betterclever No. You can work on it.
