### ISSUE TITLE
Change Password feature for logged In User

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#581]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Feature Description**

There should be an option for the user already logged in the app to change his/her account password. The user after logging in the app will have an option to change the password by firstly entering the old password and then setting the new password. I'm planning to add the change password option in the Settings->App Settings.

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Please review.

**Comment by iamareebjamal** [comment]
Please go ahead but add the feature in Profile Area (Opens when profile pic is clicked)
