### ISSUE TITLE
Option to toggle password Visibility in Auth Module

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#582]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Feature Description**

There should be an option by which password can be made visible and vice versa.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Please review.

**Comment by iamareebjamal** [comment]
Please go ahead
