### ISSUE TITLE
Adding Zooming and Clicking gestures on User's Profile Photo

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#583]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

### Feature Request

**Feature Description**

Clicking gestures - User can load his image on full screen onclick.
Zooming gestures - User will be able to zoom the photo.
   

**Would you like to work on the issue?**

No

**Comment by Masquerade0097** [comment]
@iamareebjamal Please review.

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by srv-twry** [comment]
@Masquerade0097 If you aren't working on it, can i go ahead with this ?
