### ISSUE TITLE
Unit Test for ResetPasswordByTokenPresenter

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#584]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

**Feature Description**

Currently the presenter for ResetPasswordByToken is not tested. So I will add Unit Tests to test it thoroughly which will ensure good performance and point out any potential bugs.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Please approve.

**Comment by iamareebjamal** [comment]
Please go ahead
