### ISSUE TITLE
Loading Animation 

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#586]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

**Feature Description**

Currently android default progress bar is used in the project. It can be replaced by some cool loading animation instead. 
   

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal I have some suggestions -

1. https://github.com/jpardogo/GoogleProgressBar
2. https://github.com/EyalBira/loading-dots

Please approve any one of the above, I'll send PR for the same.

**Comment by iamareebjamal** [comment]
@Masquerade0097 The projects are very old. 2 or 4 years old and not maintained. If they were new and maintained, we could have added those. Secondly, designs are susceptible to change and targeting AppCompat library ensures that we conform to the standard Material Design. Also, as all other eventyay applications, the app should be ultimately themable by the end user of the service and using custom views will make it harder for them to adapt to a new style :smile:

**Comment by Masquerade0097** [comment]
Ok, so the issue isn't needed anymore.
