### ISSUE TITLE
Error handling of JSON response

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#593]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore

**Feature Description**

The error response given by server as JSON String is currently not being deserialized which could instead give better error description for the request. Currently the error string is provided to the view by ErrorUtils which gives the response on the basis of HTTP Error code but better detailed error response is possible by deserializing the server response and passing the string in "detail" tag of the JSON response as the error response to the view.
   
**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@srv-twry @Masquerade0097 @mishuvs @DhruvamSharma @KumarBusem @SahanMonaara @sridharjajoo @Prashant-Chaurasia @YashishDua

This needs to be done asap

**Comment by YashishDua** [comment]
I'll take up this issue!

**Comment by iamareebjamal** [comment]
I'll have to warn that this is an extremely complex issue. You'll have to create custom exceptiond and exception mappers and deal with rxjava to convert generic retrofit exception to a specific one

**Comment by YashishDua** [comment]
Yeah, I'll take care of everything.

**Comment by Masquerade0097** [comment]
@iamareebjamal Sorry for delaying this issue. Please give me a day or two I have a PR almost ready for this.
