### ISSUE TITLE
bug: Event's name getting truncated

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#600]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    

**Actual Behaviour**

The About Event Activity UI is showing only partial name of the event in case the length of name exceeds the view length.

**Expected Behaviour**
There should be marquee animation in textview such that user can full name of the event.

**Steps to reproduce it**

Login -> Create Event -> Select About in Drawer

**Screenshots of the issue**

![escr2](https://user-images.githubusercontent.com/23634977/35425541-79d0d55e-0281-11e8-8d72-660ced0409a5.png)

**Android version and Phone Model**

Moto G4 Plus
    
**Would you like to work on the issue?**

No

**Comment by AkshayCHD** [comment]
@Masquerade0097 can i work on this

**Comment by Masquerade0097** [comment]
Ya, please go on.

**Comment by iamareebjamal** [comment]
@AkshayCHD Status?
