### ISSUE TITLE
feat: Delete Event

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#602]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore

**Feature Description**

There should be an option for a user to delete his/her events from the app.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Please provide the necessary UI details for the feature.

**Comment by iamareebjamal** [comment]
Deleting an event is not an atomic operation. It has many repercussions associated. What if you created an event, sold some tickets and without refunding, deleted it? So it is not a safe operation to provide directly

**Comment by Masquerade0097** [comment]
@iamareebjamal  Ya, you're right. So there should be a check that only if the event has already taken place or if there are no tickets sold for an event then only the user should have the permission to delete that event. Since there is no way of payments or refunds through this app so, for now, refund stuff can't be processed. So should I introduce the feature with the above permission check?

**Comment by iamareebjamal** [comment]
This should be handled by API IMO, and it should throw an appropriate error if the checks are invalid. So let's not implement in client side. Let's wait for the API to stabilize and then communicate with them for suggestions
