### ISSUE TITLE
bug: Passing ObservableField as parameter warning

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#603]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    

**Actual Behaviour**

Presently ObservableField is being passed as a parameter in DateBindings which create the following warning( refer the logcat ).

**Expected Behaviour**
Since the present method is deprecated, it should be changed.

**Steps to reproduce it**

This is a compile time warning.

**LogCat for the issue**

`Warning:Use of ObservableField and primitive cousins directly as method parameters is deprecated and support will be removed soon. Use the contents as parameters instead in method org.fossasia.openevent.app.common.app.binding.DateBindings.bindDate`

**Android version and Phone Model**

Moto G4 Plus    

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@srv-twry @Masquerade0097 @mishuvs @DhruvamSharma @KumarBusem @SahanMonaara @sridharjajoo @Prashant-Chaurasia @YashishDua

Check for the core and high-priority issues first. The older the better

**Comment by Prashant-Chaurasia** [comment]
I'll do this.

**Comment by iamareebjamal** [comment]
OK. But please follow rapid cycles of iterations and pass on the issue if not able to implement. I should warn you though that this issue is not beginner friendly and high priority

**Comment by Prashant-Chaurasia** [comment]
Ya, I'll try to implement this and if I can't then will say this to you.

**Comment by iamareebjamal** [comment]
Please describe your approach first here that how will you solve it after a bit if researching whever you see fit within about 2 days. Thanks

**Comment by Prashant-Chaurasia** [comment]
Sir, I am having my exams till 27th, so, I am not able to give proper time to this issue. Give me 3-4 days and I will resolve this one.Also if you could guide me a bit that will be of much help.
Also I searched a bit and found that we may need to change the adapter - `Ticket.java`  and `DateBindings.java`.Maybe we can change the `ObservableField` variable to `String`.
References:
[https://stackoverflow.com/questions/42570707/data-binding-broke-after-upgrade-to-gradle-2-3](https://stackoverflow.com/questions/42570707/data-binding-broke-after-upgrade-to-gradle-2-3)
[https://stackoverflow.com/questions/44570882/bindingadapter-deprecation-warnings](https://stackoverflow.com/questions/44570882/bindingadapter-deprecation-warnings)

**Comment by iamareebjamal** [comment]
That is obvious. But how will you deal with 2 way binding

**Comment by iamareebjamal** [comment]
That is obvious. But how will you deal with 2 way binding?

**Comment by Prashant-Chaurasia** [comment]
@iamareebjamal Can you give me some insights as to how should I proceed in this. I researched a bit here and there but didn't found anything which could be helpful to make a two way binding without observablefield.

**Comment by iamareebjamal** [comment]
There are a lot of articles on 2 way binding with Data Binding. There's no definitive way. It may be impossible to generalize in some cases, we may move to traditional means of binding in those cases

https://www.bignerdranch.com/blog/two-way-data-binding-on-android-observing-your-view-with-xml/
https://medium.com/@fabioCollini/android-data-binding-f9f9d3afc761
https://medium.com/@douglas.iacovelli/custom-two-way-databinding-made-easy-f8b17a4507d2

**Comment by iamareebjamal** [comment]
@Prashant-Chaurasia Status?

**Comment by Prashant-Chaurasia** [comment]
@iamareebjamal The warning is no more visible in the current build.

**Comment by iamareebjamal** [comment]
It is still there nevertheless

**Comment by srv-twry** [comment]
@iamareebjamal Can i take it ? I guess it's not being worked upon by anyone and has high priority.

**Comment by iamareebjamal** [comment]
Yup, it's important to fix as it will cause many issues, please take it up

**Comment by srv-twry** [comment]
@iamareebjamal I am struggling to understand how to implement two way data binding here. 
The problem is we are setting the date variable on a button and we are modifying the date using a different view, a date picker.
All the examples that i found about 2-way data binding use the same view to change the variable. 
For eg. In [this](https://medium.com/@douglas.iacovelli/custom-two-way-databinding-made-easy-f8b17a4507d2) blog post, he is setting the variable on the edittext, which itself modifies the variable. Hence he can set the ```textChangeListener``` on the edittext and everytime the text changes, he can call the ```onChange``` on the ```InverseBindingListener``` which will call ```InverseBindingAdapter``` to get the value from the EditText and call the setter and update the model. 

In our case we are setting the parameter on a button which opens a DatePickerDialog which modifies it.

**Comment by iamareebjamal** [comment]
Can we do this if we create a custom view?

**Comment by srv-twry** [comment]
Yes, i think so. I'll try it once.
