### ISSUE TITLE
feat: Adding optional fields to Create Event Layout

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#610]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Feature Description**

Modify the Create Event layout to request all the optional fields from the user as well.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal There's a bug. According to [this](https://open-event-frontend.herokuapp.com/create), the user can select whether the event has free or paid tickets enabled which is also an optional field in [this](https://open-event-api.herokuapp.com/#events-events-collection-post). After the creation of event , when the user create tickets, he again has an option to choose between free or paid tickets which can be conflicting. So should i keep the option for choosing the ticketing system while creating an event or not.

**Comment by iamareebjamal** [comment]
The second option is about if the particular ticket is paid or free, not related to global event setting

**Comment by Masquerade0097** [comment]
What about if the global event is selected "free" and the ticket created is "paid" or vice versa.

**Comment by iamareebjamal** [comment]
That's for the API to handle

**Comment by Masquerade0097** [comment]
@iamareebjamal There's an issue with Timezone. The server accepts only this format - `Country/City`,  others give HTTP 500 error. So the format returned by Timezone.getAvailableIds() is rejected by server. That's why to populate timezone spinner I will have to make a new resource file with all the timezones in proper format or we'll have to stick with text based input.
