### ISSUE TITLE
Timezone and Payment currency should be a drop-down menu

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#612]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Right now, when creating an event from the application, the timezone and the payment currency is entered through a text field.
Since these are categorical variables, these should be made a drop down menu and the user should be able to choose from them.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@srv-twry As discussed here, I added necessary fields and text-based input in the Create Event Layout in my first PR and was going to include custom inputs(  which includes Spinners  )in the next PR #610.  So I'm already working on these in #610.

**Comment by srv-twry** [comment]
@Masquerade0097 
>  As discussed here

Sorry, i couldn't find the discussion.

> was going to include custom inputs

Sorry, but i think in the issue you've written 
"Modify the Create Event layout to request all the optional fields from the user as well."
There is no mention of custom inputs. Although if you want to do it in that PR, it's fine :+1: 

> So I'm already working on these 

Okay, please go ahead but kindly mention the exact details or atleast add a link to the discussion in the issue itself to avoid duplicate issues. Thanks.

Closing this.

**Comment by Masquerade0097** [comment]
@srv-twry Sorry, I forgot to attach the link for the discussion, you might not have read that because that issue is now closed. Here is the link  #518 .
