### ISSUE TITLE
CreateEventActivity should be finished after creating a new Event.

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#613]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

After creation of Event is successful, the CreateEventActivity still remains open.

**Expected Behaviour**

It's not a bug but i think it's not standard for it to remain active. In most of the standard applications, the create activities are finished after successful creation.
Not a major issue hence can be labelled ```later```

**Steps to reproduce it**

Create an event using the CreateEventActivity

**Would you like to work on the issue?**

Yes.

**Comment by leeyh20** [comment]
Could I try this issue? Thanks!

**Comment by srv-twry** [comment]
Yeah, please go ahead.

**Comment by iamareebjamal** [comment]
@leeyh20 What's the status of this issue?

**Comment by leeyh20** [comment]
@iamareebjamal Sorry for the late PR, was a bit stuck somewhere. I have created the PR!
