### ISSUE TITLE
Change sale end time default for Create Ticket Screen.

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#614]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

The Sale End time of the CreateTicket Screen starts at the current time.

**Expected Behaviour**

It would be better if it's default end time is the end time of the Event itself.
Not a major issue, can be labelled ```later```

**Steps to reproduce it**

Use CreateTicket screen to create a Ticket.

**LogCat for the issue**

NA

**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
Please check the behaviour on frontend and align with it
