### ISSUE TITLE
Tickets list is not updated automatically after creating new Ticket

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#615]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Tickets list is not updated automatically after creating new Ticket.

**Expected Behaviour**

It should automatically get updated after it.

**Steps to reproduce it**

Add a new ticket using CreateTicketFragment.

**Screenshots of the issue**

![videotogif_2018 01 31_14 18 25](https://user-images.githubusercontent.com/21277837/35613437-136a3d9a-0692-11e8-967b-473b4c56ce2c.gif)

**Android version and Phone Model**

NA
    
**Would you like to work on the issue?**

Yes

**Comment by abhaymaniyar** [comment]
Hello @srv-twry! I would like to work on it. Please let me know if you are not working on it already.

**Comment by srv-twry** [comment]
@abhaymaniyar Hi, I am working on it.

**Comment by iamareebjamal** [comment]
@abhaymaniyar What's the status of this issue?

**Comment by mishuvs** [comment]
I think this issue is resolved. @iamareebjamal Please close this.
