### ISSUE TITLE
Add admin-notifications feature in the application

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#616]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

The API supports the admin-notifications feature. It should be implemented in the application.
   
**Would you like to work on the issue?**

Yes.

**Comment by iamareebjamal** [comment]
Those notifications are for users, not admin

**Comment by srv-twry** [comment]
So this can be a part of the open-event-android project. right ?

**Comment by iamareebjamal** [comment]
Yup

**Comment by iamareebjamal** [comment]
Although you can add admin notifications here

**Comment by srv-twry** [comment]
@iamareebjamal While trying to fetch the admin notifications, i am getting a 403 error response. Admin access is required. How to get that ?
I thought the creator of the event is the admin i.e. me but i can't fetch it. Who is the admin then ?

**Comment by iamareebjamal** [comment]
I think the admin notifications will be for the site-wide admin. @shubham-padia Can you please confirm?

**Comment by srv-twry** [comment]
@iamareebjamal It's out of the scope of this app right ? I already implemented it :cry:

**Comment by iamareebjamal** [comment]
No problem @srv-twry You can request for the user roles and display the section if the user is site wide admin. It is a little off track from the road map, but definitely in the scope as our goal is to encapsulate entire management API in the app

**Comment by srv-twry** [comment]
@iamareebjamal 
Thank you but any suggestion on how to test it ? I can't test whether the notifications are correctly shown or not.

PS: Apologies for the delayed reply. Was busy with mid-sems

**Comment by iamareebjamal** [comment]
You can download open-event-server and set it up locally. Then you'll have admin access, but this can be done later if you want to work on higher priority bugs
