### ISSUE TITLE
Show Event's Additional details in About Event Layout

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#617]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Feature Description**

Currently About Event Layout shows only few attributes of an event. It should show all the details related to an event.

**Would you like to work on the issue?**

Yes

**Comment by srv-twry** [comment]
@Masquerade0097 What are the details that you're trying to add ? 
As i said earlier, please add the complete info or the link to the section of API from where you're going to fetch the data. This way other contributors will know what you want to add and hence will avoid duplicate issues.

**Comment by Masquerade0097** [comment]
@srv-twry  I meant the Event details as shown [here](https://open-event-api.herokuapp.com/#events-event-details-get) under attributes tag of the get event response body. 
> event.Currently About Event Layout shows only few attributes of an event. It should show all the details related to an 

For the copyright info thing, It's not included in this.

**Comment by AkshayCHD** [comment]
@Masquerade0097 can i work on this??

**Comment by Masquerade0097** [comment]
Sorry, I'll be working on that.
