### ISSUE TITLE
Add Statistics to the app

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#618]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

**Feature Description**

In the API there are 3 Types of Statistics available - Order Statistics, Event Statistics and Admin Statistics, none of which is currently present in the app. These should be incorporated in the app.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Please provide the necessary information for this feature.

**Comment by Masquerade0097** [comment]
I'm working on adding the statistics. Removing later label.

**Comment by mishuvs** [comment]
@iamareebjamal Why do we need admin statistics for Organizer App?

**Comment by Masquerade0097** [comment]
@iamareebjamal The admin-statistics endpoint provides info for all the events, users existing in server database. So, this would not be needed here but we can implement Order Statistics now.

**Comment by iamareebjamal** [comment]
OK :+1:

**Comment by Masquerade0097** [comment]
Fully Implemented. Closing this.
