### ISSUE TITLE
Hide unknown information from the ui

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#628]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

The visibility of the views which don't have any data is still set to VISIBLE. eg. In Attendee Details, Event details.

**Expected Behaviour**

If the data is unknown, then the view's visibility should be made GONE.

**Screenshots of the issue**

![screenshot_2018-02-03-18-34-56-59](https://user-images.githubusercontent.com/21277837/35767391-70d29ae6-0911-11e8-9442-5d9f34382b96.png)

**Android version and Phone Model**

All
    
**Would you like to work on the issue?**

Yes

**Comment by MLPJ** [comment]
Hi @srv-twry ,
I would like to work on this issue. Is this stikk open?

**Comment by srv-twry** [comment]
Yeah, it is still open. Please go ahead.

**Comment by MLPJ** [comment]
ok, i'll contact you if there is any issue.

**Comment by MLPJ** [comment]
@srv-twry ,
i have signed up through the android app. I got the verification email too. But the verifiaction email doesnot seem to be working. 
![image](https://user-images.githubusercontent.com/26664908/36041645-3396091e-0def-11e8-8bff-290ca817a81f.png)
Can you please look into this. I can't work on as nothing is shown when i'm logged into the app. It shows that i'm not verified.

**Comment by iamareebjamal** [comment]
There's no need to verify the email

**Comment by MLPJ** [comment]
ok @iamareebjamal

**Comment by AkshayCHD** [comment]
@MLPJ are you still working on this issue, if not can i take over.

**Comment by MLPJ** [comment]
@AkshayCHD  yes i'm still working on the issue, but you can work on it too, I think it does not matter if the owner is ok

**Comment by AkshayCHD** [comment]
@MLPJ  i have no problem with that, but the thing is if i or you make a pull request that fixes the issue then, work of the other person goes in vain. that is why i wanted to ask if i could work on it

**Comment by MLPJ** [comment]
I'm still working on the issue @AkshayCHD . So I think you better go for another issue then.

**Comment by MLPJ** [comment]
@srv-twry  @iamareebjamal please review the PR
