### ISSUE TITLE
Views with no data should be removed from ui

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#631]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

The views in organizer detail layout are visible but have no data in them

**Expected Behaviour**

The views with no data should be invisible

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

![screenshot_1517927743](https://user-images.githubusercontent.com/25455546/35865001-5b779fec-0b79-11e8-8694-3fc837a630e6.png)

**Would you like to work on the issue?**

yes

**Comment by srv-twry** [comment]
Duplicate #628
