### ISSUE TITLE
Add Event Statistics feature

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#633]
**Is it a ?**

- [x] Feature Request
    
- [ ] Bug Report

- [ ] Chore

**Parent issue** 
#618 

**Feature Description**

This is aimed at adding an option for the user to view the event statistics associated to an event.

   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal I'm getting `Co-organizer access is required` error response when I try to get event statistics of the event I created. This is weird, the organizer who created the event doesn't have Co-organizer access. Also who is the admin? Do i need to request role access from admin?

**Comment by iamareebjamal** [comment]
I think @shubham-padia can better answer this question

**Comment by shubham-padia** [comment]
@Masquerade0097 Can you paste the request payload and the response for me.

**Comment by Masquerade0097** [comment]
This is the GET request -
https://open-event-api.herokuapp.com/v1/events/699/general-statistics

Headers -
Accept : application/vnd.api+json
Authorization : JWT "token"

This is the response - 
`{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "Co-organizer access is required.",
            "status": 403,
            "source": {
                "source": ""
            },
            "title": "Access Forbidden"
        }
    ]
}`

**Comment by Masquerade0097** [comment]
Sorry, I think I was using token from another session maybe, I'm able to view the event stats now.
