### ISSUE TITLE
Using Server's Regex for Validation

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#634]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    

**Actual Behaviour**

The ValidationUtils are using a regex that is different from that used by server for validation. This regex filters out most of the invalid urls/emails but they are only a subset of all possible invalid inputs.

**Expected Behaviour**

These should be replaced by the regex used by server for validation.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Server uses marshmallow which uses a very complex regex. I can we can skip it. Also, I am currently working on open event core java library which will have inbuilt validation through `javax.validation` API
