### ISSUE TITLE
No empty check in quantity and price EditTexts

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-orga-app#640]
**Is it a ?**

- [X] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When we create a new ticket there is no empty check in price and quantity editTexts

**Expected Behaviour**

There should be an empty check just like it is being done in other editTexts

**Steps to reproduce it**

Open create new ticket, select paid.
Give a name and time, and leave the rest of the editTexts empty

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

**Comment by nikit19** [comment]
The reason why I thought they shouldn't be empty is because
if quantity is empty it automatically gets a value of 100
![screenshot_20180214-221236](https://user-images.githubusercontent.com/20878145/36216330-7bdd99f6-11d4-11e8-9ea4-9edeb73330e2.png)
and IMO if an event is paid there should be a price

**Comment by iamareebjamal** [comment]
If API does not restrict this, we cannot do anything. We are just implementors of app for the API, all logic is decided by the server guys, we cannot branch off from the default behaviour, you can discuss this in the gitter channel of opev server if you think this should be default behaviour. All in all, if they need to enforce that no free tickets can be made if event is paid, the API should reject the free ticket and not the app

**Comment by nikit19** [comment]
Okay,understood
