### ISSUE TITLE
Update Tests for Create Event Module

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#643]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [x] Chore
    

**Description**

The tests for Event Create Module does not cover the whole module. These should be updated.

**Would you like to work on the issue?**

Yes

**Comment by leeyh20** [comment]
@Masquerade0097 Are you still working on this?

**Comment by Masquerade0097** [comment]
@leeyh20  No, I'm not. You can work on it, if you like.

**Comment by leeyh20** [comment]
@Masquerade0097 Okay I shall try working on this!

**Comment by iamareebjamal** [comment]
@leeyh20 Status?

**Comment by leeyh20** [comment]
@iamareebjamal Really sorry for the delay! I'll finalize the PR by tomorrow.
