### ISSUE TITLE
Display Event CodeOfConduct in AboutEventFragment

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#644]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

**Actual Behaviour**

The event code of conduct is  not displayed anywhere

**Expected Behaviour**

The event code of conduct should be visible

**Would you like to work on the issue?**

Yes

**Comment by AkshayCHD** [comment]
@iamareebjamal where should i display this in AboutEventFragment

**Comment by Masquerade0097** [comment]
Duplicate #617
