### ISSUE TITLE
feat: Add Admin User Statistics

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#646]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
   

**Description**
There should be an option to view user admin statistics in the app.

**Parent**
#618

**Would you like to work on the issue?**
Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal I'm thinking to making a overflow menu in dashboard toolbar from which user can select to view admin statistics. The reason behind not using the same UI as event statistics is that dashboard is showing details related to a particular event whereas admin stats contains details for the user and his/her collective events. So Admin Statistics fragment after completion will contain Admin User, Mail, Event, Session stats. Is this fine?

**Comment by Masquerade0097** [comment]
@shubham-padia @iamareebjamal  Are the Admin Statistics for the server side admin or for this app?

**Comment by iamareebjamal** [comment]
@Masquerade0097 It can be delayed but is on scope of the app, however not immediately required

**Comment by Masquerade0097** [comment]
@iamareebjamal Ok, so should I implement it now?

**Comment by iamareebjamal** [comment]
Let's save this for later

**Comment by sridharjajoo** [comment]
@iamareebjamal Can I take up this issue and start working on it?

**Comment by iamareebjamal** [comment]
No, this is still not important. There are other issues which need attention
