### ISSUE TITLE
Add Event speakers list

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#647]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

There is no provision for the admin to see the speakers for his event
 
**Expected Behaviour**

There should be an option in the Navigation drawer for that 

**Would you like to work on the issue?**

Yes

**Comment by AkshayCHD** [comment]
@iamareebjamal should i go on with this

**Comment by iamareebjamal** [comment]
See my response at #648

**Comment by srv-twry** [comment]
**Parent issue**
#925

**Comment by AkshayCHD** [comment]
@srv-twry sorry didn't see your message initially, i am stuck in my semester exams as of now, so you can take this issue. I'll resume my work as soon as i get free.
