### ISSUE TITLE
Add Session in the app

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#648]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Description**

This is aimed at implementing all the functionalities related to session shown [here](https://open-event-api.herokuapp.com/#sessions-sessions-collection-post) in the API.

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Is this feature in scope of the app? If yes, then please provide the necessary details.

**Comment by iamareebjamal** [comment]
For sessions, tracks would also have to be implemented and more. This is in the original road map, and surely we will look forward to implementing it this summer, but for now let's focus on fixing current bugs and completing the missing functionality as this issue is a big undertaking

**Comment by iamareebjamal** [comment]
Yes that's most important

**Comment by Masquerade0097** [comment]
The issue is completed. Closing this.
