### ISSUE TITLE
Add config.gradle file for maintaining package version 

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-orga-app#659]
**Is it a ?**

- [ ] Bug Report

- [X] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

![image](https://user-images.githubusercontent.com/18497513/36631112-2a51485a-1998-11e8-9866-56da11cc9663.png)
Currently this is the way for maintaining version of different android packages

**Expected Behaviour**

This might look a bit clumsy in the future so how about creating a new file where all the information regarding version numbers can be stored.

**Would you like to work on the issue?**

Yes

**Comment by S2606** [comment]
@iamareebjamal Please do give your review on this.

**Comment by iamareebjamal** [comment]
Alright, please go ahead
