### ISSUE TITLE
Handle UnknownHostExceptionError in Login Screen

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-orga-app#660]
**Is it a ?**

- [X] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Currently nothing happens on handling this exception

**Expected Behaviour**

Show a snackbar regarding network error and retry option

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
What is the way to reproduce this bug
