### ISSUE TITLE
HTTP 500 Internal Server Error while signing up 

### ISSUE THREAD

**Issue by arundhati24** [fossasia/open-event-orga-app#679]
**Is it a ?**

  Bug Report
    
### Bug Report    

**Actual Behaviour**

Currently, the app displays a HTTP 500 Internal Server Error whenever a new user tries to sign up.

**Expected Behaviour**

The app shouldn't display this error. The user should be able to sign up on the server.

**Steps to reproduce it**

* Open the app
* Click on the Sign up link
* Fill in your credentials
* Click on the Sign Up button
An HTTP 500 Internal Server Error will be displayed.

**Screenshots of the issue**

![http_500](https://user-images.githubusercontent.com/30979369/36847182-7802a9b0-1d83-11e8-8dda-fcb6a88eec2a.jpg)

**Android version and Phone Model**

Device used [Xiaomi Redmi Note 4]
Android Version [Android 7.0]    

Also, the released version of the app on Google Playstore displays an HTTP 503 error while the user tries to sign up. A screenshot of the same is as follows : 

![http_503](https://user-images.githubusercontent.com/30979369/36847316-e93a707c-1d83-11e8-9b2e-17b1940432a6.jpg)

**Comment by iamareebjamal** [comment]
Not an issue of app, it's a server issue

**Comment by iamareebjamal** [comment]
The dev server may have temporary issues and the production API (api.eventyay.com) is down for a long time
