### ISSUE TITLE
Change default API URL to dev version

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#680]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [x] Chore

### Chore

**Description**

Change the default dev API link from https://open-event-api.herokuapp.com to https://open-event-api-dev.herokuapp.com

The development branch of open event server is now hosted on the second link and thus, all new features and bug fixes will be present there

**Comment by MLPJ** [comment]
@iamareebjamal  do you want to just change the constant BASE_URL?

**Comment by iamareebjamal** [comment]
Yes

**Comment by MLPJ** [comment]
can I do it?

**Comment by iamareebjamal** [comment]
Sure
