### ISSUE TITLE
Toolbar goes behind the status bar on login screen

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#681]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When typing in any field, the toolbar goes behind the status. 

**Expected Behaviour**

It should stay stuck at the top

**Steps to reproduce it**

Type in any text field in login screen

**Screenshots of the issue**

![screenshot-1519932995513](https://user-images.githubusercontent.com/3874064/36865625-0cdc1076-1db6-11e8-86f3-aea19df20eb1.jpg)

**Comment by MLPJ** [comment]
![image](https://user-images.githubusercontent.com/26664908/36869721-ba113b66-1dc2-11e8-8f5a-6cc73ea148e0.png)
@iamareebjamal  here I can't see the bug, is it android version specific?

**Comment by iamareebjamal** [comment]
Maybe depends on screen size

**Comment by brijeshshah13** [comment]
@iamareebjamal Can you please specify the Android device and version you were using when you faced the bug?

**Comment by iamareebjamal** [comment]
Marshamallow. Device doesn't matter, anything above lollipop should have same behaviour

**Comment by brijeshshah13** [comment]
@iamareebjamal I checked it on Motorola E3 power running 6.0 and Xiomi Redmi Note 4 running 7.0 and it worked fine on both.

**Comment by iamareebjamal** [comment]
Try to scroll the UI, or directly click on Base URL. The keyboard will push the UI under status bar

**Comment by sridharjajoo** [comment]
@iamareebjamal Can we set the fitSystemWindows to true in the root layout? This would solve the issue.

**Comment by brijeshshah13** [comment]
@sridharjajoo Yes, I'm sending PR for the same.
