### ISSUE TITLE
Settings fragment should be in backstack

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#682]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

When clicking back in settings section, the app shows toast to exit if back is pressed twice

**Expected Behaviour**

The settings fragment should be killed and app should return to the main screen on back press

**Comment by MLPJ** [comment]
@iamareebjamal  Can I work on this issue?

**Comment by iamareebjamal** [comment]
Yes, please go ahead

**Comment by Prashant-Chaurasia** [comment]
@iamareebjamal As the assigned person has not done any work and not sent any PR, therefore, I request you assign me this issue. Also, I would suggest that we should add backstack for every fragment call and pressing back button should lead to main screen, that is, dashboard. And from dashboard user can exit. I have already done the backstack part.

**Comment by iamareebjamal** [comment]
Please go ahead but every fragment to backstack is not a good strategy, it can lead to complicated and nested navigation. Each fragment already leads to dashboard when clicking back button except Setting

**Comment by Prashant-Chaurasia** [comment]
No, clicking back button in any fragment asks "Press again to exit". And again clicking the button lets exits out of the app.

**Comment by iamareebjamal** [comment]
OK, then implement it

**Comment by Prashant-Chaurasia** [comment]
@iamareebjamal Please review this PR.

**Comment by iamareebjamal** [comment]
The build is failing, please fix it first

**Comment by mishuvs** [comment]
Is work being done on this issue? Can I work?

**Comment by iamareebjamal** [comment]
Please go ahead @mishuvs
