### ISSUE TITLE
Sort currency list with priority

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#689]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore

### Feature Request

**Feature Description**

The currency list in event selection is huge and has no priority. It is hard to get the right currency selected. 
Proposed enhancements:
- [x] Sort the list with priority (Common currencies on top)
- [x] Select the default Locale's currency as default
- [ ] Add option to search (Auto Complete TextView)

**Comment by srv-twry** [comment]
I propose the same for the Timezone of the event in the Event creation Fragment. Should i create a similar issue for it also ?

**Comment by iamareebjamal** [comment]
That is already created and being worked upon

**Comment by AkshayCHD** [comment]
@iamareebjamal can i work on it

**Comment by iamareebjamal** [comment]
@AkshayCHD Please create a child issue for one of the 3 parts and work on that

**Comment by iamareebjamal** [comment]
@AkshayCHD Status?

**Comment by AkshayCHD** [comment]
@iamareebjamal In the third part do i have to remove the spinner and add auto complete textview instead

**Comment by iamareebjamal** [comment]
Let's not focus on the 3rd option right now.

**Comment by iamareebjamal** [comment]
Let's focus on other issues, they are more important
