### ISSUE TITLE
Remove Observable types from databinding methods

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#696]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

A lot of warnings are generated that Observable types should not be present in the parameters of binding methods and the support will be removed in the future

**Expected Behaviour**

Remove the observable types and reimplement the binding methods

**Comment by Masquerade0097** [comment]
This issue is already present #603.
