### ISSUE TITLE
Sort Currency list

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#698]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Currency list is in no particular order

**Expected Behaviour**

Currency list should be sorted

**Would you like to work on the issue?**

Yes

Parent issue #689

**Comment by AkshayCHD** [comment]
@iamareebjamal in my opinion sorting the list in alphabetical order is the best way

**Comment by iamareebjamal** [comment]
It should be sorted alphabetically with the special case specified in the parent issue
