### ISSUE TITLE
Two Loading Spinners on Pulled Refresh

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#70]
On __Dashboard Page__ and __Attendees Page__, two load spinners appear on pulled refresh.

Expected: Only load spinner of refresher should appear on pulled refresh

**Comment by betterclever** [comment]
I noticed that but couldn't find a way to make the refreshing spinner appear when page is loaded for the first time.

**Comment by mejariamol** [comment]
@betterclever You can hide a spinner under pulled refresh case.

**Comment by betterclever** [comment]
@mejariamol  Hmm. That can be done. So are you working on this or should I proceed?

**Comment by mejariamol** [comment]
@betterclever You can proceed. 👍

**Comment by mejariamol** [comment]
@betterclever the first time spinner never hides if no network. It keeps on showing after no network alert.
On pages:
* Dashboard Page
* Attendees Page

@niranjan94 please reopen the issue.

**Comment by betterclever** [comment]
@niranjan94 @mejariamol Working on this. 👍
