### ISSUE TITLE
Showing 'null' in Navigation View, if First Name not provided.

### ISSUE THREAD

**Issue by YashishDua** [fossasia/open-event-orga-app#700]
**Is it a ?**
- [x] Chore
    
### Chore

**Description**

Removing 'null' from Navigation View if First Name not provided

**Would you like to work on the issue?**

I would like to work on this issue.

**Comment by iamareebjamal** [comment]
The API does not enforce this restriction so we can't as well

**Comment by YashishDua** [comment]
Keeping Null Null is fine?

**Comment by iamareebjamal** [comment]
We can change the app behaviour where the name is not displayed if it null. Does that sound fine?

**Comment by YashishDua** [comment]
Okay, seems valid!
Should I take this issue?

**Comment by iamareebjamal** [comment]
Sure

**Comment by YashishDua** [comment]
Okay, I am on it!
