### ISSUE TITLE
Remove any one of the two progress bars

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#705]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When swiped down to refresh, two progress bars appear simultaneously (one from the SwipeRefreshLayout, and other from the "included" progressbar_layout.xml)

**Expected Behaviour**

Only one of the progress bars should be displayed as double progress bars make the UI look odd.

**Steps to reproduce it**

Swipe down to refresh

**Screenshot of the issue**

![doublerefresh](https://user-images.githubusercontent.com/35009811/36952872-20a4c2c4-203b-11e8-9264-e5255bb2f49d.png)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
The problem is that a view only has one showProgress contract and we want a pull to refresh progress indicator, but it does not look good when loading items. What do you propose

**Comment by mishuvs** [comment]
@iamareebjamal Can we use any of these?
   1. Use `setRefreshing(false)` in the `OnRefeshListener`'s `onRefresh()` method. This one seems to be a concise and better solution.
   2. Change the drawable via reflection (not sure about this one).
   3. We can use a 3rd party library for swipeToRefresh.

**Comment by iamareebjamal** [comment]
Still can't understand how any of these will solve both of these being triggered. Can you elaborate?

**Comment by mishuvs** [comment]
Yes. `SwipeRefreshLayout`'s `setRefreshing(false)` is used to tell the widget that the loading has finished i.e. to hide the ProgressBar. The SwipeRefreshLayout's progress bar will be hidden immediately after the refresh is triggered. But the other ProgressBar will keep behaving normally. 

This means that as you pull down, the small ProgressBar will be visible and move to show that fragment supports SwipeToRefresh. But once you swipe down fully and activate refresh, the smaller ProgressBar will be hidden immediately, and only the bigger (better looking) ProgressBar will be visible throughout the refresh.

* The gif: *
![refresh](https://user-images.githubusercontent.com/35009811/36985472-577f940e-20bd-11e8-97ef-9117d809f4c5.gif)

**Comment by iamareebjamal** [comment]
OK, sounds good. Looks good. What happens on a screen where there are no items?

**Comment by mishuvs** [comment]
I found out that in the current state of the app if we swipe down in case of no items, the spinner doesn't appear to move. This is also a UI glitch as the user then won't know that fragment supports SwipeToRefresh feature (in case of no items), unless they accidently swipe down.

Otherwise, it works same as described above in case of no items as well.

**Comment by iamareebjamal** [comment]
OK, please go ahead and implement this

**Comment by mishuvs** [comment]
Thanks! I'll send a PR right away.

**Comment by mishuvs** [comment]
@iamareebjamal Please review!

**Comment by sridharjajoo** [comment]
@iamareebjamal This issue is similar one but the multiple progress bar here are present in the dashboard.
