### ISSUE TITLE
Add Place Picker widget for the 'Create Event Form'

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#706]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
       
### Feature Request

**Feature Description**

Manually copying and pasting, or typing can be a bit tedious. User experience can be improved here. 
For the 'Create Event Form', options for Place Picker. Option for location detection using network service or GPS can also be added.
   
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@mishuvs I think as it is done in frontend, we used instead use Google Maps API to pick location instead of GPS.

**Comment by mishuvs** [comment]
@Masquerade0097 The PlacesAPI provides a much shorter way of integrating Google's services. MapsAPI will require us to first create a map fragment, set its properties and manually add the markers corresponding to your required locations on this Map object, some methods of PlacesAPI simplify your tasks to a great extent.

Using Maps API, we’ll have to fire queries to GooglePlacesAPI web service, get the JSON response and plot markers manually in the map. The PlacePicker method in PlacesAPI can do all this for us, without even needing to create a map object. PlacesAPI reduces complexity. Note that in Maps API, we'd still end up using the Places API Web Service(not the Android version) for getting response. 

Besides, I think that to be able to pick an address from the app is not a big task. I think it's better to use Places API for Android that **also includes Map implementation**, instead of indirectly getting information from web service, and displaying it using MapsAPI.

@iamareebjamal can you please help us decide?

**Comment by iamareebjamal** [comment]
Can you add the approximate extra size it'd require to add the library

**Comment by mishuvs** [comment]
Not sure, but from the apk analyzer: places api costs around 11KB (from one of my apps).
However, I think code complexity will still be less in Places API than in  Maps API.

**Comment by iamareebjamal** [comment]
Then go ahead please
