### ISSUE TITLE
Remove redundancy in case of date-time selection in the event creation form

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#707]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Both DatePicker-TimePicker and EditText field is shown. This makes up as a redundant part in the UI, and makes the form look bigger and complex.

**Expected Behaviour**

Only the Pickers should be shown, as they are more user-friendly.

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@mishuvs This is done because some users may find it time consuming to use the picker widget and search for the date. Insted they can just type in the appropiate date in EditText.

**Comment by mishuvs** [comment]
@Masquerade0097 @iamareebjamal Can we add a checkbox to show/hide the additional text field? This would make the form smaller and also keep the functionality at the same time.

**Comment by iamareebjamal** [comment]
Yes, we can do that
