### ISSUE TITLE
Correct FAB size and position

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#708]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

In some screens, 'add' Floating Action Buttons seems to be oddly positioned, squashed to the corner. 
As per the Material Design guidelines,"The floating action button should be placed 16dp minimum from the edge on mobile and 24dp minimum on tablet/desktop."

- [ ] In `event_create_layout.xml`, `marginBottom` for FAB is missing.
- [ ] In `ticket_create_layout`, distance from parent view edges is not same (might be the desired behaviour). `marginTop` is missing here.

**Expected Behaviour**

`marginBottom` attribute should be present in FAB in `event_create_layout.xml`
add `marginTop` attribute to `ticket_create_layout.xml`

**Screenshots of the issue**

![badui](https://user-images.githubusercontent.com/35009811/36954320-224455b6-2047-11e8-8e7a-17fd8db1e3ef.png)

![fab1](https://user-images.githubusercontent.com/35009811/37025966-1336c5d8-2153-11e8-9e4e-d8994cd8f79d.png)

![fab2](https://user-images.githubusercontent.com/35009811/37025976-17b6a844-2153-11e8-950e-da17fe8c7070.png)

**Android version and Phone Model**

Android version: 6.0.1; Phone model: Xiaomi Redmi 4A 
    
**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
FAB size is normal here

**Comment by mishuvs** [comment]
@iamareebjamal sir, thanks for correcting me. I confused with the `ticket_create_layout`'s `mini` size FAB. 
I have modified the issue and the title.

**Comment by iamareebjamal** [comment]
Can you please update the screenshot

**Comment by mishuvs** [comment]
I have added the new screenshot. Should we make the ticket FAB bigger? Presently, it's size is 'mini'.

**Comment by iamareebjamal** [comment]
Yes, we can but I can't see the new screenshot

**Comment by mishuvs** [comment]
Oh! sorry, I probably didn't hit update. My bad!
But I have updated now. Please check it, sir.

**Comment by iamareebjamal** [comment]
Umm, still same pic

**Comment by mishuvs** [comment]
Don't know why this is happening (Is there a max. limit for screenshots?). 
Nevertheless, updated again!

**Comment by iamareebjamal** [comment]
Yup, got it now. And no need to call me sir :smile:

**Comment by mishuvs** [comment]
you are senior :sweat_smile: 

Do you approve of the required changes?

**Comment by iamareebjamal** [comment]
Yes, please go ahead
