### ISSUE TITLE
Prevent 'Draft' label from getting truncated

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#715]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

The 'Draft' label is not being displayed correctly on some devices. It is getting truncated and making the UI look bad.

**Expected Behaviour**

It should be on one line, without truncation.

**Screenshot of the issue**

![badui](https://user-images.githubusercontent.com/35009811/36969372-4d746aac-208b-11e8-834f-c0182bb54188.png)

**Android version and Phone Model**

Android Version: 6.0.1; Phone Model: Xiaomi Redmi 4A

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
I'm not able to reproduce the issue. Can you please add the android version and phone model details?

**Comment by mishuvs** [comment]
Oops! I added them now. I think it probably depends on screen size.

**Comment by iamareebjamal** [comment]
Yes, I thought this would be the case. I think we can change the background color to light yellowish to show that the event is draft with a very small `save` icon on the right

**Comment by mishuvs** [comment]
Yes, that's a good idea! 
Currently, I am occupied with other issues. I will work on this once my work on those is done.
