### ISSUE TITLE
Event fragment should be in backstack

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#726]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When any of the fragments corresponding to a particular event is clicked, the app shows toast "Press again to exit"

**Expected Behaviour**

Since the fragments: 'Attendees', 'Tickets', 'About', 'FAQ' correspond to an event, the Event fragment should be on the back stack as per the hierarchy. And when the Events fragment is activated, all the property fragments should be removed from the drawer.

This means that pressing back button on the property fragments should be killed and Events fragment be attached. Also, other event-property options should be removed from the drawer.

Also note: When a user first logs in, events fragment is shown and the drawer doesn't contain options for the property fragments.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
> When a user first logs in, events fragment is shown and the drawer doesn't contain options for the property fragments.

When we don't know which event is selected, we can't show any property related to it

> This means that pressing back button on the property fragments should be killed and Events fragment be attached. 

We want the user to always remain in the context of an event. If he wants to change the event context, he may. But the only time it should be outside of event context, it should be the time when it first logs in

**Comment by mishuvs** [comment]
Got it! Closing issue.
