### ISSUE TITLE
Add option to delete FAQ

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#728]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Parent Issue**
#652 

**Description**

There should be an option in FAQ List Layout to delete an FAQ.

**Would you like to work on the issue?**

Yes

**Comment by mishuvs** [comment]
@Masquerade0097 Can I please take this issue?

**Comment by iamareebjamal** [comment]
@mishuvs This is being worked on currently
