### ISSUE TITLE
Implement Speaker Call Module features

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#731]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore

**Description**

The API supports Speakers Call create, list, update, delete operations. These should be implemented in the app followed by tests.

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal Where should I provide an option for that, in the drawer? I think sice it is an enhancement to Speakers therefore it should be in the overflow menu in Speakers list layout but Speakers isn't implemented yet so where should I implement it?

**Comment by iamareebjamal** [comment]
Yes, that's why we should leave it till speakers are implemented

**Comment by Masquerade0097** [comment]
This was supposed to be implemented after Speakers module right?

**Comment by iamareebjamal** [comment]
I will analyse the API and let you know

**Comment by Masquerade0097** [comment]
The API only has dependence on `event-id` for this module so I guess it can be implemented. What UI should be followed ?

**Comment by iamareebjamal** [comment]
Just like others

**Comment by Masquerade0097** [comment]
I am busy with Open-Event-Server project for now and will continue working after a week or so. Till then it is open to all.

**Comment by sridharjajoo** [comment]
@Masquerade0097 Are you working on it? If not I'll like to take this up.

**Comment by Masquerade0097** [comment]
@sridharjajoo Sorry, I am working on it.

**Comment by Masquerade0097** [comment]
This can be closed for now, as we are not showing this in the release version. Closing this.
