### ISSUE TITLE
Implement spinner for 'Payment Country', choose default, and auto-select 'Payment Currency' using it.

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#732]
**Is it a ?**

- [x] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Since we can automatically detect organizer's timezone and currency based on locale, we probably also can auto-fill payment country. Maybe we should make it a spinner, just like timezone and currency instead of a EditText field.

Also, in the present state, country name is not validated. Therefore, any random name can be filled. This qualifies it as a bug too.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
A spinner would be good. But constraining it to be same as with currency is not a good idea. What we can do is - The spinner for the country is at the top and currency is below and we set the currency when the country is picked but only once and not vice versa

**Comment by mishuvs** [comment]
I agree! Issue title changed.

**Comment by mishuvs** [comment]
@iamareebjamal Please open this issue as I want to send a PR.
