### ISSUE TITLE
Display event id in the ui

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#736]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

No information regarding the event id which might be very useful when accessing api endpoints.

**Expected Behaviour**

Event id should be made visible to the user

**Would you like to work on the issue?**

Yes

**Comment by AkshayCHD** [comment]
@iamareebjamal i think it is needed, what do you think.

**Comment by iamareebjamal** [comment]
No, that is not something users need to concern themselves with
