### ISSUE TITLE
feat: Allow updating the copyright

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#737]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Right now, the app supports Creating copyright for an Event. It should also support updating an existing Copyright for an Event.
   
**Would you like to work on the issue?**

Yes

**Parent issue**

#619

**Comment by iamareebjamal** [comment]
@srv-twry Status. Please comment so I may open it

**Comment by srv-twry** [comment]
@iamareebjamal Please open it now, I'm ready to send the PR.
