### ISSUE TITLE
feat: Allow deleting the copyright

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#738]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Right now the application supports creating Copyright for an Event. It should also support deleting the copyright.
   
**Would you like to work on the issue?**

Yes

**Parent issue**

#619 

To be done after #737

**Comment by iamareebjamal** [comment]
Please comment when ready

**Comment by srv-twry** [comment]
@iamareebjamal Please open this. Ready to send the PR

**Comment by srv-twry** [comment]
@iamareebjamal Please remove the ```unimplemented``` and ```waiting-for-status``` tags.
