### ISSUE TITLE
Ticket sale end date should be the event end date

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#740]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

The sale end date is set to be 10 days after the event

**Expected Behaviour**

The sale end date should be directly the end date of the event

**Would you like to work on the issue?**

yes

**Comment by AkshayCHD** [comment]
@iamareebjamal should i work on this, is it needed

**Comment by iamareebjamal** [comment]
It is set 10 days after the ticket sale start date. Please confirm. If not, please correct it in alignment to what the frontend does
