### ISSUE TITLE
test: Create tests for StringUtils

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#744]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
**Description**

Create unit tests for StringUtils class.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
@Masquerade0097 When not directly working on issues, please try to create a single parent issue with parts and when the implementation is done, branch that particular part with the issue

**Comment by Masquerade0097** [comment]
Ok, I'll take care of that from now onwards.
