### ISSUE TITLE
test: Write tests for all the Presenters

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#745]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

There are a lot of presenters which don't have Unit tests.

- [x] AboutEventPresenter(#739)
- [x] TicketDetailPresenter(#741)
- [ ] ChartPresenter
- [x] OrganiserDetailPresenter(#742)

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@srv-twry Since this is the parent issue therefore please add Organizer Detail Presenter (#742) in the list. Also, You have added TicketDetailPresenter twice. Please remove one of them.

**Comment by iamareebjamal** [comment]
Since ChartsPresenter is not yet in use, we'll skip this
