### ISSUE TITLE
Profile Activity shows null null if First Name not provided

### ISSUE THREAD

**Issue by YashishDua** [fossasia/open-event-orga-app#747]
- [x] Bug
    
### Bug

**Description**

Profile Activity action bar title contains 'null null' if the first name is not provided by the user.

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by iamareebjamal** [comment]
This is not chore, it's bug

**Comment by YashishDua** [comment]
Corrected. Should I start working?

**Comment by iamareebjamal** [comment]
Sure
