### ISSUE TITLE
FAB present in FAQ Activity not follows Google Design Margin guidelines

### ISSUE THREAD

**Issue by YashishDua** [fossasia/open-event-orga-app#748]
- [x] Chore
    
### Chore

**Description**

FAB should be anchored with fab margins ( given by Google Design )

![screenshot_2018-03-08-22-37-58-1625209755](https://user-images.githubusercontent.com/20666950/37164882-6e9249be-2321-11e8-9368-93fb2da7eb5d.png)

**Would you like to work on the issue?**

Yes, I would like to fix this issue.

**Comment by iamareebjamal** [comment]
Which FAB, please provide more context with screenshots

**Comment by YashishDua** [comment]
Added.
Same is in FAQ and Events Activity.

**Comment by YashishDua** [comment]
Should I work on this issue?

**Comment by iamareebjamal** [comment]
Yes

**Comment by YashishDua** [comment]
@iamareebjamal Anything missing?

**Comment by iamareebjamal** [comment]
Your PR contains stale commits

**Comment by YashishDua** [comment]
What do you mean by stale commits?

**Comment by iamareebjamal** [comment]
Commits irrelevant to PR which have already been merged

**Comment by YashishDua** [comment]
How to remove that? I am not able to do it.

**Comment by iamareebjamal** [comment]
Rebase from development branch and add the correct commit to an appropriate feature branch

**Comment by YashishDua** [comment]
Let me know if they are removed or not.

**Comment by iamareebjamal** [comment]
Still same, you can see that for yourself
https://github.com/fossasia/open-event-orga-app/pull/767/files 3 files  
https://github.com/fossasia/open-event-orga-app/pull/767/commits 9 commits

**Comment by YashishDua** [comment]
How to remove previous commits that are already pushed?

**Comment by iamareebjamal** [comment]
> Rebase from development branch and add the correct commit to an appropriate feature branch

**Comment by iamareebjamal** [comment]
@YashishDua Status?
