### ISSUE TITLE
Remove "LogIn" from Action Bar title 

### ISSUE THREAD

**Issue by YashishDua** [fossasia/open-event-orga-app#749]
- [x] Feature Request
    
### Feature Request

**Feature Description**

In the Login Activity, instead of showing 'Log In' in action bar title which is very obvious looking at the screen, we can remove the action bar and display a designed textview with "Open Event Orga App from Fossasia".

**Comment by iamareebjamal** [comment]
The `Log In` provides context as do the other fragments like `Forgot Password` and `Sign Up`

**Comment by YashishDua** [comment]
Landing page of application should atleast reveal it's an event management app.

**Comment by YashishDua** [comment]
Should I work towards making landing page project it's an event management app?
@iamareebjamal

**Comment by iamareebjamal** [comment]
Yes
