### ISSUE TITLE
Clicking about option intents to activity, should attach fragment

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#751]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Use fragment when the 'About' option clicked instead of activity, just like is done for other event properties.

**Would you like to work on the issue?**

Yes

**Comment by mishuvs** [comment]
@iamareebjamal Should I work on this?

**Comment by iamareebjamal** [comment]
Yes
