### ISSUE TITLE
test: Create tests for ChartPresenter

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#760]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [ ] Chore

Create unit tests for ChartPresenter (Parent issue: #745 )
    
**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
ChartPresenter is not working correctly right now

**Comment by mishuvs** [comment]
@iamareebjamal Can I write any other test?

**Comment by iamareebjamal** [comment]
@mishuvs There are plenty of open issues for tests, contact the OP and ask if they are working on something, and if they are not, take it up

**Comment by mishuvs** [comment]
Thanks! "the OP"?

**Comment by iamareebjamal** [comment]
Original Poster
