### ISSUE TITLE
Remove confirmation before exit

### ISSUE THREAD

**Issue by arundhati24** [fossasia/open-event-orga-app#761]
**Actual Behaviour**

Currently, the app displays a toast to prompt the user, in case the user hits the back button.

**Expected Behaviour**

The app should not display any toast or dialog to confirm exit, unless there is some task running in the background (say, download), as this breaks user experience. Moreover, none of the standard apps implement this.

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Confirmation before exit is pretty standard for apps which have muti-level navigation within the application and it is quite annoying to be led out of the app when just clicking back to get to the main screen. Sometimes people don't know they are on home screen and just click back couple of times

The apps which don't implement this feature are pretty optimized with initial loading in milliseconds and we load quite a bit of information on initial load.

**Comment by arundhati24** [comment]
@iamareebjamal Please have a look at the recent conversation in fossasia/susi_android on Gitter where @mariobehling agreed upon removing this from all android apps. :)

**Comment by iamareebjamal** [comment]
Alright, go ahead, but as mentioned in the issue, enforce the rule if something is going on in background
