### ISSUE TITLE
Event list doesn't update automatically after event creation

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#778]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Event list doesn't update automatically after event creation.

**Expected Behaviour**

Should refresh immediately after event creation.

**Gif of the issue**

![eventrefresh](https://user-images.githubusercontent.com/35009811/37318493-d8e4c2de-2690-11e8-9cf4-e28c054277ac.gif)

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
Duplicate #690.
