### ISSUE TITLE
Error 404 found on selecting About from nav bar

### ISSUE THREAD

**Issue by S2606** [fossasia/open-event-orga-app#780]
**Is it a ?**

- [X] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

After creating event, on selecting about from nav drawer, 404 is being shown on the logs

![image](https://user-images.githubusercontent.com/18497513/37448935-684eeb66-284e-11e8-8695-78f4a1f0996e.png)

**Expected Behaviour**

No error

**Steps to reproduce it**

Create a event 
Select about from nav drawer

**Would you like to work on the issue?**

Yes

**Comment by S2606** [comment]
@iamareebjamal Please review

**Comment by iamareebjamal** [comment]
Not an issue. Copyright isn't present so 404 will be thrown obviously
