### ISSUE TITLE
Toolbar title reduces on screen rotation

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#789]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**
On screen rotation the title of the toolbar reduces in size.

**Expected Behaviour**
It shouldn't reduce.

**Would you like to work on the issue?**
Yes!

**Comment by iamareebjamal** [comment]
This was already discussed in other apps and is a default behaviour of Support Lib

**Comment by sridharjajoo** [comment]
@iamareebjamal Should I close this issue or can I submit a path for it?
