### ISSUE TITLE
Adding shared element transition to profile

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#790]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**
I would like to add a shared element transition to the profile picture when it is selected.

**Would you like to work on the issue?**
Yes!

**Comment by iamareebjamal** [comment]
Please ping when implemented and sent a PR, I'll open the issue. Also, I have seen that you too have claimed a lot of issues, please only pick issues which you can solve within 3-4 days. This keeps issue tracker clean. You can maintain a list of issues locally or discuss on gitter about a potential issue

**Comment by sridharjajoo** [comment]
@iamareebjamal Sure .I'll follow it from now onwards
