### ISSUE TITLE
Improve the UI of FAQ section

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#791]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    

### Feature Request

**Feature Description**
Currently the UI of FAQ section is quite plain .I would like to add cardviews for each set of question and answers and make it more appealing.

**Would you like to work on the issue?**
Yes!

**Comment by sridharjajoo** [comment]
@iamareebjamal I want to work on this issue.

**Comment by iamareebjamal** [comment]
Please go ahead

**Comment by sridharjajoo** [comment]
@iamareebjamal I'll submit a P.R for this till tomorrow.

**Comment by iamareebjamal** [comment]
No need to close this

**Comment by sridharjajoo** [comment]
@iamareebjamal Should I implement this type of UI ?
![preview](https://user-images.githubusercontent.com/20684618/37815946-0a8c69fa-2e97-11e8-9aee-be56458eb8bb.gif)

**Comment by sridharjajoo** [comment]
@iamareebjamal I need just a small suggestion. Suppose any question is open (as shown in the above gif) and at the same time we open other question should the previous question be closed or should it remain open?

**Comment by iamareebjamal** [comment]
Remain open

**Comment by sridharjajoo** [comment]
@iamareebjamal Is this fine? Kindly suggest any changes.



![open_event](https://user-images.githubusercontent.com/20684618/37930388-416e0714-3160-11e8-8694-877c8df6321f.gif)
