### ISSUE TITLE
Implement sorting in tickets list

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#792]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

No custom sorting feature is avaliable in tickets activity

**Expected Behaviour**

Custom sorting feature should be there in tickets list

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
Not a priority right now, can it be closed? @iamareebjamal
