### ISSUE TITLE
Login Button Color

### ISSUE THREAD

**Issue by YashishDua** [fossasia/open-event-orga-app#794]
**Is it a ?**

- [x] Feature Request
    
### Feature Request

**Feature Description**

Log In button color should be same a sign-up color i.e ( shade of green )

![screenshot_2018-03-19-21-47-27-1467687999](https://user-images.githubusercontent.com/20666950/37608566-e8d681fc-2bc0-11e8-9795-71329829568b.png)
![screenshot_2018-03-19-21-47-32-1152599258](https://user-images.githubusercontent.com/20666950/37608567-e923c03e-2bc0-11e8-9e19-f0a77f299d1f.png)

**Comment by iamareebjamal** [comment]
We have deliberately made it so
