### ISSUE TITLE
Ticket UI

### ISSUE THREAD

**Issue by YashishDua** [fossasia/open-event-orga-app#795]
**Is it a ?**
 
- [x] Feature
   
### Feature

**Description**

Date and Time should be presented primarily. UI must be modified accordingly.

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by iamareebjamal** [comment]
Can't understand the issue. Please explain the issues properly in description

**Comment by FladaDevs** [comment]
In Ticket User Interface, all sort of information is having some text properties. Time and date which are most important are not able to look primarily. We need to make changes in UI so that date and time could be seen easily.

**Comment by iamareebjamal** [comment]
Not sure how time and date are the most important for ticket.

**Comment by FladaDevs** [comment]
I guess an attendee will open the ticket only to see its time and date.

**Comment by iamareebjamal** [comment]
Yeah that's what I am not sure of. This app is not for attendees and nevertheless you don't buy a ticke to look at the date

**Comment by FladaDevs** [comment]
Sorry, I meant organizer will open the ticket to see some major details. Even if it's not date and time, at least we could separate and color code things to make them at least presentable.

**Comment by YashishDua** [comment]
I used my another account to comment here, by mistake! ignore that,

**Comment by iamareebjamal** [comment]
Please add a mock UI for what you are proposing

**Comment by YashishDua** [comment]
Okay, I'll add some mockups in few hours.
