### ISSUE TITLE
Adding Confirm Password in SignUp

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#797]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**
There should be a confirm password screen in the sign up section of the app

**Description**
Currently there is no confirm password section.After a password is entered , there should be a confirm password edit text as well to check whether both of them match.

**Would you like to work on the issue?**
Yes

**Comment by sridharjajoo** [comment]
@iamareebjamal I want to work on this issue

**Comment by iamareebjamal** [comment]
Please go ahead
