### ISSUE TITLE
Not able to perform unit tests from command line

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#800]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**
If trying to perform unit tests from command line (./gradlew test , ./gradlew check etc.) an error get thrown up that 

FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '9.0.1'.

**Steps to reproduce it**
perform the ./gradlew test from cmd.

@iamareebjamal 
I think this is because the distributionUrl is distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip and the gradle version is 3.0.1 . In my opinion I need to downgrade the distributionUrl to 
**gradle-3.3-all.zip**.
Should I go forward with it?

**Would you like to work on the issue?**
Yes!

**Comment by Masquerade0097** [comment]
Please run `./gradlew androidCheck` in terminal instead.

**Comment by sridharjajoo** [comment]
@Masquerade0097 No , it doesn't work

**Comment by iamareebjamal** [comment]
Are you using Java 9?

**Comment by sridharjajoo** [comment]
@iamareebjamal Yes!
