### ISSUE TITLE
UsePicker (date and time) checkbox in Create Ticket fragment.

### ISSUE THREAD

**Issue by Prashant-Chaurasia** [fossasia/open-event-orga-app#801]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**
In the create ticket fragment there should be a usepicker checkbox which on clicking will enable date/time picker as is the case in the create event page. As of now create ticket displays both the picker as well as in the text format.
   
### Screenshots

**Create Event**
![screenshot_20180320-123528](https://user-images.githubusercontent.com/19494189/37640810-3b5f2a74-2c3d-11e8-9404-7eb878b9399c.png)

**Create Tickets**
![screenshot_20180320-123542](https://user-images.githubusercontent.com/19494189/37640814-415b3d0a-2c3d-11e8-8d58-3b6616b0e96f.png)

**Would you like to work on the issue?**
Yes

**Comment by AkshayCHD** [comment]
@Prashant-Chaurasia are you still working on it or shall i take it up.

**Comment by iamareebjamal** [comment]
@AkshayCHD Please go ahead

**Comment by Prashant-Chaurasia** [comment]
@iamareebjamal I was waiting for your confirmation, that's why I didn't work on this.

**Comment by AkshayCHD** [comment]
@Prashant-Chaurasia No worries, if you want to implement it please go ahead.

**Comment by yatri1609** [comment]
@iamareebjamal  I would like to work on this, but will be able to do it after 30th April reason being I have my end-semester presentations. I hope it is fine. Thanks

**Comment by yatri1609** [comment]
@Prashant-Chaurasia , you can work on this if you want as I won't be able to do it till mid of this month.
