### ISSUE TITLE
Blurry placeholder image in Profile

### ISSUE THREAD

**Issue by SahanMonaara** [fossasia/open-event-orga-app#802]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

I would like to add a good placeholder for profile image in OrganizerDetailedActivity and the Organizer can change the image when they want.

**Screenshots of the issue**
![screenshot_2018-03-20-13-37-07](https://user-images.githubusercontent.com/23328262/37642746-56072e92-2c44-11e8-82ee-86b0bf93b9f8.png)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Please elaborate the issue

Profile Image and placeholder already exist in Profile Section
![screenshot-1521534251333](https://user-images.githubusercontent.com/3874064/37643363-420f2fb4-2c46-11e8-8b8e-ff613daa8a84.jpg)

**Comment by SahanMonaara** [comment]
For some phones the place holder is blured. and can't change the profile picture by the organizer.

**Comment by iamareebjamal** [comment]
OK, please split the issue into 2

**Comment by SahanMonaara** [comment]
- [ ] Changing The Profile Place Holder

- [ ] Enabling Change Profile Picture For The User

**Comment by iamareebjamal** [comment]
Please create a new issue for second part is what I meant by splitting

**Comment by SahanMonaara** [comment]
Okay

**Comment by ahsan44411** [comment]
You still working on this @SahanMonaara ?
