### ISSUE TITLE
Multiple progress bar appearing on refreshing

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#806]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**
While refreshing the profile of the organizer multiple progress bars can be seen.

**Expected Behaviour**
Single progress bar (circle) should be shown.

**Screenshots of the issue**
![whatsapp image 2018-03-21 at 20 21 16](https://user-images.githubusercontent.com/20684618/37716845-792b3ee8-2d45-11e8-9716-4d6a48ba0e04.jpeg)

**Would you like to work on the issue?**
Yes!

**Comment by sridharjajoo** [comment]
@iamareebjamal I would like to work on this issue.

**Comment by iamareebjamal** [comment]
There was an issue similar to this. Please find that and mention me, I'll open it
