### ISSUE TITLE
Sign up not possible.

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/open-event-orga-app#807]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Not able to sign up for the app in Moto G5 even with a good internet connection. 

**Expected Behaviour**

When creating a new account, the app should allow the user to sign in to the app.

**Screenshots of the issue**

![screenshot_20180322-111727](https://user-images.githubusercontent.com/18664195/37753580-986bce5c-2dc3-11e8-937c-facbc6444e6a.png)

**Android version and Phone Model**

Android Version 7.1 MotoG5
    

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by iamareebjamal** [comment]
You are not using the version from development branch. The base URL of the project has changed. eventyay doesn't work anymore
