### ISSUE TITLE
Able to edit all the fields while processing signup 

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/open-event-orga-app#808]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

When sign up process is taking place, I could easily type in where the cursor was and change that field. Any user would be confused if that happened.

**Expected Behaviour**

The activity should be frozen while signup and only a loader should be shown.

**Steps to reproduce it**

The screen should be frozen. 

**Screenshots of the issue**

![screenshot_20180322-114238](https://user-images.githubusercontent.com/18664195/37754269-d7006850-2dc6-11e8-863f-d1563a2392bd.jpg)

**Android version and Phone Model**

Android 7.1 Moto G5 
    

**Would you like to work on the issue?**

Yes, I would like to work on the app.

**Comment by iamareebjamal** [comment]
It's already disabled when signing in

**Comment by DhruvamSharma** [comment]
Thank you :D
