### ISSUE TITLE
Too many colors on create event activity

### ISSUE THREAD

**Issue by DhruvamSharma** [fossasia/open-event-orga-app#811]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

In the create form activity, the app has multiple colours thus disturbing the UX of the app. 

Please state here what is currently happening.

The colour of start date and end date of an event should be preference_color rather than purple and red. 

State here what the feature should enable the user to do.

Change colour from red and purple to blue in the colours XML 

**Screenshots of the issue**

OLD ONE: 
![screenshot_20180322-190442](https://user-images.githubusercontent.com/18664195/37773698-49df44e4-2e04-11e8-89f9-e6c961172b26.png)

NEW ONE: 
![screenshot_20180322-190242](https://user-images.githubusercontent.com/18664195/37773709-54098ba0-2e04-11e8-91f4-c5e538871a35.png)

**Android version and Phone Model**

Android 7.0 Moto G5
    
### Feature Request

**Feature Description**

The colours break the UX of the app. 

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

**Comment by iamareebjamal** [comment]
This is by design to show color and time in different colors, and is not only present in event create form. Also I'll recommend you wait for approval before implementing issues and sending PRs

You can propose better UI definitely, but after discussions and approval you may implement them
