### ISSUE TITLE
Page load time for Attendees List Page

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#82]
Currently it takes more time to load attendees list page in case of large attendees.
**For now** we can try generating only list view items which fit in the viewport from the loaded attendees list on scroll. Will check if it decreases page loading time.
I will work on this.

**Comment by mejariamol** [comment]
@niranjan94 What do you think possible reason behind page loading time issue

- the whole grouping and sorting process on attendees list  
**OR**

- is it just populating views into the page taking time ??

**Comment by niranjan94** [comment]
@mejariamol 

I'd say this 
> the whole grouping and sorting process on attendees list

And also, there's obviously the time taken to load the data from the server too.

**Comment by mejariamol** [comment]
@niranjan94 then our server api should return sorted data. We can do that right.. since SQLAlchemy provides `order_by` .
Shall I create issue for server api to return sorted data in required calls ??

**Comment by niranjan94** [comment]
@mejariamol no. Don't create any server issues for API yet. The entire API is going to get a make over to make it compliant with json-api. So when that happens, we'll get the sorting functionality we need.

**Comment by iamareebjamal** [comment]
I think this can be closed now @mejariamol @niranjan94 ?

**Comment by mejariamol** [comment]
Yeah sure. Closing this as attendees page is much faster now.
