### ISSUE TITLE
Add separate issue templates

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#821]
Current issue template has checkboxes which overshadow github's checklist feature

Github now supports separate issue templates for various occasions. Split the current issue template into 3 parts - bug, feature, and chore

Add 3 corresponding buttons to README in create an issue section where a user can be redirected to new issue template respectively

**Comment by nikit19** [comment]
I would like to work on this issue

**Comment by iamareebjamal** [comment]
Please go ahead
