### ISSUE TITLE
Add documentation about contribution and finding issues

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#822]
Add documentation on how to contribute by finding issues

The first step should be to check `core` tags, and `high-priority` ones

Then `unimplemented` issues should be checked which got closed due to lack of attention but still need to be implemented.

Then `deferred` issues may be valid now to take up

If no such criteria meets, only then move on to create new issues during an issue hunt. Of course issues about serious bugs and new ideas about features are always welcome.

Above paragraph is a gist of what is to be communicated

**Comment by sridharjajoo** [comment]
@iamareebjamal We could move the **Contributions Best practices**  from the Readme.md to Contributions.md .I have written the **Issue process** as you have said above and "Pull request process" as well. We can add these 2 sections to the Contributing.md as well.

**Comment by iamareebjamal** [comment]
OK. Send the PR after you've completed the previously assigned ones

**Comment by sridharjajoo** [comment]
@iamareebjamal Can I submit a P.R for this as I haven't been able to test the app for event changes (because of 422 error)?

**Comment by iamareebjamal** [comment]
Yes
