### ISSUE TITLE
Add event Feedback

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#824]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

No option to view feedbacks for the event

**Expected Behaviour**

Event feedbacks should be made visible to the user

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
Wasn't this issue already created?

**Comment by AkshayCHD** [comment]
@iamareebjamal Ithought that the issue was closed because there was no response for some time, i have a PR Ready for this and have worked alot on it so i was hoping i could make a new issue and make a pr on that

**Comment by iamareebjamal** [comment]
Closed issues can be reopened, you know

**Comment by iamareebjamal** [comment]
Send the PR and I'll open that. Link to the previous issue and not the new one
