### ISSUE TITLE
Convert orga app to Native android app

### ISSUE THREAD

**Issue by Rishabhk07** [fossasia/open-event-orga-app#83]
Hey i started converting orga app into native android app, here is the initial demo, all the functionality of the current orga app is present in it, here is the  demo [link](https://youtu.be/IrruuJz2k0g) & the repo of the app is [here](https://github.com/Rishabhk07/FossAsia-open-event-orga-android)

![rsz_screenshot_20170428-163743](https://cloud.githubusercontent.com/assets/8939938/25526747/a33f743e-2c32-11e7-8caa-285bd609d32f.png)

![rsz_screenshot_20170428-163800](https://cloud.githubusercontent.com/assets/8939938/25526761/b15c069a-2c32-11e7-8dbe-664ea6104e75.png)

![rsz_1screenshot_20170428-163804](https://cloud.githubusercontent.com/assets/8939938/25526735/9514533e-2c32-11e7-8130-24e059d32338.png)

![rsz_screenshot_20170428-164034](https://cloud.githubusercontent.com/assets/8939938/25526783/d3109c92-2c32-11e7-854b-9b9d7ff0e269.png)

![rsz_screenshot_20170428-164047](https://cloud.githubusercontent.com/assets/8939938/25526793/de2f01c2-2c32-11e7-8d03-0d40621db183.png)

**Comment by Rishabhk07** [comment]
@niranjan94 @mariobehling what do you think about it ?

**Comment by niranjan94** [comment]
@Rishabhk07 Hi ... That's a nice app. But the organizer app was decided to be a cross-platform app so that we can support multiple platforms (like the [eventbrite organizer app](https://www.eventbrite.com/l/Organizer-check-in-app/) with a single code-base). 

So, it would be great if you could look through the issues here on this repository and add some more cool feature to this app. 😄

**Comment by niranjan94** [comment]
also @Rishabhk07 be sure to join the Gitter channel at https://gitter.im/fossasia/open-event-orga-app so that you don't miss any discussions.

**Comment by Rishabhk07** [comment]
@niranjan94 Thanks, cool will be solving issues on this repository. ya i am already on the gitter channel. thanks :)
