### ISSUE TITLE
fix: Remove static copyright field from the Update Copyright Fragment

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#852]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [x] Chore
    
### Chore

**Description**

There is a static copyright field inside the Update Copyright Fragment. It needs to be removed. 
Moreover the following lines are unnecessary
``` Java
final Context contextThemeWrapper = new ContextThemeWrapper(getActivity(), R.style.AppTheme);
LayoutInflater localInflater = inflater.cloneInContext(contextThemeWrapper);
```

**Would you like to work on the issue?**

Yes

**Comment by srv-twry** [comment]
@iamareebjamal How would you suggest resolving the problem ? 
I need to pass the copyright variable to the new instance of the ```UpdateCopyrightFragment```. I think it can be passed as a bundle but that would need me to implement ```Parceable``` or ```Serializable``` interface on the Copyright class. 
Should i implement Parceable or Serializable or any other approach ?

**Comment by iamareebjamal** [comment]
Just pass the id and have the presenter load it from the db
