### ISSUE TITLE
Change TicketDetailPresenterTest package name

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#858]
**Is it a ?**

- [ ] Bug Report

- [ ] Feature Request
    
- [x] Chore

### Chore

**Description**

Change `openticket` to `openevent`

**Would you like to work on the issue?**

No

**Comment by sridharjajoo** [comment]
Can I send a P.R?

**Comment by iamareebjamal** [comment]
yes
