### ISSUE TITLE
No translucent status bar in About Event Activity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#883]
### Bug Report    

**Actual Behaviour**

The translucent status bar from About Event Activity is gone

**Expected Behaviour**

About Event Activity should have translucent status bar as it was in previous versions

**Would you like to work on the issue?**

No

**Comment by AkshayCHD** [comment]
@iamareebjamal shall I take this up or is this issue made for new contributors.

**Comment by iamareebjamal** [comment]
Please go ahead
