### ISSUE TITLE
Pressing back on create/edit copyright exits activity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#884]
### Bug Report    

**Actual Behaviour**

When pressing back either via soft or hard button, the about event activity is finished.

**Expected Behaviour**

The fragment should be popped from backstack instead.

**Would you like to work on the issue?**

No

**Comment by mishuvs** [comment]
@iamareebjamal Can I take this up?

**Comment by iamareebjamal** [comment]
Go ahead
