### ISSUE TITLE
Pressing back on edit organizer details exits activity

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#885]
### Bug Report    

**Actual Behaviour**

When pressing back either via soft or hard button, the about event organizer is finished.

**Expected Behaviour**

The fragment should be popped from backstack instead.

**Would you like to work on the issue?**

No

**Comment by gautamjajoo** [comment]
@iamareebjamal I would like to take it

**Comment by sridharjajoo** [comment]
@iamareebjamal I would like to take it

**Comment by iamareebjamal** [comment]
Go on
