### ISSUE TITLE
Refactor Main Presenter into separate components

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#888]
### Chore

There are many functionalities in Main Presenter which can be encapsulated in separate modules and hence reduce the responsibilities of it by distributing them

**Comment by yatri1609** [comment]
Hey, I am new to this so @iamareebjamal  can you please guide me a bit through this? Also, can you suggest some first-timer issues which I can do? Thanks.

**Comment by iamareebjamal** [comment]
@yatri1609 Look at #681 #894 #801 #603 #589
