### ISSUE TITLE
Dashboard overrides Fragments on screen rotation

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#894]
### Bug Report    

**Actual Behaviour**

Almost all the Fragments are overridden by the dashboard on Screen rotation. They include

- [ ] Attendees
- [ ] Tickets
- [ ] Feedbacks
- [ ] FAQ
- [ ] Tracks

**Expected Behaviour**

They shouldn't close.

**Steps to reproduce it**

Open any one of the mentioned fragments and rotate the screen

**LogCat for the issue**

N/A

**Screenshots of the issue**

![videotogif_2018 04 13_20 14 14](https://user-images.githubusercontent.com/21277837/38741422-86dca170-3f57-11e8-878a-95e572364cc6.gif)

**Android version and Phone Model**

Android 5.1.1 Oppo f1

**Would you like to work on the issue?**

No as i already have some assigned issues.

**Parent issue**
#1011

**Comment by srv-twry** [comment]
@sridharjajoo @mishuvs @AkshayCHD @Prashant-Chaurasia 
Feel free to take this one up if you want :smile:

**Comment by sridharjajoo** [comment]
@iamareebjamal I tried using setRetainInstance(true) in the fragments but still the dashboard overrides the fragments on screen rotation.

**Comment by iamareebjamal** [comment]
We don't want to use `setRetainInstance(true)` 

Look at my comment above regarding why is this happening. Has nothing to do with retaining fragments, activity gets recreated nevertheless

**Comment by srv-twry** [comment]
@iamareebjamal Since we have moved away from the loader based presenters, what are our options here in order to solve this ?

1. We can store the `attachCount` in the bundle using `onSaveInstanceState`, provide it to the presenter when it is attached to the fragment and not open the dashboard when the attachCount > 1.

2. Migrate the Main Activity to MVVM. I think it will automatically solve this issue. I am in favour of this although it will take some time but it is already in our plans. 

Which approach out of these two or any other looks favourable to you ?

**Comment by iamareebjamal** [comment]
I'd say, main presenter is huge, in small PRs, take chunks of its responsibilities in separate VMs rather than converting it in one go

**Comment by iamareebjamal** [comment]
@srv-twry I guess this is solved now?
