### ISSUE TITLE
Add option to delete feedback

### ISSUE THREAD

**Issue by AkshayCHD** [fossasia/open-event-orga-app#899]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Currently the user cannot delete inappropriate feedbacks

**Expected Behaviour**

User should be allowed to delete feedbacks

**Would you like to work on the issue?**

Yes

**Parent Issue**

#672

**Comment by iamareebjamal** [comment]
Link parent issue

**Comment by AkshayCHD** [comment]
@iamareebjamal I am unable to delete feedbacks through the endpoint http://open-event-api-dev.herokuapp.com/v1/feedbacks/4 , I think this is also because the api is undergoing some changes, i would start working on the issue as soon as the problem is solved.

**Comment by AkshayCHD** [comment]
@iamareebjamal the issue regarding this has been solved in open-event-server but as per the current functionality of the server, the user who created the feedback, only he can delete it. Not the event organizer, should i look upon how to solve this problem or should it be this way only.

**Comment by iamareebjamal** [comment]
I think @shubham-padia @SaptakS will be better able to answer this question

**Comment by Masquerade0097** [comment]
@AkshayCHD Can i take this up ?

**Comment by AkshayCHD** [comment]
@Masquerade0097 I am a somewhat occupied in my internship currently, so please fell free to take this up.

**Comment by Masquerade0097** [comment]
Can be closed since it is out of roadmap.
