### ISSUE TITLE
Implement Tests for Tracks 

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#909]
### Chore

**Description**
Currently no tests have been added for the recently implemented CreateTrackPresenter, TracksPresenter and FeedbackListPresenter.

**Would you like to work on the issue?**
Yes!

@iamareebjamal I would like to work on this!

**Parent Issue**
#870

**Comment by srv-twry** [comment]
@sridharjajoo I am implementing the Tracks module and would be writing the tests for those presenters after i am done with implementing the features first. 
Similary i think you can also leave FeedbackListPresenter as well or atleast ask it from the issue creator.

**Comment by srv-twry** [comment]
Moreover, please use the direct issue templates from the README file instead of the common issue template

**Comment by iamareebjamal** [comment]
Please split in 2 issues

**Comment by srv-twry** [comment]
Please link the parent issue as well.

**Comment by sridharjajoo** [comment]
@srv-twry I have created a test shouldShowSuccessOnCreated() and inside it is 

    public void shouldShowSuccessOnCreated() {

        Track track = createTrackPresenter.getTrack();
        when(trackRepository.createTrack(track)).thenReturn(Observable.just(track));

        createTrackPresenter.createTrack();

        InOrder inorder = Mockito.inOrder(createTrackView);

        inorder.verify(createTrackView).showProgress(true);
        inorder.verify(createTrackView).onSuccess(anyString());
        inorder.verify(createTrackView).dismiss();
        inorder.verify(createTrackView).showProgress(false);
    }

This is giving a null pointer exception at  `createTrackPresenter.createTrack()` . Could you help?

**Comment by srv-twry** [comment]
It's hard to say from here. 
I guess it could be because of this line in the ```createTrack``` method -> 
``` Java
long eventId = ContextManager.getSelectedEvent().getId();
```

**Comment by iamareebjamal** [comment]
Go ahead
