### ISSUE TITLE
Add confirm to delete for Copyright

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#914]
### Bug Report    

**Actual Behaviour**

The Copyright is deleted as soon as the user clicks on the delete button.

**Expected Behaviour**

There should a confirmation dialog before deleting the copyright.

**Steps to reproduce it**

Create a Copyright(if not present)
Click on the delete button.

**Would you like to work on the issue?**

Yes

**Parent issue**

#619

**Comment by srv-twry** [comment]
There is also a minor UI issue which can also be tackled in this issue itself. The buttons aren't alligned properly with the title of Copyright
![screenshot_2018-05-01-14-41-15-75](https://user-images.githubusercontent.com/21277837/39467952-4a9974c2-4d4e-11e8-8de6-7ba47a2d25ab.png)

**Comment by iamareebjamal** [comment]
Also make (C) grey
