### ISSUE TITLE
MVP - Model View Presenter pattern Implementation

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#92]
Currently the project is based on MVC (Model View Controller) pattern in which unit testing is difficult. Hence we will be implementing MVP pattern which facilitates unit testing.

Expected: Design MVP interface containing the required interfaces.

**Comment by iamareebjamal** [comment]
I have my exams now so I may only be helping in the design of the architecture :)

**Comment by mejariamol** [comment]
@iamareebjamal @Ronak-59 @Rishabhk07 We should consider using [Mosby MVP Library](https://github.com/sockeqwe/mosby) for implementing MVP. It will make the process relatively easier than starting from the scratch.

**Comment by iamareebjamal** [comment]
@mejariamol I think it ties our hand to a particular convention we might not need to follow

Furthermore, I have created a basic structure for app and we might also use dagger 2 in future in accordance to our needs

**Comment by iamareebjamal** [comment]
Also, I think it is basic enough so that we learn to do from scratch rather than relying on an opinionated platform so that we can adapt it according to our needs, like breaking the model temporarily for rapid prototyping
