### ISSUE TITLE
Selecting multiple FAQ's at once

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#921]
### Feature Request

**Feature Description**
Currently in the FAQ list mode there is an option to delete the faq's but only 1 faq can be selected and deleted at a time. I would like to add a feature where multiple FAQ's can be selected and deleted at once.

**Would you like to work on the issue?**
Yes!

@iamareebjamal Can I work on this issue?

**Comment by iamareebjamal** [comment]
Let's deal with this later as more features need attention than this
