### ISSUE TITLE
SignIn Error

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-orga-app#923]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Currently when I uncheck the URL on the login screen and enter any invalid url in the base URL, the login is still happening

**Expected Behaviour**

It shouldn't happen

**Steps to reproduce it**

Go to the main screen of app.
1. Uncheck the URL box
2. Enter anything in BASE URL
3. Click on login

**Android version and Phone Model**

Android 6.0, Asus Zenfone Max 
    

**Would you like to work on the issue?**
Yes @iamareebjamal

**Comment by codedsun** [comment]
@srv-twry Confirm it!

**Comment by iamareebjamal** [comment]
Not reproducible for me.

**Comment by codedsun** [comment]
@iamareebjamal It's working on my phone, please recheck! Even when no value is set in baseURL it's logs into my account on clicking signin

**Comment by codedsun** [comment]
@mishuvs @sridharjajoo Please confirm, I can reproduce this error till now!

**Comment by brijeshshah13** [comment]
@iamareebjamal I confirm it. BASE URL works for any text value or even when empty.

**Comment by codedsun** [comment]
@iamareebjamal Will send a pr by tommorow!

**Comment by Masquerade0097** [comment]
@codedsun Status ?
