### ISSUE TITLE
Implement Speakers module

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#925]
### Feature Request

**Feature Description**

Implement Speakers module since the Sessions module been implemented.

- [x] List Speakers(#647)
- [x] Tests for the module.
- [x] Speaker details
- [x] Tests for Speaker details

**Would you like to work on the issue?**

Yes

**Comment by srv-twry** [comment]
Fully implemented.

**Comment by iamareebjamal** [comment]
Speaker details are not shown along with the sessions they are speaking in

**Comment by srv-twry** [comment]
Implemented completely.
