### ISSUE TITLE
Allow creation of Speaker 

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#937]
### Feature Request

**Feature Description**

Allow creation of Speaker in the app.

**Would you like to work on the issue?**

Yes

**Parent issue**

#925

**Comment by srv-twry** [comment]
@iamareebjamal A speaker is supposed to have a relationship with a User object. Should I attach the logged in user as the User instance for the speaker ?

**Comment by iamareebjamal** [comment]
No, speaker user is the speaker itself.

**Comment by srv-twry** [comment]
@iamareebjamal I don't think it's in the scope of the app to create speakers. We can create forms for collecting speaker details. but speaker details have to be associated with a user account. Hence organizer cannot create it on his/her own.

**Comment by iamareebjamal** [comment]
Yeah, alright! @mariobehling @niranjan94 Please confirm

**Comment by srv-twry** [comment]
Closing this. Please reopen if I was wrong :)

**Comment by ShridharGoel** [comment]
Should we implement the feature to create speakers?

**Comment by iamareebjamal** [comment]
No
