### ISSUE TITLE
Adding option to Update and Delete Tickets

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#948]
### Feature Request

**Feature Description**
There should be an option to update and delete tickets as well.

**Would you like to work on the issue?**
Yes

@iamareebjamal I would like to work on this.

**Comment by iamareebjamal** [comment]
No, deleting tickets is involved in refunding orders and backend is not equipped with checks on pending or existing orders. So we already implemented this but it is hidden by default

**Comment by iamareebjamal** [comment]
Yeah, but you can update the ticket but still not sure how well it'd translate on the actual real world scenario. So let's skip this for the moment
