### ISSUE TITLE
Back pressing in SessionsFragment shows exit toast

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#949]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

Pressing back button in Sessions Fragment shows exit toast: "Press again to exit"

**Expected Behaviour**

It should get back to TracksFragment without asking to exit.

**Steps to reproduce it**

Press back button when SessionsFragment is active

**Gif**

![videotogif_2018 05 16_22 38 18](https://user-images.githubusercontent.com/35009811/40132322-2bff7fbc-595a-11e8-8da4-8700613430ab.gif)

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@mishuvs Can I work on the issue?

**Comment by iamareebjamal** [comment]
This is related to buggy backpress handler. Remove the double tap to exit feature completely

Simply keep popping back stack until empty

**Comment by mishuvs** [comment]
@iamareebjamal IMO the backpress handler isn't buggy as it's only responsible for displaying toast and exiting. I think the issue can be dealt with without removing the double tap to exit feature. Please have a look at the PR.
