### ISSUE TITLE
Adding check-in and ticket sales chart

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#970]
### Feature Request

**Feature Description**

As discussed in the meeting today, I would like to implement a feature similar to Event Brite's app where a check-in chart and ticket sales chart has been implemented on the dashboard.
I would like to use the library [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart) for the same.
- [ ] Check In time chart
- [ ] Ticket Sales chart

**Would you like to work on the issue?**
Yes.

**Comment by iamareebjamal** [comment]
This is already implemented, you just need to fix it according to new API.

**Comment by sridharjajoo** [comment]
@iamareebjamal I think the API for the checkin times is there in the docs but there is no API for the  ticket sales?

**Comment by iamareebjamal** [comment]
The attendees are the ticket sales

**Comment by mishuvs** [comment]
@sridharjajoo  can I work on one of them?

**Comment by sridharjajoo** [comment]
Sure you can work  the ticket sales chart

**Comment by sridharjajoo** [comment]
@iamareebjamal For the check-in times chart I wrote the following method:
```
public Completable loadDataCheckIn(long eventId) {
        clearData();
        return getAttendeeSource(eventId).doOnNext(attendee -> {
           String checkInTime = attendee.getCheckinTimes();
           addDataPointForCheckIn(checkInTimeMap, checkInTime);
        })
          .toList()
          .doAfterSuccess(attendees -> this.attendees = attendees)
          .toCompletable()
          .doOnComplete(() -> {
              if (error) throw new IllegalAccessException("No checkin's found");
              checkInDataSet = setData(checkInTimeMap, "checkintime");
              prepare();
          });
    }
```
Now setData is given as follows:
```
private LineDataSet setData (Map<String, Long> map, String label) throws ParseException {
List<Entry> entries = new ArrayList<>();
        for (Map.Entry<String, Long> entry : map.entrySet()) {
            String date = DateUtils.formatDateWithDefault(DateUtils.FORMAT_DAY_COMPLETE,entry.getKey());
            float time = DateUtils.getDate(entry.getKey()).toEpochSecond();

            entries.add(new Entry(time, entry.getValue(), date));
        }
        Collections.sort(entries, new EntryXComparator());

        // Add a starting date point ine day ago
        float dayMillis = 60 * 60 * 24 * 1000;
        entries.add(0, new Entry(entries.get(0).getX() - dayMillis, 0));
        return new LineDataSet(entries, label);
    }
```
I wanted to know that is my approach right because here
String date = DateUtils.formatDateWithDefault(DateUtils.FORMAT_DAY_COMPLETE,entry.getKey());
It gives an invalid date's format and also no graph is output.

**Comment by iamareebjamal** [comment]
First of all, you don't want LiveData during building the graph and all. This is a number crunching process, you simply need to load the numbers in background and update the entry values

Also, whatever you are doing in doAfterSucess and doAfterComplete should be done in subscribe of that completable. These methods are side effects, so they should not contain logic that is the direct result of execution of the code. Side Effects are used for logging and stuff, rarely business logic. Then the return type is Completable, which it shouldn't be, it should be some kind of data

Also, checkinTime**s** as the name suggests are times user was checked in separated by commas, not a single time entity. It it was, it would have been stored as ZonedDateTime

**Comment by iamareebjamal** [comment]
Also debugging like this is like flailing arms in the dark. Always push your PR and then ask questions
