### ISSUE TITLE
Improve login flow

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#971]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
     
### Feature Request

**Feature Description**

The login flow differs in Eventbrite in 3 ways:
- [ ] The first screen only has the email field. On clicking next, it detects if the email is registered.
    if yes -> it makes the password  field visible
    if no -> redirects to Signup screen

![videotogif_2018 05 24_04 39 23](https://user-images.githubusercontent.com/35009811/40456209-a37ccb64-5edf-11e8-99b5-9fb8e978fdeb.gif)

- [x] When in forgot password screen, the user doesn't have to rewrite the email. (#979 )

- [ ] If the email entered hasn't been changed after entering the login screen, it directly sends the email upon clicking 'forgot password'. If the user changes the email id, it hides the 'password' field and the 'forgot password' button.

![videotogif_2018 05 24_04 44 07](https://user-images.githubusercontent.com/35009811/40456250-d2c5a5da-5edf-11e8-9545-35d2e08e0612.gif)

**Would you like to work on the issue?**

Yes

**Comment by brijeshshah13** [comment]
@iamareebjamal @mishuvs Is this issue up for grabs?

**Comment by mishuvs** [comment]
@brijeshshah13  I intend to work on this. But I haven't been able to, since the API probably doesn't yet allow to check if an email is registered or not.

**Comment by iamareebjamal** [comment]
Even if so, I don't think it is that crucial to the flow of the app to be exactly same as Eventbrite

**Comment by mishuvs** [comment]
Then, should it be closed for now?

**Comment by srv-twry** [comment]
Although it's not on the radar now but the support has been added for it from the server side. 
@mishuvs @iamareebjamal

**Comment by mishuvs** [comment]
@srv-twry Will work on it after current issues.
