### ISSUE TITLE
Creating a Stepped approach for Event Creation

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#978]
### Feature Request

**Feature Description**
Currently the Create Event is done only in a single screen in a Fragment. It would be more helpful for the user if it is done in a stepped manner. Thereby I propose the implementation of a horizontal stepper for creating an event.

**Screenshots**
![tabs](https://user-images.githubusercontent.com/20684618/40559286-cf3547b4-6073-11e8-80d7-139c6bb68545.gif)

**Would you like to work on the issue?**
Yes

@iamareebjamal I would like to work on adding this feature.

**Comment by sridharjajoo** [comment]
@iamareebjamal I have divided the event creation into 4 fragments. All of these implement the same CreateEventView but it would lead to a lot of unimplemented methods in each of the fragments as the functionality is getting divided. So should I create a new view for each fragment that has been implemented with all fragments sharing a single presenter?

**Comment by iamareebjamal** [comment]
Only last fragment will have current event create view, all three fragments will have separate views and a shared ViewModel
