### ISSUE TITLE
Error Prone Integration

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-orga-app#984]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore

### Feature Request

**Feature Description**

This will help in catching the errors in the compile time itself.
https://github.com/tbroyer/gradle-errorprone-plugin

**Would you like to work on the issue?**

Yes! @iamareebjamal

**Comment by brijeshshah13** [comment]
@iamareebjamal @codedsun I've found the method to integrate it. Can I send the PR for the same if there is no issue?

**Comment by codedsun** [comment]
@brijeshshah13 I am working on it, will submit a PR by today. Feel free to take over other issues!

**Comment by iamareebjamal** [comment]
Bump for next version of error prone
