### ISSUE TITLE
FaqListFragment should allow updation and multiple deletion

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#986]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

FaqListFragment currently only allows deleting single FAQ item. Edit option is also not supported.
Functionality for both should be added to toolbar.
   
**Would you like to work on the issue?**

Yes

**Comment by sridharjajoo** [comment]
@mishuvs It is the same as [#921](https://github.com/fossasia/open-event-orga-app/issues/921)
