### ISSUE TITLE
Fix PMD and Checkstyle Issues

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#988]
https://584-65606855-gh.circle-artifacts.com/0/outputs/pmd/pmd.html
https://584-65606855-gh.circle-artifacts.com/0/outputs/checkstyle/checkstyle.html

@mishuvs @srv-twry @Masquerade0097 @sridharjajoo Please take a look

**Comment by mishuvs** [comment]
@sridharjajoo Are you working on this?

**Comment by sridharjajoo** [comment]
@mishuvs You can take this up
