### ISSUE TITLE
Attendees list remains same for different events

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#99]
On attendees list page, attendees are added to the same list instance when opened for different events.

**Comment by iamareebjamal** [comment]
@mejariamol Should be fixed by now. Can you confirm?

**Comment by mejariamol** [comment]
yes. it is fixed.

**Comment by iamareebjamal** [comment]
Please refer to the PR here which you think solved this issue. I guess MVP implementation of AttendeeActivity did it?

**Comment by mejariamol** [comment]
fixed with #116
