### ISSUE TITLE
Show speakers details in the app along with his/her sessions

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#996]
### Feature Request

**Feature Description**

The app should show the Speaker details in the application along with his/her sessions.

**Would you like to work on the issue?**

Yes

**Parent issue**

#925

**Comment by srv-twry** [comment]
@iamareebjamal I have facing a small issue. I am trying to implement this using MVVM instead of MVP.
I am having problems in converting Observable to LiveData in the ViewModel.
```Java
protected LiveData<Speaker> getSpeaker(long speakerId, boolean reload) {
        if (speaker != null && !reload)
            return speaker;

        Observable<Speaker> speakerObservable = speakerRepository.getSpeaker(speakerId, reload)
            .doOnSubscribe(disposable -> progress.setValue(true))
            .doOnError(throwable -> error.setValue(ErrorUtils.getMessage(throwable)))
            .doFinally(() -> progress.setValue(false));

        speaker = LiveDataReactiveStreams.fromPublisher(speakerObservable);
        return speaker;
    }
```

This doesn't work. An Observable isn't a Publisher and hence I don't think there is direct support for Observable to LiveData conversion.
Possible options:
1. Convert the Observable to Flowable and handle backpressure. I haven't used Flowable though hence not sure about it.
2. Use MutableLiveData and set the value manually.

Views please.

**Comment by iamareebjamal** [comment]
The data layer will always be in RxJava, only View layer will deal with LiveData

**Comment by iamareebjamal** [comment]
Use second option, see the new Open Event Android General for more info
