### ISSUE TITLE
Copy URL and Share Event Details Options

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#997]
**Feature Description**

Share option in Dashboard which will open a fragement containing options to -
1. Copy Event URL.
2. Share Event Details via Email.
3. Share Event Detail via Other apps.

EventBrite offer these functionalities.
![screenshot_20180530-015204](https://user-images.githubusercontent.com/23634977/40683462-5076077e-63ac-11e8-90af-1a2c1b625c96.png)

**Would you like to work on the issue?**

Yes

**Comment by iamareebjamal** [comment]
I think this is trivial. Sharing right now is probably fine. Take this up later

**Comment by Masquerade0097** [comment]
@iamareebjamal Can I send a PR for this now ?

**Comment by iamareebjamal** [comment]
Sure
